### ISSUE TITLE
BrewNote should contain a copy of a the recipe on the day it was brewed.

### ISSUE THREAD

**Issue by janjachnik** [Brewtarget/brewtarget#106]
I think it is quite common to make adjustments to a recipe over time. The current BrewNote system does not tell you the exact recipe on the day you brewed it. If I change the recipe and look back at past brews I have lost what I did. 

I think the easiest solution is for a BrewNote to contain a copy of the recipe. It would also require the relevant UI updates to display this information. 

There is a related request on the Google Groups but I think this place is more active:
https://groups.google.com/forum/#!topic/brewtarget-help/86WvJiZX_lk

**Comment by WI-Wino** [comment]
I use BrewTarget exclusively and would really like this feature as well. I would probably try to use the inventory feature if this available as well. I often subbed out a base grain for something close.

**Comment by mikfire** [comment]
I've an idea for this, but I need to finish the database thing first.

Mik

**Comment by onesnzerosimon** [comment]
Would be good if failsafe.
I just usually copy the recipe and append the date into the title. 
That way I don't lose any previous versions, and I can compare taste notes to improve them.

**Comment by pricelessbrewing** [comment]
Current workaround would be to use the file/recipe/export to BBcode/html, which can be pasted into the notes section. 

@mikfire Did you ever get around to your idea? If not, can you outline it? Maybe another dev will be able to take it up.

**Comment by matty0ung** [comment]
@pricelessbrewing I think https://github.com/Brewtarget/brewtarget/issues/327 was the idea @mikfire mentions above.

**Comment by mattiasmaahl** [comment]
As versioning is now a thing I will close this issue.
