### ISSUE TITLE
Brewtarget v2.3.0

### ISSUE THREAD

**Issue by rocketman768** [Brewtarget/brewtarget#107]
@Brewtarget/developers 

I plan to release v2.3.0 in January 2016. A couple of things about the release:

First, get your string changes in now. It usually takes a month or two for Launchpad to retranslate the strings that change. This means in the next couple of weeks, I'll have to branch off the v2.3.0 release and forbid further string changes until release. So, get in whatever UI/string changes as quickly as you can.

Second, we're going to try a different release branching strategy this time. For v2.2.0, I was experimenting with cherry-picking bug fixes to the stable branch (the way my prior employer likes to do it). I think it was a little weird. This time, we'll stick to [the git branching model](http://nvie.com/posts/a-successful-git-branching-model/) (except for now, we'll still use the master branch as the development branch). This means we'll base and submit bug fix pull requests directly to the stable/2.3.0 branch after it's created, and submit all other pull requests to the master branch.

This requires us to be careful _not to fix bugs_ while also working on a new feature. If you start to fix a bug, stop immediately and switch to the 2.3.0 branch and make a bug fix commit on top. I'll merge these commits into the master branch so the bug fixes propagate forward.

**Comment by rocketman768** [comment]
Last call for UI changes in 2.3.0. The new branch will be coming shortly.

**Comment by theophae** [comment]
I've noticed recently that I've forgotten to change another weird checkbox in miscellaneous tab used for weight or volume choice. Can I still change it know for 2.3.0 or it is too late ?

**Comment by rocketman768** [comment]
Go for it. I'll branch this weekend for 2.3.0 if you can make it by then.

**Comment by theophae** [comment]
Already done ;)

**Comment by rocketman768** [comment]
Branch stable/2.3.0 is pushed. Please make bugfix pull requests directly to the stable branch, all other requests against master.
