### ISSUE TITLE
Mac build is broken

### ISSUE THREAD

**Issue by JulianVolodia** [Brewtarget/brewtarget#111]
Every build have:
Error: Could not find app bundle "/Applications/brewtarget.app"

but do not stop. After my change:

Error: Could not find app bundle "/Applications/brewtarget.app"
make[2]: *** [CMakeFiles/addframeworks] Error 1
make[1]: *** [CMakeFiles/addframeworks.dir/all] Error 2
make: *** [all] Error 2

it fails.

Could you help me?

**Comment by rocketman768** [comment]
Not your fault. I guess the way we are building bundles is wrong.

**Comment by JulianVolodia** [comment]
I try to figure why, but I cannot find out...

Google also are silent...
I find in # http://pmarinc-tidylib.googlecode.com/hg/src/Sigil/CMakeLists.txt?r=8276c61e05bc385d5ffbcc58e1f007f84b0c52df
that they used project( ) with Uppercase firs letter (Sigil),
sth like this:
   set( MACOSX_BUNDLE_INFO_STRING "Sigil" )
   set( MACOSX_BUNDLE_BUNDLE_NAME "Sigil" )
and so on.

Maybe we just do not create that dir?

**Comment by rocketman768** [comment]
I think we have never built the mac bundle properly. I don't know the "right" way. I suspect the version of cmake on the integration server just changed and broke the way we were using it.

**Comment by JulianVolodia** [comment]
Could you show for which TravisCI return success?
