### ISSUE TITLE
QCoreApplication::applicationDirPath: Please instantiate the QApplication object first

### ISSUE THREAD

**Issue by JulianVolodia** [Brewtarget/brewtarget#115]
Should we do sth with it?

info in debug console output.

**Comment by rocketman768** [comment]
Is this coming from `QString Brewtarget::getConfigDir(bool *success)` at `brewtarget.cpp:429`? But yes, we should fix any warnings.

**Comment by rocketman768** [comment]
Also, Windows I presume?

**Comment by mikfire** [comment]
This was fixed with mr #229
