### ISSUE TITLE
New ingredient can't be created into a folder

### ISSUE THREAD

**Issue by theophae** [Brewtarget/brewtarget#117]
If you create a folder for any type of ingredient (fermentable, hop, misc...) and you right click on this folder and choose to create a new ingredient, it won't be created into the folder, but it will appear at the end of the list. The only way to add it to the folder is to drag and drop it on the folder (which is really a pain)

**Comment by mikfire** [comment]
That shouldn't work that way. Let me see if I can figure out why it behaves
as it does.

Mik

On Tue, Nov 10, 2015 at 4:47 AM, theophae <notifications@github.com> wrote:

> If you create a folder for any type of ingredient (fermentable, hop,
> misc...) and you right click on this folder and choose to create a new
> ingredient, it won't be created into the folder, but it will appear at the
> end of the list. The only way to add it to the folder is to drag and drop
> it on the folder (which is really a pain)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Brewtarget/brewtarget/issues/117>.
>



-- 
In a world of ninja v. pirate, I pilot a Gundam

**Comment by mikfire** [comment]
Pull request #192 should fix this.
