### ISSUE TITLE
Style editor and locales with comma as decimal separator

### ISSUE THREAD

**Issue by carlesmu** [Brewtarget/brewtarget#130]
brewtarget version: 2-2-0 (downloaded from github)
    libqt5 version: 5.5.1
    platform: debian/testing (amd64)
    locale: LANG=ca_ES.utf8 (comma decimal separator, dot group separator).

When I change the densities in the style editor, some times it don't store the correct value, ant stores it as it the ',' was a thousand separator:

`1,048` --> [after changing the focus to other field] --> `1,048 sg` --> [save and reopen] `1.048,000 sg` (when the expected value is `1,048 sg`)

There are values which works fine (e.g.: `1,065` --> `1,065 sg` --> `1,065 sg`), could be because it is internally stored as 1,06499999999?

**Comment by rocketman768** [comment]
Unreproducible in stable/2.3.0
