### ISSUE TITLE
2.3.0 release imminent

### ISSUE THREAD

**Issue by rocketman768** [Brewtarget/brewtarget#134]
I'm about to pull the latest translations from launchpad and start making binaries. If you have any last-minute critical bugs or want to change something in the manual, speak now.

We have pretty much full translations for French, Spanish, and Portuguese. If any significant progress happens on the other translations in the next few months, I'll make a minor release with language updates.

**Comment by theophae** [comment]
Great news !

**Comment by mikfire** [comment]
See issue #142. There's a core dump on the first run of brewtarget that I haven't been able to trace beyond the new logging methods. Based on the current order of operations, I don't think a new install will ever be able to run.

**Comment by rocketman768** [comment]
Just uploaded the mac version [Brewtarget-2.3.0.dmg](https://github.com/Brewtarget/brewtarget/releases/download/v2.3.0/Brewtarget-2.3.0.dmg). Can someone with a Mac test to see if you can install and run it?
