### ISSUE TITLE
Recalc button

### ISSUE THREAD

**Issue by ddk1965** [Brewtarget/brewtarget#135]
When you change some features the changes are not yet done, ex. dialog ok but when you print out it is not the same so why not add a recalc button that force a complete calculation refresh of the recipe?

**Comment by pricelessbrewing** [comment]
Instead of a button, shouldn't this be something that is done automatically at the end of either user input, or when dialog is closed? Seems strange that this is an issue. 

Can anyone replicate and confirm? I haven't noticed such an issue.

**Comment by mattiasmaahl** [comment]
I believe this is fixed in develop? I'll close. can re-open if this is not the case.
