### ISSUE TITLE
No menu

### ISSUE THREAD

**Issue by ddk1965** [Brewtarget/brewtarget#136]
When I compile brewtarget on my laptop I have no menu bar. On my desktop I have one.
Ubuntu 14.04 any idea why?
Also how can I compile for the release version instead of the debug one?

**Comment by rocketman768** [comment]
Do you mean menu bar (File, View, etc.) or toolbar (icons)? If you mean you do not see icons in the toolbar, then for some reason you don't have the qt5 package with the svg plugin installed. On debian, this package is libqt5svg5.

Release build is done with cmake option `-DDO_RELEASE_BUILD=ON`. See [Brewtarget/debian-packaging](https://github.com/Brewtarget/debian-packaging), especially the `control` and `rules` file for other build questions.

**Comment by ddk1965** [comment]
It is the menu bar. Icons are ok.

**Comment by rocketman768** [comment]
Never seen that. Screenshot?

**Comment by ddk1965** [comment]
![screenshot from 2016-01-15 09 40 55](https://cloud.githubusercontent.com/assets/16631273/12348972/315207ac-bb6c-11e5-954d-ecf4280466d1.png)

**Comment by rocketman768** [comment]
The menu bar is very basic Qt functionality, so this is unlikely to be a Brewtarget bug. Does Ubuntu still have the Mac-style global menu bar?

![17eblpbylxuj9jpg](https://cloud.githubusercontent.com/assets/752558/12538759/ffa86a3e-c296-11e5-8801-0115149a842c.jpg)

**Comment by ddk1965** [comment]
I am using XFCE as desktop manager not Unity ...

**Comment by greggree** [comment]
This is why I hate downstream code changes that distros do. Conical probably patched Qt to do the funcky OSX style menus, and XFCE doesn't know how to handle that. Try installing qbittorrent and see if you have menus for that application in XFCE on Ubuntu 14.04.

**Comment by greggree** [comment]
Get the deb from the qbittorrent site, and not apt-get install. apt-get will probably get you a conical patched version.

**Comment by necrostylery** [comment]
Searching for an alternative for this issue I found this thread:
https://bugs.launchpad.net/ubuntu/+source/appmenu-qt5/+bug/1307619

and this comment solved my issue:
https://bugs.launchpad.net/ubuntu/+source/appmenu-qt5/+bug/1307619/comments/5

Maybe someone else could try it too.

**Comment by ddk1965** [comment]
Works like a charm!!!

Tx,

Philip ...

**Comment by pricelessbrewing** [comment]
Adding to things to test for next release. Maybe include in a troubleshooting FAQ for ubuntu/linux builds unless someone can confirm this is fixed in a newer build of this distro.

**Comment by mattiasmaahl** [comment]
Seeing as this bug is Ubuntu 14.04 related and that this version is no longer maintained I think we will close this issue.
