### ISSUE TITLE
Named Mash Editor missing show selected equipment only up and down arrows displayed

### ISSUE THREAD

**Issue by ddk1965** [Brewtarget/brewtarget#138]

**Comment by rocketman768** [comment]
Can you explain? You can attach images if necessary.

**Comment by ddk1965** [comment]
![screenshot from 2016-01-13 10 22 30](https://cloud.githubusercontent.com/assets/16631273/12290046/b095755a-b9df-11e5-90df-30def6153f25.png)

**Comment by rocketman768** [comment]
I think this is working as designed.

**Comment by rocketman768** [comment]
Closing as WAD.
