### ISSUE TITLE
Add or edit fermentable color input always in SRM

### ISSUE THREAD

**Issue by geiregjo** [Brewtarget/brewtarget#139]
When adding or editing a fermentable the color input forces the user the provide an SRM value. Note that my brewtarget install is configured to use EBC. I was able to add my fermentable by converting the EBC value to an SRM value using an online tool.

I hope the scenario is clear because I just started using brewtarget en ran into this issue setting up my first recipe. Also, where should we register suggestion to add new fermentables?

**Comment by ddk1965** [comment]
Do you get the error also if you right click on color and change the scale from srm to ebc?

**Comment by geiregjo** [comment]
Do you mean change the color in the Recipe tab or when changing the option? In both scenarios I don't get (visible) errors.

**Comment by ddk1965** [comment]
No go with your mouse on the text Color right click and change the scale from SRM to EBC works like a charm ...

**Comment by geiregjo** [comment]
Where is the "Color" text located? What window or location in the application? I can do this in multiple locations and there I can choose between: Default, EBC and SRM. This works fine but the issue is with adding or editing fermentables. There I can't right click the set the Color.

**Comment by ddk1965** [comment]
In version 2.3 you can just tested it.

**Comment by geiregjo** [comment]
I apologize, I used the Ubuntu Repo to install BrewTarget and got version 2.1. I build it from scratch and tested again. Everything is fine now. I'm sorry I wasted your time.
