### ISSUE TITLE
Broken windows installer for BT 2.3.0

### ISSUE THREAD

**Issue by theophae** [Brewtarget/brewtarget#140]
I tried to install the new release of brewtarget using the windows installer file. It is impossible to launch BT because of missing dll (icuin50.dll, icuuc50.dll and icudt52.dll) and event after adding these three dlls manually, I got another message saying that it couldn't find the Qt platform plugin "windows", so I support that one or more Qt dlls are missing.

**Comment by rocketman768** [comment]
Can you please try the version I just uploaded (brewtarget...rc2.exe)?

The windows part of the cmake files is a horrendous mess. It never EVER has worked the same way between two consecutive releases. I never know what plugins are missing, as they don't show up on a dependency walk, and obviously I have all the Qt DLLs installed to the system already, so everything just works always for me. This frustrates the hell out of me. Can someone please find a better way to create the installer package on Windows in a robust way?

**Comment by theophae** [comment]
It works with the rc2 version. I just don't understant how the intallation package can have the double of the size of the 2.1.0 version...

**Comment by rocketman768** [comment]
Dll hell. The webkit dll went from 15 MB to 30 MB, the new ic*.dll files add another 30 MB, etc.
