### ISSUE TITLE
Instruction increment trigger may be broken

### ISSUE THREAD

**Issue by mikfire** [Brewtarget/brewtarget#141]
I think there's a bug in the database triggers. The auto increment trigger looks like this:

      CREATE TRIGGER inc_ins_num AFTER INSERT ON instruction_in_recipe
      BEGIN
         UPDATE instruction_in_recipe SET instruction_number =
            (SELECT max(instruction_number) FROM instruction_in_recipe WHERE recipe_id = new.recipe_id) + 1
            WHERE rowid = new.rowid;
      END;

I suspect the problem is that there is no column named "rowid". I have no idea if there is an impact from this. I am deep in an interesting idea, or I would otherwise stop and fix it myself.

**Comment by rocketman768** [comment]
It would be weird if this were not a bug. I'm pretty sure everything in the database is keyed by a field named "id".

**Comment by EvansMike** [comment]
In sqlite3 rowid is a special column and is always created by default and doesn't show with .schema command.

**Comment by mikfire** [comment]
This seems to be working as expected. I will close the bug.
