### ISSUE TITLE
[master] foreign keys seem to need to be last

### ISSUE THREAD

**Issue by mikfire** [Brewtarget/brewtarget#144]
DatabaseSchemaHelper::create will fail to create the mashstep, recipe and brewnote tables. It would seem that SQLite wants foreign key declarations to be the last thing in the definition. 

It hasn't been noticed to date because we've always been able to copy default_db.sqlite into place, and then the DatabaseSchemaHelper:;create silently fails. 

As soon as I'm done playing around tonight, I will check in the fix for this.

**Comment by rocketman768** [comment]
This is against stable/2.3.0 and master, right?

Yeah, looks like from [this diagram](https://www.sqlite.org/lang_createtable.html) all constraints in a table must come after the column definitions.

**Comment by rocketman768** [comment]
Just tested stable/2.3.0 by deleting .config/brewtarget then cold starting. Since we are still shipping a version 1 default_db.sqlite in /usr/share/brewtarget, that gets copied on first start and then migrated.

**Comment by mikfire** [comment]
Yup. It isn't spectacularly urgent, and what I'm playing with will end up
fixing these. I'm simply opening tickets so I remember to do the work when
I'm done.

Mik



On Sun, Jan 24, 2016 at 9:27 PM, Philip Lee <notifications@github.com>
wrote:

> Just tested stable/2.3.0 by deleting .config/brewtarget then cold
> starting. Since we are still shipping a version 1 default_db.sqlite in
> /usr/share/brewtarget, that gets copied on first start and then migrated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Brewtarget/brewtarget/issues/144#issuecomment-174373566>
> .
>



-- 
In a world of ninja v. pirate, I pilot a Gundam

**Comment by mikfire** [comment]
Closed with the postgresql merge (mr #151 )
