### ISSUE TITLE
[master] use bool type in schema

### ISSUE THREAD

**Issue by mikfire** [Brewtarget/brewtarget#148]
This is against the master branch and does not impact the 2.3.0 release.

While SQLite implements booleans as integers, DatabaseSchemaHelper::create() really needs to define them as boolean columns, not integer columns.

Assign this to me, and I will fix when I am done playing.

**Comment by rocketman768** [comment]
What behavior will change by using BOOL explicitly?

**Comment by mikfire** [comment]
To directly answer the question asked, it makes a huge difference when talking to postgres. But it was fixed in merge #151
