### ISSUE TITLE
DatabaseSchemaHelper defines mash.name as not null

### ISSUE THREAD

**Issue by mikfire** [Brewtarget/brewtarget#149]
As with anything mentioning DatabaseSchemaHelper, this can be ignored for the 2.3.0 release.

According to the definitions in DatabaseSchemaHelper::create(), mash.name is not null. My personal database has approximately 95 mash entries with a null name. As mashes are not named by default, I am assuming DatabaseSchemaHelper::create() is wrong in this instance.

Assign this to me, I will fix when I'm done with other things.

**Comment by mikfire** [comment]
To quote a serbian friend, huuuu. I have three very odd mashstep entries with no name either. They look completely bogus, and I've cleaned them out. 

Could the other devs check to see if they have similar bogus entries? Open up the sqlite database and run this query:
  select * from mashstep where name='';

**Comment by rocketman768** [comment]
`null` is not the same as empty`''`. The query for a null name would be

    select * from mash where name is null;

**Comment by rocketman768** [comment]
Working as designed?

**Comment by rocketman768** [comment]
Closing as WAD
