### ISSUE TITLE
[master] DatabaseSchemaHelper() defines hop table incorrectly

### ISSUE THREAD

**Issue by mikfire** [Brewtarget/brewtarget#150]
Ignore for the 2.3.0 release -- assign to me and I will fix.

Two typos for the hop table: colHopHtype is incorrectly spelled as "htyp" and colHopHsi is incorrectly spelled as "his".

**Comment by rocketman768** [comment]
Must have been a slow-finger day...

**Comment by mikfire** [comment]
No worries. Hope I'm not looking like its an attack. I am going through all of this for the postgresql work. I log them as I find them :)

**Comment by mikfire** [comment]
Closed in mr #151
