### ISSUE TITLE
Require specific minimum Qt version in CMakeLists.txt

### ISSUE THREAD

**Issue by EvansMike** [Brewtarget/brewtarget#152]
This may not affect many users but I'm using and old version of Fedora (18) When compiling 3.2 I get:
fatal error: QCommandLineParser: No such file or directory
QCommandLineParser was first included in  QTBase version 5.2 (January 2014 ?) so users with 5.1 may have issues.
I can compile by removing the CL code in main using a version test. Of course I don't get to have CL options on my install.

**Comment by EvansMike** [comment]
Oops I should have attached a patch that tests for QT version and excludes CL parts if below 5.2
[qt5.patch.zip](https://github.com/Brewtarget/brewtarget/files/104933/qt5.patch.zip)

Like I say though it may not affect many users.

**Comment by EvansMike** [comment]
Or at least set minimum QT version in CMakeLists.txt I guess.

**Comment by rocketman768** [comment]
Yeah, desired fix would be to set a specific version in CMakeLists.txt.
