### ISSUE TITLE
Initial value of IBU Adjustments erronous on system use coma as decimal separator

### ISSUE THREAD

**Issue by theophae** [Brewtarget/brewtarget#158]
After a fresh install of BT 2.3.0 on windows, I noticed that the default values of IBU Adjustments were set to 10 000,000 instead of 10,000. This is obviously due to the use of coma as separator in my system configuration.
This bug is not blocking as if I set 10,000 as a new value it will remains as is.

**Comment by pricelessbrewing** [comment]
Tested on latest dev build, looks like it's fixed. Close?

**Comment by pricelessbrewing** [comment]
@dpettersson can you test this on linux and see if it's an issue for you?

**Comment by dpettersson** [comment]
Sure, i can test it.
But i saw something earlier. The develop branch has (compared to 2.4)  141 more commits and there are 2 that doesn't exist in develop that are in 2.4. Maybe we should merge develop into 2.4 (or vice versa). It would give a great boost to the functionality if we could do something like that.

**Comment by dpettersson** [comment]
It seems to work for me.
I tested it like this:
I moved the sqlite-db and started the program. It looked OK.

**Comment by mattiasmaahl** [comment]
closed?

**Comment by matty0ung** [comment]
Since, from the most recent comments, it looks like this is fixed, I'm closing.  Please re-open if I've misunderstood.
