### ISSUE TITLE
[stable/2.3.0] OG °P wrongly calculated for OG sg in refractometer tool

### ISSUE THREAD

**Issue by theophae** [Brewtarget/brewtarget#159]
If you enter the OG in sg then you enter the current gravity in °P, after clicking on calculate, the OG value in °P is fill with a wrong value (444 851,457 P for an OG of 1.067 sg in my case).

This is a minor bug as it doesn't prevent the tool to compute all this other values correctly.

**Comment by rocketman768** [comment]
![test](https://cloud.githubusercontent.com/assets/752558/12705112/7025ad84-c81f-11e5-91fb-d2eb9dcf3055.png)

**Comment by rocketman768** [comment]
(gdb) 
    74         else if( (!haveOP) && haveOG )
    (gdb) 
    76            originalPlato = Algorithms::SG_20C20C_toPlato( inputOG );
    (gdb) p inputOG
    $5 = 1.0669999999999999
    (gdb) n
    77            lineEdit_op->setText(originalPlato);
    (gdb) p originalPlato
    $6 = 16.365412456710942

**Comment by rocketman768** [comment]
@mikfire, how do I tell BtLineEdit in the call `lineEdit_op->setText(originalPlato);` that `originalPlato` is not in SG units?

    Brewtarget::displayAmount (amount=16.365412456710942, units=0x9f0ab0, precision=3, displayUnits=Unit::displayPlato, displayScale=Unit::noScale)
    at /home/philip/myc/brewtarget/rocketman768-brewtarget/src/brewtarget.cpp:1120
    1120       int fieldWidth = 0;
    (gdb) n
    1121       char format = 'f';
    (gdb) 
    1125       if( Algorithms::isNan(amount) || Algorithms::isInf(amount) )
    (gdb) 
    1129       if( units == 0 )
    (gdb) 
    1132       QString SIUnitName = units->getSIUnitName();
    (gdb) 
    1133       double SIAmount = units->toSI( amount );
    (gdb) 
    1134       QString ret;
    (gdb) p SIAmount
    $9 = 16.365412456710942
    (gdb) n
    1137       temp = findUnitSystem(units, displayUnits);
    (gdb) 
    1139       if ( temp == 0 )
    (gdb) 
    1142          ret = temp->displayAmount( amount, units, precision, displayScale );

**Comment by mikfire** [comment]
Set a property on the BtLineEdit called "forcedUnit" and then give it the
unitDisplay name of the unit you want to force the field to.

On Sun, Feb 7, 2016 at 7:24 PM, Philip Lee <notifications@github.com> wrote:

> @mikfire <https://github.com/mikfire>, how do I tell BtLineEdit in the
> call lineEdit_op->setText(originalPlato); that originalPlato is not in SG
> units?
>
> Brewtarget::displayAmount (amount=16.365412456710942, units=0x9f0ab0, precision=3, displayUnits=Unit::displayPlato, displayScale=Unit::noScale)
> at /home/philip/myc/brewtarget/rocketman768-brewtarget/src/brewtarget.cpp:1120
> 1120       int fieldWidth = 0;
> (gdb) n
> 1121       char format = 'f';
> (gdb)
> 1125       if( Algorithms::isNan(amount) || Algorithms::isInf(amount) )
> (gdb)
> 1129       if( units == 0 )
> (gdb)
> 1132       QString SIUnitName = units->getSIUnitName();
> (gdb)
> 1133       double SIAmount = units->toSI( amount );
> (gdb)
> 1134       QString ret;
> (gdb) p SIAmount
> $9 = 16.365412456710942
> (gdb) n
> 1137       temp = findUnitSystem(units, displayUnits);
> (gdb)
> 1139       if ( temp == 0 )
> (gdb)
> 1142          ret = temp->displayAmount( amount, units, precision, displayScale );
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Brewtarget/brewtarget/issues/159#issuecomment-181145974>
> .
>



-- 
In a world of ninja v. pirate, I pilot a Gundam
