### ISSUE TITLE
Static Analysis: null dereference in UnitSystem::displayAmount

### ISSUE THREAD

**Issue by rocketman768** [Brewtarget/brewtarget#16]
Bug reported by the clang static analyzer.

Description: Called C++ object pointer is null
File: UnitSystem.cpp
Line: 145

![bug2](https://cloud.githubusercontent.com/assets/752558/7079877/a61e2a16-deef-11e4-8aea-622ca59600f4.png)

**Comment by mikfire** [comment]
The static analysis is wrong. scaleToUnit cannot be empty. Line 112 makes sure of that. The loop will always be executed at least once and last will be initialized.

**Comment by rocketman768** [comment]
Yeah, static analysis can't catch implied dependencies. But, I don't see any harm to explicitly check `last` before dereferencing either. What do you think?
