### ISSUE TITLE
Brewtarget Dependencies

### ISSUE THREAD

**Issue by danielm5** [Brewtarget/brewtarget#160]
I'd like to remove some dependencies to simply building on some platforms. For instance, I have my own reduced Qt build and some modules aren't available.

Specifically, I believed these dependencies can be safely removed:
- Qt5Qml
- Qt5Sensors
- Qt5Quick
- Qt5Positioning
- Qt5WebChannel

Probably Qt5WebKit and Qt5WebKitWidgets can be replaced by something simpler.

Could someone give me feedback on this? Thanks.

**Comment by mikfire** [comment]
I'm fairly certain the positioning and web channel can be removed. I've
plans to move to QtQml, which does require the QtQuick. Once I'm done with
that and my other project, I'll want the QtSensors.

I've no idea when I'll get to this projects, so take them out if you want.
I'll simply add them back in when I need them.

If you want to remove the webkit, make sure the manual loads and the print
functions work. There may be some other dependencies I'm not aware of.

Mik

**Comment by danielm5** [comment]
Thanks Mik!

I'd say we remove the unused modules and we add them back later if required, possibly with a cmake option to disable them if they are optional (similar to NO_QTMULTIMEDIA)

Webkit is deprecated in Qt 5.5 (http://doc.qt.io/qt-5/qtmodules.html), I'd say we update this. I'll be looking at this.
