### ISSUE TITLE
brewtarget_tests fail

### ISSUE THREAD

**Issue by EvansMike** [Brewtarget/brewtarget#161]
Running brewtarget_tests gives the following output:

********* Start testing of Testing *********
Config: Using QtTest library 5.1.1, Qt 5.1.1
PASS   : Testing::initTestCase()
PASS   : Testing::pstdintTest()
PASS   : Testing::runTest()
PASS   : Testing::recipeCalcTest_allGrain()
QDEBUG : Testing::postBoilLossOgTest() "a: 1.04292, b: 1.04719, tol: 0.002" 
FAIL!  : Testing::postBoilLossOgTest() 'fuzzyComp(recLoss->og(), recNoLoss->og(), 0.002)' returned FALSE. (OG of recipe with post-boil loss is different from no-loss recipe)
   Loc: [/home/mikee/Projects/brewtarget/src/Testing.cpp(232)]
[11:29:57.426] INFO : Brewtarget is cleaning up.
PASS   : Testing::cleanupTestCase()
Totals: 5 passed, 1 failed, 0 skipped
********* Finished testing of Testing *********

The failure is correct however. The test to allow for trub losses increases the water volume by 2L to maintain the final volume but, since the grain volume is not increased in proportion the SG will be lower and so trigger the error.  The grain needs to be increased (in the test) by a proportional amount.

**Comment by rocketman768** [comment]
Agree: bad test. Is it clearer to increase the grain or to just let the final batch size be 2L less?

**Comment by EvansMike** [comment]
Good test, just needs tweaking a bit.
Adjusting the batchSize and boilSize by - trubChillerLoss_l is clearer I think and tests all pass. I'll do a pull request.
