### ISSUE TITLE
Update the download page on the website

### ISSUE THREAD

**Issue by ddk1965** [Brewtarget/brewtarget#165]
I supply already the Ubuntu version to many home brewers but I can't compile for Windows.
So can someone please update the website with a downloadable Windows version 2.3?

**Comment by ddk1965** [comment]
Or send me a copy ;-)

**Comment by theophae** [comment]
You can already download the windows version here: https://github.com/Brewtarget/brewtarget/releases

**Comment by ddk1965** [comment]
Ok tx.
