### ISSUE TITLE
HopSortFilterProxy isn't quite behaving properly on TIMECOL

### ISSUE THREAD

**Issue by mikfire** [Brewtarget/brewtarget#182]
The hop time column is using the Units::kilogram in the call to Brewtarget::qStringToSI() instead of the more appropriate Units::minutes.

This is almost entirely invisible, since it sort of works regardless. But I am chasing other things, and this was annoying.

**Comment by rocketman768** [comment]
Does this apply to stable/2.3.1?

**Comment by mikfire** [comment]
It goes back to at least v2.2.0 -- I just checked the code. Hold on. It's a trivial fix.

**Comment by mikfire** [comment]
I created the pull. I think you would have to work pretty hard to actually see the error. Something like a dry hop done for 2 hours and another done for 1 day and it only affects the sorting.
