### ISSUE TITLE
In Extras tab the *Age  (days) lineEdit box should default to days.

### ISSUE THREAD

**Issue by EvansMike** [Brewtarget/brewtarget#184]
Currently the default values for these input boxes appear to be minutes, when the label clearly says days. The default units for these boxes should be set to days.
I'm looking at the code but I cannot find where the units are set for a specific LineEdit.

**Comment by theophae** [comment]
The unit between parentheses must be removed as you can enter any time unit.

In the file BtLineEdit.cpp you can find this:
```cpp
void BtLineEdit::initializeProperties()
{
   QVariant unitName = property("forcedUnit");
```cpp

So, to force the unit, you need the add the option forcedUnit to the properties of the BtLineEdit in QtCreator.

**Comment by EvansMike** [comment]
Thanks theophae, that put me on the right track. Time though has to scaled so I had to do a little more work to add more functionality. I'll do a pull request soon(ish).
