### ISSUE TITLE
The feature of calculating ingredients

### ISSUE THREAD

**Issue by MasDenBy** [Brewtarget/brewtarget#188]
Sometimes homebrewers buy ingredients for some next brewing. It is really convenient because you can visit shop only one time and make some beers. But we have one trouble, each time when you are going to visit shop for the purpose of buying ingredients, you should calculate count of each malt, hops, yeasts and etc. It will be great if application can do it.

For example, we have two beer recipe (It is not real recipe, just an example).

Beer 1:
Wheat malt - 1.5 kg.
Carabelge - 0.5 kg.
Cascade - 10 g.
US-05 - 11.5 g.

Beer 2:
Wheat malt - 2.5 kg.
Caraaroma - 0.3 kg.
Cascade - 10 g.
Amarillo - 15 g.
US-05 - 11.5 g.

User opens the window to calculate ingredients and add two recipes (Beer 1, Beer 2). The application calculates all ingredients and show a table with all things what user should buy:
Wheat malt - 4 kg.
Carabelge - 0.5 kg.
Caraaroma - 0.3 kg.
Cascade - 20 g.
Amarillo - 15 g.
US-05 - 23 g.

**Comment by rodrigoA** [comment]
Very nice. In my case it would help reduce waste on hops and specialt malts.
Looking forward this feature.

**Comment by pricelessbrewing** [comment]
Closing, #322 includes this issue and should be used instead.
