### ISSUE TITLE
[stable/2.3.1] build fails on finding Qt5LinguistTools on debian/sid

### ISSUE THREAD

**Issue by rocketman768** [Brewtarget/brewtarget#190]
Could not find a package configuration file provided by "Qt5LinguistTools"
      with any of the following names:
    
        Qt5LinguistToolsConfig.cmake
        qt5linguisttools-config.cmake

This is no longer a part of the qttools-dev package. I don't think we need it anyway.

**Comment by rocketman768** [comment]
Well, it seems that is where QT5_ADD_TRANSLATION is defined on debian/jessie...

**Comment by rocketman768** [comment]
Qt5LinguistToolsConfig.cmake is in different packages depending on the release? WTF is going on at debian?

- jessie: qttools-dev
- stretch: qttools5-dev-tools
- sid: qttools5-dev-tools
- experimental: qttools-dev

**Comment by theophae** [comment]
I've noticed this previously so I've added qttools5-dev-tools to the required packages on the wiki. But it seems very strange to me too.

**Comment by rocketman768** [comment]
Fixed in a0571fb in debian-packaging
