### ISSUE TITLE
Color range wrongly updated after style change

### ISSUE THREAD

**Issue by rocketman768** [Brewtarget/brewtarget#2]
As reported by @theophae

I noticed that if have set EBC as default unit in parameters, if you change the style of the beer in the recipe, the color range of the style is not updated correctly. To get the right display, you need to right click on "Color" and change the display unit to another one and to change it again to EBC. After doing this, the color range changes to fit the right value.

**Comment by theophae** [comment]
I don't know how to assign it to me, but I'll take care of it. I've already found were the bug is, but as I'm still a newbie with git, I need to learn how to use it before to send my patch.
