### ISSUE TITLE
Compiling last master give me this error ...

### ISSUE THREAD

**Issue by ddk1965** [Brewtarget/brewtarget#201]
CMake Error at CMakeLists.txt:115 (FIND_PACKAGE):
  Could not find a configuration file for package "Qt5Core" that is
  compatible with requested version "5.3".

  The following configuration files were considered but not accepted:

    /usr/lib/x86_64-linux-gnu/cmake/Qt5Core/Qt5CoreConfig.cmake, version: 5.2.1

**Comment by rocketman768** [comment]
WAD

**Comment by ddk1965** [comment]
WAD????

**Comment by rocketman768** [comment]
#152. If the min version can be lower, then ok lower it.

**Comment by EvansMike** [comment]
ref:
https://github.com/Brewtarget/brewtarget/issues/152
It should be 5.2

**Comment by ddk1965** [comment]
Sorry guys but I don't understand you can you at least write what is wrong and where I can change it?
Not in crypto code like WAD en #152 it should be 5.2 ...

Tx,

Danny

**Comment by ddk1965** [comment]
Ok I found it change the 5.3 to 5.1 in the CMakeLists.txt under Ubuntu 14.04 and it compiles ...
