### ISSUE TITLE
Crash re-creating brewday instructions

### ISSUE THREAD

**Issue by EvansMike** [Brewtarget/brewtarget#211]
With a fresh install,or with newly generated sqlite3 database. 
Pick a recipe and create the instructions.
Now click generate again, or delete one of the instructions.
Brewtarget crashes with the following output.

```
[10:11:35.486] ERROR : void Database::removeIngredientFromRecipe(Recipe*, BeerXMLElement*) failed to delete children. DELETE FROM instruction_children WHERE child_id=15 no such table: instruction_children Unable to execute statement
terminate called after throwing an instance of 'QString'
Aborted (core dumped)
```

**Comment by mikfire** [comment]
Assign this to me.

Mik

**Comment by EvansMike** [comment]
database.cpp line 705.  You could just create a dummy table "instruction_children" .

**Comment by mikfire** [comment]
No. I would rather fix the method to work properly. I just need to figure
out what exactly "properly" means in this instance.

On Mon, Mar 7, 2016 at 6:02 AM, Mike Evans <notifications@github.com> wrote:

> database.cpp line 705. You could just create a dummy table
> "instruction_children" .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Brewtarget/brewtarget/issues/211#issuecomment-193205850>
> .
>



-- 
In a world of ninja v. pirate, I pilot a Gundam
