### ISSUE TITLE
TravisCI can't find webkit because it's gone forever

### ISSUE THREAD

**Issue by rocketman768** [Brewtarget/brewtarget#217]
They must have updated their qt5 packages. The builds are all failing to find webkit.

**Comment by rocketman768** [comment]
Well, webkit is gone in 5.6. The replacement is supposed to be WebEngine, but I don't see a package that provides it in debian. I am also reading that it can only be built with MSVC in Windows?

Uh, help?

**Comment by rocketman768** [comment]
Convert the html viewers into QTextEdits maybe? They accept html.

**Comment by mikfire** [comment]
I will dig at it, but it will take me a while. I am tracking four different
distros, and I don't think any of then (gentoo included) are showing qt 5.6
yet.

Mik

On Sat, Mar 19, 2016 at 7:36 PM, Philip Lee <notifications@github.com>
wrote:

> Well, webkit is gone in 5.6. The replacement is supposed to be WebEngine,
> but I don't see a package that provides it in debian. I am also reading
> that it can only be built with MSVC in Windows?
>
> Uh, help?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Brewtarget/brewtarget/issues/217#issuecomment-198807701>
>



-- 
In a world of ninja v. pirate, I pilot a Gundam

**Comment by mikfire** [comment]
QTextBrowser works as a straight search/replace in RecipeFormatter and in
the BrewDay widgets. By the way, which one of those needs to go away? We
only use one, and I hate maintaining them both.

Anyway, give me 30 minutes and I will have a pull request for this.

Mik

On Sat, Mar 19, 2016 at 7:42 PM, Philip Lee <notifications@github.com>
wrote:

> Convert the html viewers into QTextEdits maybe? They accept html.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Brewtarget/brewtarget/issues/217#issuecomment-198809178>
>



-- 
In a world of ninja v. pirate, I pilot a Gundam
