### ISSUE TITLE
Bug: Incorrect mash temperature is shown in editor and grid

### ISSUE THREAD

**Issue by MasDenBy** [Brewtarget/brewtarget#220]
I've added mash step with time 75 min in editor it is shown as 1.250 hr, but in mash grid I see time 1 hr of this step.
![Incorrect ](https://photos-3.dropbox.com/t/2/AABKUXwUAgtASoKRJJ7jzDkAERf9lh7Sn-Df3-mmKdKzNA/12/53463655/png/32x32/3/1458493200/0/2/shot_160320_151225.png/EJjF28gDGOcCIAcoBw/ewRVOdBNpDGzgrzrMco5HaDB-azMSuTsSG7d1LQcj50?size_mode=3&size=1280x960)

**Comment by mikfire** [comment]
As a work around, if you right click on the Time column in the MashStep panel and then you select scale->minutes, it will display correctly.

It looks like time doesn't like being decimal. Let me track down the formatting rules, and I will fix.

**Comment by MasDenBy** [comment]
I've checked it and you are right after scale -> minutes it is displayed correctly. But now I have default formatting rules. If you need more informations please tell me what I should give you.

**Comment by xor-gate** [comment]
I think this is due to "forced-rounding" because when I enter 2 hop additions of 30 min and 1.5h the second addition is "upgraded" to 2h but in the brew instructions it is stated as 1.5h.

**Comment by mikfire** [comment]
This has been resolved with mr #222
