### ISSUE TITLE
Pedantic compiler warnings

### ISSUE THREAD

**Issue by speshak** [Brewtarget/brewtarget#233]
PR #228 introduced a large number of compiler warnings caused by an extra semi-colon:

> In file included from /vagrant/build/src/ui_recipeExtrasWidget.h:13:0,
                 from /vagrant/src/RecipeExtrasWidget.h:31,
                 from /vagrant/src/RecipeExtrasWidget.cpp:25:
/vagrant/src/BtLineEdit.h:51:105: warning: extra ‘;’ [-Wpedantic]
    Q_PROPERTY( int     type              READ type              WRITE setType              STORED false);
                                                                                                         ^
/vagrant/src/BtLineEdit.h:52:105: warning: extra ‘;’ [-Wpedantic]
    Q_PROPERTY( QString configSection     READ configSection     WRITE setConfigSection     STORED false);
                                                                                                         ^
/vagrant/src/BtLineEdit.h:53:105: warning: extra ‘;’ [-Wpedantic]
    Q_PROPERTY( QString editField         READ editField         WRITE setEditField         STORED false);
                                                                                                         ^
/vagrant/src/BtLineEdit.h:54:105: warning: extra ‘;’ [-Wpedantic]
    Q_PROPERTY( QString forcedUnit        READ forcedUnit        WRITE setForcedUnit        STORED false);
                                                                                                         ^
/vagrant/src/BtLineEdit.h:55:105: warning: extra ‘;’ [-Wpedantic]
    Q_PROPERTY( QString forcedScale       READ forcedScale       WRITE setForcedScale       STORED false);

**Comment by speshak** [comment]
@mikfire FYI

**Comment by mikfire** [comment]
Huh. I make clean and build from scratch every time I switch. Wonder why I
didn't get those.

And yes. Habits die hard, and EVERY line ends with a ; :)

On Tue, Mar 29, 2016 at 11:20 PM, Scott Peshak <notifications@github.com>
wrote:

> @mikfire <https://github.com/mikfire> FYI
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Brewtarget/brewtarget/issues/233#issuecomment-203227889>
>



-- 
In a world of ninja v. pirate, I pilot a Gundam
