### ISSUE TITLE
PPA is Way Out of Date

### ISSUE THREAD

**Issue by reverendj1** [Brewtarget/brewtarget#236]
The PPA (ppa:brewtarget-devs/brewtarget-releases) is woefully out of date. Looks like it is still 2.1, and hasn't been updated in about 1.5 years. The continuous integration PPA (ppa:brewtarget-devs/brewtarget) is a little better, but even that is at 2.2 and hasn't been updated in a year.

**Comment by mikfire** [comment]
I didn't think we were still maintaining a presence on launchpad?

**Comment by reverendj1** [comment]
Apparently you aren't. Ha. I think many would appreciate it if you did though. The [download page](http://www.brewtarget.org/download.html) still says, "For those using Ubuntu, you can get the latest release by using our PPA.".

**Comment by rocketman768** [comment]
I used to maintain a bunch of different builds. I got burnt out on trying to maintain all the packaging and all the building. A continuous integration server with windows/mac/debian/redhat builds all the time would be nice.

**Comment by malavv** [comment]
As you all know there are a few nice continuous integration server that are free for open source projects. [Travis CI](https://travis-ci.org/), for example, seems enterprise grade, free, and integrates with Github. I don't know if there is a way to automatically connect PPA to the CI server though.

**Comment by dvictori** [comment]
Any update on this issue? What would be the easiest way to install the latest BrewTarget on Ubuntu? PPA? .deb?  Docker? Snap?

**Comment by jawsdaws** [comment]
Unfortunately, there isn't a lot of activity on this project right now.  Your best bet to get the latest is going to be to build it yourself from the github repo, develop branch. The instructions are in the readme file.

**Comment by dvictori** [comment]
It's a pity because it's a great software and a good options for us brewers running Linux

**Comment by matty0ung** [comment]
Closing this as you can now download version 3.0.0 from https://github.com/Brewtarget/brewtarget/releases

I'm afraid I don't have access to https://launchpad.net/brewtarget to update it or shut it down so, for the moment, it exists as some sort of time capsule of a past version of the project I guess.
