### ISSUE TITLE
Can't enter 90 minutes in hops schedule

### ISSUE THREAD

**Issue by daleanson** [Brewtarget/brewtarget#243]
This is a little weird -- I go to the Hops tab and enter a hop and set the time for 90 minutes. The display changes it to 2 hr. I've tried 1.5 hr and the display changes to 2 hr again. However, if I do a print preview of the recipe, I see that it correctly shows 1.5 hr. I haven't checked the math extensively, but it appears that Brewtarget is calculating the IBU's correctly using the 90 minutes, even though it shows 2 hr. So I think this is just a display issue and not a calculation issue.

**Comment by daleanson** [comment]
Actually, this is probably the same issue as #220.

**Comment by mikfire** [comment]
This is a known issue. The work around is to right click on the label and select Scale -> Minutes. Everything is being stored properly, just not displayed properly.

The fix has been merged (pull request #222 even if the bug was a little misnamed) and should be out in the next release.

**Comment by mikfire** [comment]
I'm going to leave this open, so others can find it easier, but mark it as a duplicate

**Comment by pricelessbrewing** [comment]
@mikfire Can we create a label for stuff like this, maybe "solved" or "Reference" or something like that. I'm sure you noticed, but going through and cleaning up open issues atm. Hard to keep track of what's an existing issue when there's also stuff that's "oh, btw".

**Comment by matty0ung** [comment]
This is working in the current version of the code, so closing.
