### ISSUE TITLE
New mash type are behaving poorly

### ISSUE THREAD

**Issue by mikfire** [Brewtarget/brewtarget#244]
I just created a new recipe. If I do a double batch sparge with a grist ratio of 1.5 qt/lb, I get a warning saying that there is more liquid than mash tun. If I do a double batch sparge at a grist ratio of 2, no warning and the math works.

The sort order is also a little out of whack. 

Finally, I missed a few qDebug statements in there somewhere.

**Comment by mikfire** [comment]
I think I have it this time.

As a side question, is there a reason we load everything, everything, everything on startup? Could we maybe find a way to load only what is needed first (like whatever tree is focused, plus what is needed to display the recipe + ferms) and then load the rest as we need it? It would make the remote database stuff much faster.

**Comment by rocketman768** [comment]
>As a side question, is there a reason we load everything, everything, everything on startup?

Because that's how it used to work in-memory?

>Could we maybe find a way to load only what is needed first

Sure, if there is a principled way to figure that out.
