### ISSUE TITLE
Database VANISHED!!!

### ISSUE THREAD

**Issue by onesnzerosimon** [Brewtarget/brewtarget#247]
Everything is GONE, and i'm feking DEVESTATED.
I opened Brewtarget just now, and EVERYTHING is gone.
My recipes, my hop information, my malts, my yeasts…
devestated

OSX 10.8.5
Lastest Brewtarget install.

**Comment by cgiacofei** [comment]
I just had the same thing happen this morning, database seemed to have been reset to defaults. Fortunately I had backups.

At the time it happened I mistakenly had Brewtarget open on 2 machines sharing a synced data directory. Not sure if that had anything to do with it.

Running 2.3.0 on Ubuntu.

**Comment by mikfire** [comment]
Having two instances running against the same file is *always*
catastrophic. I think it has something to do with how sqlite locks the
files, how Qt responds to the lock and then how brewtarget interprets the
failure to open the database.

@onesnzersimon, I ... well crap. You may be able to recover if your
database was stored on something like a dropbox drive, maybe not. I really
wish I had something better to offer, but I am not sure how much I can do.


On Tue, Apr 26, 2016 at 2:26 PM, Chris Giacofei <notifications@github.com>
wrote:

> I just had the same thing happen this morning, database seemed to have
> been reset to defaults. Fortunately I had backups.
>
> At the time it happened I mistakenly had Brewtarget open on 2 machines
> sharing a synced data directory. Not sure if that had anything to do with
> it.
>
> Running 2.3.0 on Ubuntu.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Brewtarget/brewtarget/issues/247#issuecomment-214839996>
>



-- 
In a world of ninja v. pirate, I pilot a Gundam

**Comment by tpiszcze** [comment]
My database disappeared just minutes ago. Last time I used BT was yesterday night. For sure I did not open two instances. All was good at that time. Today it started with only default entries as the fresh installation. No message was displayed.
Few times in the past it happened to me to start two BTs but there was always error displayed and I was careful to stop second instance first to not lose database.

**Comment by recidive** [comment]
I've setup my equipment twice and added some recipes. No matter what I do, whenever I restart Brewtarget the database is always reset.

I just can't use the software and it's frustrating having hours of work lost.

It's completely broken on the Mac. And I'm not running two instances unless it's keeping it open in the background.

The software is great but not really usable.

**Comment by mikfire** [comment]
I do not have a Mac, so I cannot easily test this to figure out what is
going on.

Are you getting any dialogs asking you to either save your changes, or to
restore/rollback?

Mik

On Wed, May 18, 2016 at 7:42 AM, Henrique Recidive <notifications@github.com
> wrote:

> I've setup my equipment twice and added some recipes. No matter what I do,
> whenever I restart Brewtarget the database is always reset.
>
> I just can't use the software and it's frustrating having hours of work
> lost.
>
> It's completely broken on the Mac. And I'm not running two instances
> unless it's keeping it open in the background.
>
> The software is great but not really usable.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/Brewtarget/brewtarget/issues/247#issuecomment-220001557>
>



-- 
In a world of ninja v. pirate, I pilot a Gundam

**Comment by onesnzerosimon** [comment]
Since i lost a whole years work, not to mention the hours upon hours spent adding ingredients, I've bought Beersmith and I will never write another recipe in Brewtarget for as long as i live. I know, make more backups and all that, but damn.
I never had 2 instances going, but i recall i DID have 2 icons in launchpad for some reason.
Anyway, it's a real shame, but that was truly devastating. Once bitten...

**Comment by mikfire** [comment]
You know. Just in case I haven't said it? I am honestly upset that this has
happened to you.

I think I will take the time and write some code so that we are
automatically backing things up for people. It isn't the best solution, as
the directory will grow with out bounds, but it would have helped in this
situation.

Again. I am honestly and deeply sorry this has happened to you.

Mik



On Thu, May 19, 2016 at 11:13 AM, onesnzerosimon <notifications@github.com>
wrote:

> Since i lost a whole years work, not to mention the hours upon hours spent
> adding ingredients, I've bought Beersmith and I will never write another
> recipe in Brewtarget for as long as i live. I know, make more backups and
> all that, but damn.
> I never had 2 instances going, but i recall i DID have 2 icons in
> launchpad for some reason.
> Anyway, it's a real shame, but that was truly devastating. Once bitten...
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/Brewtarget/brewtarget/issues/247#issuecomment-220355680>
>



-- 
In a world of ninja v. pirate, I pilot a Gundam

**Comment by xor-gate** [comment]
@mikfire you could implement backup rotation/compression so it will not go out of hand.

**Comment by mikfire** [comment]
Yeah. I can't do the compression unless Qt offers something. I don't know enough about Windows and/or Mac to make sure I can find their built-in (if any) compression programs.

The design I have so far is something like this:
 
1. On the database option screen, give an option for how many backups to retain and where to put them. This will give people some control over how much space we eat, and where. It will also allow people to use dropbox or google drive or a samba share or whatever to make the backups non-local. The values will default to 10 and the data directory.
2. Every fourth clean start -- with "clean" defined as not seeing the rollback/restore dialog-- we backup the database before we open it. The backup name would be something like bt_database.isoTimeStamp, eg, bt_database.20160522. 
3. If the number of backups on disk exceeds the option, we remove the oldest backup.

I don't want to back up every clean start. I can see a case where a user has a corrupted database and opens brewtarget some number of times before realizing its gone pear shaped. If we backup every time, we stand the chance of overwriting the last good backup. It does mean the potential for lost work.

I am thinking I will allow -1, 0 and >0 as the number of backups to maintain. -1 means never remove them, 0 means never make them and >0 works as documented.

The hardest part is actually removing things. I am really considering just maintaining a list in the properties file of all the names. When the backup is made, the new name will be appended to the list. If the size of the list exceeds the number to maintain, we will start popping names off the list and removing them.

**Comment by xor-gate** [comment]
I found out that QByteArray class has a zlib compression native builtin (cross-platform).
http://doc.qt.io/qt-5/qbytearray.html#qCompress

**Comment by mikfire** [comment]
I don't have the plumbing in place, but I am thinking the option dialog screen gets rearranged. The directories tab goes away (which is something I wanted to do anyway), and you get this on the database tab if you have sqlite configured
![SQLITE option](https://dl.dropboxusercontent.com/u/25337777/shot-2016-05-22_16-14-46.jpg)

and this if you have postgres configured
![PGSQL option](https://dl.dropboxusercontent.com/u/25337777/shot-2016-05-22_16-14-58.jpg)

I am still working on the balance of the sqlite options, but that's the idea.

**Comment by mikfire** [comment]
Something like pull request #260. No compression, but I made things easy to configure so you can put the backups anywhere.

I still need to work on the dialog. It looks like crap, but it will take me some time to figure out what to do that doesn't look like crap.

**Comment by patrick-brian-mooney** [comment]
Me too. Entire database is just gone. Everything. Dozens of recipes, and all the yeast and other ingredient information I'd entered.

It just silently disappeared at some point between when I last used Brewtarget, maybe six weeks ago,  and when I opened it again just now.

Everything's gone.

Linux Mint 20 on x64 with Brewtarget 2.3.1.
