### ISSUE TITLE
Build problems on guidsx

### ISSUE THREAD

**Issue by mikfire** [Brewtarget/brewtarget#248]
./configure is complaining:
    CMake Error at CMakeLists.txt:112 (FIND_PACKAGE):
    By not providing "FindQt5Core.cmake" in CMAKE_MODULE_PATH this project has
    asked CMake to find a package configuration file provided by "Qt5Core", but
    CMake did not find one.

I need to get a vm installed and figure this out later.

**Comment by rocketman768** [comment]
What is guidsx?

**Comment by mikfire** [comment]
A very RMS package management system. I can't figure out how to start using it, but I want it on the list. Free beer tomorrow, free speech now.

**Comment by mattiasmaahl** [comment]
@mikfire Still a thing?

**Comment by matty0ung** [comment]
AFAIK build is now working on all supported platforms, so closing this ticket.  As ever, if I'm mistaken, please don't hesitate to re-open.
