### ISSUE TITLE
Multiple dialogs when cancelling an action for more than one Item in the tree

### ISSUE THREAD

**Issue by rocketman768** [Brewtarget/brewtarget#25]
From launchpad [#1445671](https://bugs.launchpad.net/brewtarget/+bug/1445671)

When selecting more than one Item in the tree (i.e. recipes) and choose
'copy' from the context-menue, a dialog appears which asks for a name
for each copy. If you decide to abort copying you have to cancel this
dialog for every previously selectet item. Maybe it would be nice if
hitting "cancel" once aborts all of the following copy-processes.

Brewtarget 2.1.0 on MacOS 10.10.3

**Comment by mikfire** [comment]
How do I assign this ticket to myself?

**Comment by rocketman768** [comment]
Directly to the right of the original comment, there is a column with "Labels," "Milestone," and "Assignee" sections. Click on assignee and you should see your id.

**Comment by mikfire** [comment]
The "click on assignee" doesn't work. As in, that isn't something I can click.

**Comment by rocketman768** [comment]
Hm. Let me see if there is some setting I have to change.

**Comment by mikfire** [comment]
Oh. I like that.
