### ISSUE TITLE
Instant crash when export to print (on Ubuntu)

### ISSUE THREAD

**Issue by OiPenguin** [Brewtarget/brewtarget#250]
I experience an instant crash of Brewtarget when attempting either:
File --> Brewday --> Print --> Print (from the dialogue box), or 
File --> Brewday --> Print preview

I've just upgraded from v 2.1.* to 2.3.0 on Ubuntu 16.04 and I experience the issue on both versions of Brewtarget. I'll be happy to trouble shoot, but need guidance.

**Comment by mikfire** [comment]
One of my numerous VMs is Kubuntu 16.04 and I cannot reproduce this.

If you have gdb installed, run brewtarget from a command prompt like this:

    $ gdb brewtarget
    (gdb) run

and then cause the crash. When that happens, go back to the gdb prompt and say

   (gdb) bt

and copy all the output from that here. You may have to page through a few windows of backtrace. Once you are done paging and back at a gdb prompt, say 

   (gdb) q
   Quit anyway? (y or n) y

which will close everything down.

You have a production copy, so most of the useful symbols will have been stripped but I might be able to see enough.

**Comment by OiPenguin** [comment]
Hi,

I've tried to recreate the error, however this time the program stalls
(fades grey, no response so I had to use xkill), but doesn't exit
immediately as in the initial bug report. I had to force quit it. Here's
the output from my session:
http://pastebin.com/ncDW3QRT

I'll be happy to trouble shoot further, please fire away.

On 5 May 2016 at 21:38, mikfire <notifications@github.com> wrote:

> One of my numerous VMs is Kubuntu 16.04 and I cannot reproduce this.
>
> If you have gdb installed, run brewtarget from a command prompt like this:
>
> $ gdb brewtarget
> (gdb) run
>
> and then cause the crash. When that happens, go back to the gdb prompt and
> say
>
> (gdb) bt
>
> and copy all the output from that here. You may have to page through a few
> windows of backtrace. Once you are done paging and back at a gdb prompt,
> say
>
> (gdb) q
> Quit anyway? (y or n) y
>
> which will close everything down.
>
> You have a production copy, so most of the useful symbols will have been
> stripped but I might be able to see enough.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Brewtarget/brewtarget/issues/250#issuecomment-217255115>
>



-- 
Vennlig hilsen,

Lars-Andreas Kvisle
+47 996 39 720
Eikeveien 12b
1470 Lørenskog

**Comment by mikfire** [comment]
I think the easiest thing now would be for me to get a copy of your database and see if I can find the malfunction.

If you can tarball brewtarget's files:

    $ tar -czf brewtarget.tgz .config/brewtarget

and put them somewhere I can download them (dropbox, google drive, whatever), I will try to figure out why your database is unhappy.

**Comment by OiPenguin** [comment]
Here you go:
https://www.dropbox.com/s/zgbhwxt3nxrsj3f/Lars-brewtarget.tgz?dl=0

Yours,

Lars

On 7 May 2016 at 15:45, mikfire <notifications@github.com> wrote:

> I think the easiest thing now would be for me to get a copy of your
> database and see if I can find the malfunction.
>
> If you can tarball brewtarget's files:
>
> $ tar -czf brewtarget.tgz .config/brewtarget
>
> and put them somewhere I can download them (dropbox, google drive,
> whatever), I will try to figure out why your database is unhappy.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Brewtarget/brewtarget/issues/250#issuecomment-217635981>
>



-- 
Vennlig hilsen,

Lars-Andreas Kvisle
+47 996 39 720
Eikeveien 12b
1470 Lørenskog

**Comment by mikfire** [comment]
If you give your recipe a style, brewtarget will stop crashing.

I'll fix the code so this doesn't happen, but it will take some time for
the patch to be released.

I'm still not certain why it has stopped working. I would suggest making
sure brewtarget isn't running, deleting .config/brewtarget/.pid and running
brewtarget again. If that didn't work, let me know and I will make another
guess.

Mik

On Sat, May 7, 2016 at 11:42 AM, OiPenguin <notifications@github.com> wrote:
> Here you go:
> https://www.dropbox.com/s/zgbhwxt3nxrsj3f/Lars-brewtarget.tgz?dl=0
>
> Yours,
>
> Lars
>
> On 7 May 2016 at 15:45, mikfire <notifications@github.com> wrote:
>
>> I think the easiest thing now would be for me to get a copy of your
>> database and see if I can find the malfunction.
>>
>> If you can tarball brewtarget's files:
>>
>> $ tar -czf brewtarget.tgz .config/brewtarget
>>
>> and put them somewhere I can download them (dropbox, google drive,
>> whatever), I will try to figure out why your database is unhappy.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>>
>> <
https://github.com/Brewtarget/brewtarget/issues/250#issuecomment-217635981>
>>
>
>
>
> --
> Vennlig hilsen,
>
> Lars-Andreas Kvisle
> +47 996 39 720
> Eikeveien 12b
> 1470 Lørenskog
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub

-- 
In a world of ninja v. pirate, I pilot a Gundam

**Comment by OiPenguin** [comment]
Excellent! Giving the receipe a style did magic. I'll keep that in mind and
update to the next version once that get released.

Thanks a lot!

Yours sincerely,

Lars

On 12 May 2016 at 00:08, mikfire <notifications@github.com> wrote:

> If you give your recipe a style, brewtarget will stop crashing.
>
> I'll fix the code so this doesn't happen, but it will take some time for
> the patch to be released.
>
> I'm still not certain why it has stopped working. I would suggest making
> sure brewtarget isn't running, deleting .config/brewtarget/.pid and running
> brewtarget again. If that didn't work, let me know and I will make another
> guess.
>
> Mik
>
> On Sat, May 7, 2016 at 11:42 AM, OiPenguin <notifications@github.com>
> wrote:
> > Here you go:
> > https://www.dropbox.com/s/zgbhwxt3nxrsj3f/Lars-brewtarget.tgz?dl=0
> >
> > Yours,
> >
> > Lars
> >
> > On 7 May 2016 at 15:45, mikfire <notifications@github.com> wrote:
> >
> >> I think the easiest thing now would be for me to get a copy of your
> >> database and see if I can find the malfunction.
> >>
> >> If you can tarball brewtarget's files:
> >>
> >> $ tar -czf brewtarget.tgz .config/brewtarget
> >>
> >> and put them somewhere I can download them (dropbox, google drive,
> >> whatever), I will try to figure out why your database is unhappy.
> >>
> >> —
> >> You are receiving this because you authored the thread.
> >> Reply to this email directly or view it on GitHub
> >>
> >> <
> https://github.com/Brewtarget/brewtarget/issues/250#issuecomment-217635981
> >
> >>
> >
> >
> >
> > --
> > Vennlig hilsen,
> >
> > Lars-Andreas Kvisle
> > +47 996 39 720
> > Eikeveien 12b
> > 1470 Lørenskog
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly or view it on GitHub
>
> --
> In a world of ninja v. pirate, I pilot a Gundam
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Brewtarget/brewtarget/issues/250#issuecomment-218605196>
>



-- 
Vennlig hilsen,

Lars-Andreas Kvisle
+47 996 39 720
Eikeveien 12b
1470 Lørenskog

**Comment by mikfire** [comment]
This got fixed, but I cannot find the merge request that did it.

**Comment by mordante** [comment]
I ran into the same issue as the original poster. (I tested with develop, but the differences between 2.4.0 and develop seem small.) Attached a patch against develop which fixes the issue.

Do you prefer patches or pull requests for these small changes?

[patch.txt](https://github.com/Brewtarget/brewtarget/files/466062/patch.txt)

**Comment by mikfire** [comment]
Pull requests are the preferred, but I thought I had fixed this already?
Did I miss a spot?

Mik

--
  Mik Firestone
  mikfire@fastmail.com



On Sun, Sep 11, 2016, at 11:22, mordante wrote:
> I ran into the same issue as the original poster. (I tested with
> develop, but the differences between 2.4.0 and develop seem small.)
> Attached a patch against develop which fixes the issue.
> Do you prefer patches or pull requests for these small changes?
> patch.txt[1]
> — You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub[2], or mute the
> thread[3].
>


Links:

  1. https://github.com/Brewtarget/brewtarget/files/466062/patch.txt
  2. https://github.com/Brewtarget/brewtarget/issues/250#issuecomment-246185893

**Comment by mordante** [comment]
Not sure what happened. But when I print a recipe without a style and equipment everything goes well. When I print a brewday the application segfaults. Debugging found deferring two NULL pointers. The patch I posted fixes these two issues. I created a pull request with the patch.

**Comment by mikfire** [comment]
Ah. I fixed half the problem -- printing the recipe. I did not try the
brewday printing.

--
  Mik Firestone
  mikfire@fastmail.com



On Mon, Sep 12, 2016, at 14:46, mordante wrote:
> Not sure what happened. But when I print a recipe without a style and
> equipment everything goes well. When I print a brewday the
> application segfaults. Debugging found deferring two NULL pointers.
> The patch I posted fixes these two issues. I created a pull request
> with the patch.
> — You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].
>


Links:

  1. https://github.com/Brewtarget/brewtarget/issues/250#issuecomment-246450200
