### ISSUE TITLE
Printing not working in develop

### ISSUE THREAD

**Issue by greggree** [Brewtarget/brewtarget#263]
Tried printing from the latest code on my linux box. Nothing comes out. All other apps are printing fine. Noticed this in the console:

QObject::connect: No such signal QTextBrowser::loadFinished(bool) in /home/greg/Sources/Linux/github/brewtarget/src/RecipeFormatter.cpp:1510

**Comment by mikfire** [comment]
Oh. That's likely not a good sign.

Looks like my drop-in replacement didn't work so well.

Do we want to find an alternate solution, or should I try to use the Qt5.6
web stuff?

On Sun, May 29, 2016 at 8:52 PM, Greg Greenaae <notifications@github.com>
wrote:

> Tried printing from the latest code on my linux box. Nothing comes out.
> All other apps are printing fine. Noticed this in the console:
>
> QObject::connect: No such signal QTextBrowser::loadFinished(bool) in
> /home/greg/Sources/Linux/github/brewtarget/src/RecipeFormatter.cpp:1510
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Brewtarget/brewtarget/issues/263>, or mute the thread
> <https://github.com/notifications/unsubscribe/AKxgF_nOQfkescBnSCxPrDlsvjgecyeRks5qGjTZgaJpZM4Ipa23>
> .
>



-- 
In a world of ninja v. pirate, I pilot a Gundam

**Comment by greggree** [comment]
What I have in the patch works now. Instead of trying to use a signal from the doc, I just load the doc and tell it to print. Both Brewday and Recipes print out and is close to the preview, except for some line breaks. I don't know the history yet, why did we move to TextBrowser from WebView?

**Comment by greggree** [comment]
Pull request for #263 has patch.

**Comment by mikfire** [comment]
We moved because it WebView was removed from Qt5.6. The Travis CI system
was on Qt 5.6, but none of us were. So I moved things around so that the
build system started working again.



On Sun, May 29, 2016 at 11:18 PM, Greg Greenaae <notifications@github.com>
wrote:

> Pull request for #263
> <https://github.com/Brewtarget/brewtarget/issues/263> has patch.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/Brewtarget/brewtarget/issues/263#issuecomment-222404199>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AKxgF1xGvhsZKnihsxyF75jXv1th9U5lks5qGlcRgaJpZM4Ipa23>
> .
>



-- 
In a world of ninja v. pirate, I pilot a Gundam

**Comment by mikfire** [comment]
Clsoed by merge request #264
