### ISSUE TITLE
Moving mash steps doesn't update form.

### ISSUE THREAD

**Issue by greggree** [Brewtarget/brewtarget#267]
After the fix for #265, I noticed that the UI isn't updating to show the mash steps being moved around.

**Comment by mikfire** [comment]
This is likely a signal problem. All of the work I did to get postgreSQL working seems to have left a few out.

**Comment by mikfire** [comment]
@greggree check the merge request. I think it fixes as much as can be. I hope not a lot of people have bounced on that button, because it did some really wrong things. I don't think they could have, since it dumped core before you closed #265
