### ISSUE TITLE
Brewtarget release 2.4.0 is coming

### ISSUE THREAD

**Issue by mikfire** [Brewtarget/brewtarget#271]
@Brewtarget/developers, the summer release is coming and I will be guiding us through the release.

I think we are about feature complete. This release will include postgreSQL support, unit support on inputs and numerous bug supports and enhancements. I would like to get anything that isn't a bug fix finished and committed in the next week (until 2016/6/7) so I can start working on translations.

I would ask everybody to finish any work they are doing, submit the pull request, and then start testing the snot out of upstream/develop. If you find any issues, please make sure you submit the ticket.

**Comment by mikfire** [comment]
I have accepted all the enhancements for v2.4. Bug fixes only from here forward. 

I will be @ nhc this week, so don't expect much activity. Once I am back, I will be working on branching, translations, etc.

I am roughly targeting early July for this release.

Please build from upstream/develop and test like mad. I've rearranged a lot of the db code, and it has to work.

**Comment by rocketman768** [comment]
@Brewtarget/developers here is a list of open bugs targeted for 2.4.0. Please claim one or more and investigate.

## [2.4.0 bugs](https://github.com/Brewtarget/brewtarget/issues?utf8=%E2%9C%93&q=is%3Aopen+milestone%3Av2.4.0+label%3Abug)

**Comment by mikfire** [comment]
With mr #300, bug fixes for brewtarget v2.4 are done. Anything remaining will need to wait until v2.5. I will begin working on translations just as soon as I have bandwidth.

**Comment by JulianVolodia** [comment]
Hi, no hearing from me for long time.Is there anything to do with translations?

**Comment by mikfire** [comment]
I just uploaded the new files to launchpad.

Mik

--
  Mik Firestone
  mikfire@fastmail.com



On Mon, Sep 19, 2016, at 01:42, Volodia wrote:
> Hi, no hearing from me for long time.Is there anything to do with
> translations?
> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].
>


Links:

  1. https://github.com/Brewtarget/brewtarget/issues/271#issuecomment-247914464

**Comment by JulianVolodia** [comment]
Sorry, I didn't notice. And... don't know if you speak about GH commit or sth else ;) btw. I will do something else maybe ;) Best regards!

**Comment by Scimmia22** [comment]
So...

**Comment by Scimmia22** [comment]
At this point, skipping 2.4 and going straight to 2.5 or what?

**Comment by matty0ung** [comment]
@Scimmia22 AIUI the issue at this point is that we have to reverse-engineer how do releases because not everything is documented and previous folks who did it have moved on.  @mikfire has been documenting some of the process at https://github.com/Brewtarget/brewtarget/wiki/Uploading-and-Releasing, @mattiasmaahl and @xzfantom have been making solid suggestions about Windows build and install (see https://github.com/Brewtarget/brewtarget/issues/512).  Hopefully, once we can get 2.4 or whatever release out, then subsequent releases will be much easier and therefore somewhat more frequent.

**Comment by beren12** [comment]
I have 2.4 built on a mac, but i believe it currently uses a few libraries from fink which would have to be relocated by hand/script. I'm trying to get current HEAD built but that now wants more libs

**Comment by matty0ung** [comment]
Closing this as the release (now renamed from 2.4 to 3.0) is now done - see https://github.com/Brewtarget/brewtarget/releases
