### ISSUE TITLE
Signals, signals everywhere

### ISSUE THREAD

**Issue by mikfire** [Brewtarget/brewtarget#274]
As a simple exercise, open HopTableModel.cpp and add this line around just after line 202:

```
qDebug() << Q_FUNC_INFO << "Caught a signal: recObs->key():" << recObs->key();
```

Compile and run. I count 15 signals caught by the HopTableModel just to load one recipe. Multiply that by every object we initialize and that is a lot of signals that are mostly not required.

We can't fix this for the v2.4 release, but my top priority in v2.5 will be wrapping my head around the signals and trying to reduce the number of signals we generate.

**Comment by mattiasmaahl** [comment]
Is this still an issue in latest Develop? As far as I can see there are a lot fewer signals in the code now and the ones that is there now is not "unnecessary" IMHO.
close?

**Comment by mikfire** [comment]
I still think it is there, tbh. I still haven't found a good way to catalog them all.
