### ISSUE TITLE
Nested html documents in recipe printout

### ISSUE THREAD

**Issue by rocketman768** [Brewtarget/brewtarget#277]
The notes section of the recipe html has an entirely different document nested within:

         ...
         <h3>Notes</h3>
         <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
         <html>
            <head>
               <meta name="qrichtext" content="1" />
               <style type="text/css">
                  p, li { white-space: pre-wrap; }
               </style>
            </head>
            <body style=" font-family:'DejaVu Sans'; font-size:9pt; font-weight:400; font-style:normal;">
               <p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Refreshing and easy-drinking beer, this blonde is mildly hopped and approachable.</p>
            </body>
         </html>
      </div>

Is this right/allowed?

**Comment by mikfire** [comment]
Not sure about allowed, but I am fairly certain it isn't right. This may take me a while to figure out.

**Comment by mikfire** [comment]
That is the result of using QTextDocument().toHtml(), which very helpfully adds the HTML header. I need to figure this out, but I suspect I will have to unpack all of that.

**Comment by mikfire** [comment]
Closed with mr #295
