### ISSUE TITLE
Mash designer produces inconsistent results

### ISSUE THREAD

**Issue by mattipt** [Brewtarget/brewtarget#279]
I am having trouble with the mash designer. When I drag one slider around, the other sliders' values do not seem to update correctly. So for example when I drag the 'infusion/decoction amount' to its maximum value, the resulting infusion temp and total collected wort values vary wildly on repeated attempts.

Here's an example, setting infusion/decoction amount to its maximum value of 16.789 litres:
Try 1: infusion temp 77.174 C, total collected wort 8.876 l
Try 2: infusion temp 76.098 C, total collected wort 10.760 l
Try 3: infusion temp 82.910 C, total collected wort 3.586 l

This may have something to do with Brewtarget not updating the other fields fast enough when the mouse cursor reaches the end of the slider (and some change event is lost?) I don't know it it's related to the fact that the widgets themselves seem to be annoyingly resizing themselves to accommodate the changing numerical values.

I'm running Brewtarget 2.3.0 on Mac OS X.

**Comment by mattipt** [comment]
After a bit more investigation, it seems like the problem is still present on git head, with some additional oddities meaning not all slider values update automatically. I wrote a small patch that seems to fix the sliders mash designer for me; it's at http://enneu.net/files/mashdesigner.patch

The GUI glitch of widgets jittering while resizing to content remains.

Apart from that issue, the mash designer seems to have some other bugs too but I assume these are already known:

1. Selecting Batch Sparge as the step type has no effect on the range of the amount slider (used to work in 2.3 I believe.)

2. If hitting the target temperature would result in water hotter than boiling, the temperature slider reverses, with a higher-than-boiling temperature as its minimum value and boiling point as the maximum.

**Comment by rocketman768** [comment]
Yeah, definitely seems like some events get lost when I move the slider fast. I'll post a pull request with your patch for review (you can also do this instead of a patch if you find bugs in the future).

**Comment by rocketman768** [comment]
I'm splitting the other two issues you mentioned into other issues.
