### ISSUE TITLE
BtMassEdit fields are wrong

### ISSUE THREAD

**Issue by mikfire** [Brewtarget/brewtarget#28]
At some point during merge request 99, I changed the default mass from kg to g. While this is more scientifically accurate, it has broken the code. Specifically, open any equipment profile in the editor and note the weight of the mashtun. This problem is associated with any BtMassEdit field, but that is the easiest to demonstrate.

I either need to modify the toSI() and fromSI() methods for the US weights to convert into grams instead of kilograms, or I need to change the default back to kilograms. Which solution I pick will depend on how we have historically stored the information in the database -- as grams or kilograms.

**Comment by rocketman768** [comment]
Are you asking for an opinion on which solution? If so, I prefer to go back to kg, as that is the SI unit for mass.

**Comment by mikfire** [comment]
Not really. I was simply explaining I know what the problem is, I have two solutions and I just need some time to make sure which one is right. But we really shouldn't ship v2.2 until I do fix it :)
