### ISSUE TITLE
[Mash Designer] batch sparge type has no affect on water slider amount range

### ISSUE THREAD

**Issue by rocketman768** [Brewtarget/brewtarget#282]
@mattipt says:

Selecting Batch Sparge as the step type has no effect on the range of the amount slider (used to work in 2.3 I believe.)

**Comment by mikfire** [comment]
Sort of, but you've got it a little backwards. It isn't that the batch sparge has no effect on the range, it is that early infusion steps don't have any effect on the range.

If you've a 33L mash tun, and you do an initial infusion of 17L, v2.3.1 reduces the top range to 16L. 2.4.0 doesn't. So when you select a batch sparge, nothing happens.

**Comment by mikfire** [comment]
Closed with mr #296
