### ISSUE TITLE
Version 2.4.0 branched

### ISSUE THREAD

**Issue by mikfire** [Brewtarget/brewtarget#289]
@Brewtarget/developers 

The v2.4.0 stable branch has been created and pushed. Please build and start testing. Any bugs should be against that branch until we roll the release.

Mik

**Comment by randar68** [comment]
Is 2.4.0 going to be officially released?

**Comment by JulianVolodia** [comment]
0) Is it true that brewtarget seg. faults may happen more often when:
[10:02:40.129] ERROR : *Data directory "/usr/local/share/brewtarget" is missing.*  Some features will be unavaliable.
?
What will be not working? Could sb tell me?

1) Bug:
For file bad.db:
`
<bad/>
<xml>
asdfasdf
</xml>
`
./brewtarget --from-xml bad.db 
Segmentation fault

2) Bug:
![selection_011](https://cloud.githubusercontent.com/assets/1219023/26621992/147a8862-45e9-11e7-9969-46c5fb66a3bf.png)
After clean run, when click here where is seg. fault.

please review, cya

**Comment by pricelessbrewing** [comment]
Just checking in. I haven't really seen any movement in awhile,

**Comment by dpettersson** [comment]
It has been very quiet lately, but it is summer time so it is not totally
unexpected :)
I hope to be able to push som things later his week.

/Daniel P

2017-06-28 4:59 GMT+02:00 Priceless Brewing <notifications@github.com>:

**Comment by malavv** [comment]
Hey guys,

I am confused about the current state of deployment/releases.

- Why are there no win32-win64 targets on the Github 3.1 Release?
- Am I right in thinking that new features should be applied on
Brewtarget/develop?
- Am I right in thinking that bug fixes should be applied on
Brewtarget/stable/3.4.0?

Cheers!

**Comment by pricelessbrewing** [comment]
Coming up on 2 years now since 2.4 was branched. What's the status? Is there something holding up the release, new features or just bug testing? Any chance of starting a project board for what needs to be done before release, and/or what is being developed for the next release?

**Comment by dpettersson** [comment]
I think that we need to ask @rocketman768 and @mikfire about the state of the release. 
I really dont have a complete overview of it.

**Comment by MrHaroldA** [comment]
And here's your kind annual reminder ;)

**Comment by JulianVolodia** [comment]
Hi @rocketman768 @mikfire  does project died? Or changed to perpetual beta called sometimes go-bananas?

**Comment by mikfire** [comment]
The direct answer is that @rocketman768 left me in charge, and that was likely a Bad Idea. The 2.4 release stalled because I have no idea how to handle the translations. It is also stalled because I really suck as a release manager. It is both too close to my day job for me to enjoy it as a hobby, and I really just want to code.

If anybody wants the job of organizing the releases, I am more than happy to turn those powers over to somebody who wants to do it.

**Comment by JulianVolodia** [comment]
Hi @mikfire don't worry. I think we all struggle on doing great in work and as open source hobbists. More, I think it was hard to say explicitly above so good job.

As you say you have some daily experience, could you tell us what we could ask you for? How you will see next Brewtarget development as developer of it?

**Comment by matty0ung** [comment]
@mikfire If you are still looking for someone to manage releases, I'm happy to volunteer.

**Comment by mattiasmaahl** [comment]
I also want to see the 2.4 version come to life.
Can assist in building packages for all platforms except MacOS, I have not gotten a virtual MacOS to work. in the process though :)

**Comment by xzfantom** [comment]
> 
> 
> I also want to see the 2.4 version come to life.
> Can assist in building packages for all platforms except MacOS, I have not gotten a virtual MacOS to work. in the process though :)

GitHub Actions can take some work for preparing packages. I added some settings in my fork https://github.com/xzfantom/brewtarget/commit/8e47fab8165044f3b20bbd6e2e5ff96e1dc435d0 it does mostly what Travis do now, so I don't want to add it to main repo yet. If it would be possible to build packages automatically it would be great.

**Comment by matty0ung** [comment]
Closing this as the release (now renamed from 2.4 to 3.0) is now done - see https://github.com/Brewtarget/brewtarget/releases
