### ISSUE TITLE
Tun Volume Entered is 0

### ISSUE THREAD

**Issue by malavv** [Brewtarget/brewtarget#298]
This thing bothered me for a while, I think this warning is overzealous in many situation. When you create a new equipment, is you save before entering a non-zero volume for the mash tun, you will get the message `The tun volume you entered is 0. This may cause problem`.

First, 0 looks like an error msg, 0 ml, or 0 gal, would give me more confidence. The main issue however is that I am only doing extract based beer, and never had a mash tun. I always assumed that it didn't cause any problem since I didn't enter mashing steps, but this might worry a new user.

Can we change the error message for something like : `Using an empty mash tun will invalidate mashing calculation`? It might still be confusing but at least with a bit of knowledge you will know this does not apply to extract brewing.

**Comment by mikfire** [comment]
Does that make more sense? I agree, the warning isn't helpful. It is also tricky to word it so that it is. I would like to get this addressed, so I can start getting the translation work started

**Comment by mikfire** [comment]
Closed with mr #299

**Comment by malavv** [comment]
Sorry for the lack of updates. Looks alright, I think any additional comments/details could be addressed in the relevant section of the user manual. Thanks @mikfire
