### ISSUE TITLE
Converter tool crash

### ISSUE THREAD

**Issue by rocketman768** [Brewtarget/brewtarget#3]
@theophae says:

The converter tool (Tools->Convert Units) make the whole software crashes when no unit is entered for the input value, or when there is no space between the value and the unit.

Examples:

Input: 4
Output Units: g
Click on "Convert" -> Brewtarget crashes

or

Input: 4oz
Output Units: g
Click on "Convert" -> Brewtarget crashes

I've only tested it on windows 7 so I don't know what is the behaviour on Linux or Mac.

**Comment by IcanBENCHurCAT** [comment]
I am going to debug this.

**Comment by rocketman768** [comment]
Thank you!

**Comment by IcanBENCHurCAT** [comment]
This bug has been fixed in the current source, but has not been built for release.

**Comment by rocketman768** [comment]
I appreciate you checking. I'll close this issue once you complete the release check.

**Comment by IcanBENCHurCAT** [comment]
Verified, can be closed.
