### ISSUE TITLE
"Date First Brewed" should default to date recipe was created

### ISSUE THREAD

**Issue by MitchLillie** [Brewtarget/brewtarget#301]
To reproduce:
1. Create a new recipe
2. Navigate to "Extras" tab
3. Date first brewed shows 01 Jan 2011 as default

Expected behavior:
3. Date is current date when recipe is created

I realize this is small potatoes, but I'd like to get involved in contributing—happy to tackle this if there's interest.

**Comment by mikfire** [comment]
Regardless of the size, I prefer people to open tickets for the stuff
that annoys them.

If you can fix it and submit the pull request, then by all means do so.
If not, I will put this on my list of things to fix when I am looking
for some tickets to close.

Mik

--
  Mik Firestone
  mikfire@fastmail.com



On Tue, Aug 9, 2016, at 21:38, Mitch Lillie wrote:
> To reproduce:
>  1. Create a new recipe
>  2. Navigate to "Extras" tab
>  3. Date first brewed shows 01 Jan 2011 as default
> Expected behavior:
>  3. Date is current date when recipe is created
> I realize this is small potatoes, but I'd like to get involved in
> contributing—happy to tackle this if there's interest.
> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].
>


Links:

  1. https://github.com/Brewtarget/brewtarget/issues/301
