### ISSUE TITLE
Database performance

### ISSUE THREAD

**Issue by mikfire** [Brewtarget/brewtarget#309]
# Database performance tuning
When running against Postgresql, I noticed the initial load was slow. My rough count suggested 15 seconds from the time brewtarget started until it drew the screen.

# tl;dr summary
With a bit of database sleuthing, I've been able to reduce the startup time using postgresql from 15 seconds to 2 seconds and the startup times with the sqlite database are averaging 0.4 seconds. In exchange, we have to accept some very limited caching.

I would like to put these against the 2.4.0 branch because I think it is important. 

## Read the rest though
There's some interesting stuff in here, and some nice tools in postgresql that finally let me inspect what we are doing enough to find the problem and fix it. If I get nothing else from the postgresql change, this was worth it.

**Comment by mikfire** [comment]
# Initial investigations
My first pass was to instrument the load to see if the problem was associated with any specific part. What I was able to generate looked like this:

     [19:19:37.275] INFO : Loading database.
     [19:19:37.707] INFO : Starting Brewtarget.
     [19:19:37.708] INFO : Initializing GUI.
     [19:19:37.765] INFO : setupUI -- initializing trees
     [19:19:37.765] INFO : setupUI -- initializing tabTree_recipe
     [19:19:38.532] INFO : setupUI -- initializing tabTree_style
     [19:19:39.577] INFO : setupUI -- initializing tabTree_equip
     [19:19:39.691] INFO : setupUI -- initializing tabTree_ferm
     [19:19:41.367] INFO : setupUI -- initializing tabTree_hops
     [19:19:42.004] INFO : setupUI -- initializing tabTree_misc
     [19:19:42.684] INFO : setupUI -- initializing tabTree_yeast
     [19:19:43.554] INFO : setupUI -- trees done
     [19:19:43.589] INFO : Initializing dialogs.
     [19:19:47.125] INFO : Initializing ranges.
     [19:19:47.126] INFO : Initializing comboboxes.
     [19:19:47.754] INFO : Initializing tables.
     [19:19:47.930] INFO : Initializing contextmenus.
     [19:19:47.931] INFO : Initializing geometries.
     [19:19:48.523] INFO : Initializing signals.
     [19:19:49.015] INFO : Initializing finished.

I am somewhat surprised it takes 4 seconds for us to initialize all of the dialogs. The total pretty much validates my impression; 12 seconds from the time we start until we are fully initialized. 

It also indicated the issue wasn't isolated to just one specific table or set of queries. It is just slow. This also made any performance tuning difficult; with no specific issue, I couldn't start using EXPLAIN to help tune any query.

I needed a way to simply time every query being run.

## Using Postgresql
Thankfully, postgresql has a bunch of plugins that can help. I tried several of them, but settled on pg\_stat\_statements. This gives me what I need without too much noise. I started the plugin, started brewtarget and then started examining the stats

    postgres=# SELECT query, calls, total_time, rows, 100.0 * shared_blks_hit /
    postgres-#                nullif(shared_blks_hit + shared_blks_read, 0) AS hit_percent
    postgres-#           FROM pg_stat_statements ORDER BY total_time DESC LIMIT 5;
                                 query                              | calls |    total_time    | rows |     hit_percent
    ----------------------------------------------------------------+-------+------------------+------+----------------------
     PREPARE qpsqlpstmt_25 AS SELECT * FROM misc WHERE id=$1        |  3663 |           169.03 | 3663 | 100.0000000000000000
     PREPARE qpsqlpstmt_27 AS SELECT * FROM fermentable WHERE id=$1 |  8711 | 125.702000000003 | 8711 | 100.0000000000000000
     PREPARE qpsqlpstmt_20 AS SELECT * FROM recipe WHERE id=$1      |  1780 |           51.747 | 1780 | 100.0000000000000000
     PREPARE qpsqlpstmt_1c AS SELECT * FROM yeast WHERE id=$1       |  4192 | 48.2080000000019 | 4192 | 100.0000000000000000
     PREPARE qpsqlpstmt_24 AS SELECT * FROM style WHERE id=$1       |  3046 | 42.0470000000007 | 3046 | 100.0000000000000000

The PREPARE in this does not mean the statement is being prepared, it means a prepared statement is being executed. The times are in milliseconds. Notice that the hit\_percent is 100, meaning we have loaded the entire database into cache.

But why are we querying the fermentable table 8,711 times?

## How Many?
The next question is just how many database queries are we making?

    postgres=# select sum(calls) from pg_stat_statements;
      sum
    -------
     28871
    (1 row)

Sweet mercy. No wonder this is taking so long. It doesn't matter that the entire database is cached in memory; 28,871 calls are going to take a lot of time. 

As important, we are returning the entire row each time. This means the database has to martial a lot of data, build the network packet for it, transmit the packet, etc.

## Why So Many?
With a bit more sleuthing, it quickly became apparent what was happening. Every time we get an attribute, the call ends up going to Database::get(), which looks like this:

    QVariant get( Brewtarget::DBTable table, int key, const char* col_name )
    {
       QSqlQuery& q = selectAll[table];
       q.bindValue( ":id", key );
       q.exec();
       if( !q.next() )
       {
          Brewtarget::logE( QString("Database::get(): %1 (%2) %3").arg(q.lastQuery()).arg(col_name).arg(q.lastError().text()));
          q.finish();
          return QVariant();
       }

       QVariant ret( q.record().value(col_name) );
       q.finish();
       return ret;
    }

selectAll is a hash that contains the prepared statements like this:

   SELECT * FROM fermentable WHERE id=:id

Every time any table, tree or editor loaded something, the Database::get() method was ultimately called. Apparently, we do that about 29,000 times in my database.

## Some Ideas
One immediate idea is to wonder why we provide the column name in the call to Database::get(), then return every column from the row, only to pluck the one column from that return. What if we just asked for the one column we wanted?

This causes a few issues with using a prepared query. PREPARE causes the database to build and cache a plan for how it will execute the query. This saves overhead on a frequently used query, because the planning is done once. But it does mean you cannot use place holders for column names, since that would change the planning.

What if we just don't worry about preparing the statement? I changed Database::get() to look like this

    QVariant get( Brewtarget::DBTable table, int key, const char* col_name )
    {
      QSqlQuery q(sqlDatabase());
      QString query = QString("SELECT %1 from %2 WHERE id=%3")
                        .arg(col_name)
                        .arg(tableNames[table])
                        .arg(key);

      q.exec(query);
      if( !q.next() )
      {
         Brewtarget::logE( QString("Database::get(): %1 (%2) %3").arg(q.lastQuery()).arg(col_name).arg(q.lastError().text()));
         q.finish();
         return QVariant();
      }

      QVariant ret( q.record().value(col_name) );
      q.finish();
      return ret;
    }

No prepared statement, but we are selecting just the column we want. A long build later (modifying database.h pretty much causes everything to recompile), we got the results.

### Results
Starting the modified version looked like:

    [19:28:31.115] INFO : Loading database.
    [19:28:31.593] INFO : Starting Brewtarget.
    [19:28:31.594] INFO : Initializing GUI.
    [19:28:31.654] INFO : setupUI -- initializing trees
    [19:28:31.655] INFO : setupUI -- initializing tabTree_recipe
    [19:28:32.263] INFO : setupUI -- initializing tabTree_style
    [19:28:32.524] INFO : setupUI -- initializing tabTree_equip
    [19:28:32.550] INFO : setupUI -- initializing tabTree_ferm
    [19:28:32.832] INFO : setupUI -- initializing tabTree_hops
    [19:28:33.033] INFO : setupUI -- initializing tabTree_misc
    [19:28:33.201] INFO : setupUI -- initializing tabTree_yeast
    [19:28:33.426] INFO : setupUI -- trees done
    [19:28:33.439] INFO : Initializing dialogs.
    [19:28:35.300] INFO : Initializing ranges.
    [19:28:35.300] INFO : Initializing comboboxes.
    [19:28:35.878] INFO : Initializing tables.
    [19:28:36.027] INFO : Initializing contextmenus.
    [19:28:36.028] INFO : Initializing geometries.
    [19:28:37.119] INFO : Initializing signals.
    [19:28:37.788] INFO : Initializing finished.

Roughly 6 seconds now to complete the initalization. Not bad for a fairly small hack.

Postgresql also indicated a good change:

      brewtarget=# SELECT query, calls, total_time, rows, 100.0 * shared_blks_hit /
                   nullif(shared_blks_hit + shared_blks_read, 0) AS hit_percent
              FROM pg_stat_statements ORDER BY total_time DESC LIMIT 5;
                        query                     | calls |    total_time    | rows |     hit_percent
      ----------------------------------------------+-------+------------------+------+----------------------
       SELECT name from misc WHERE id=?             |  1768 | 40.8189999999996 | 1768 | 100.0000000000000000
       SELECT amount_is_weight from misc WHERE id=? |   507 | 33.5320000000001 |  507 | 100.0000000000000000
       SELECT name from fermentable WHERE id=?      |  4347 | 30.4349999999988 | 4347 | 100.0000000000000000
       SELECT name from recipe WHERE id=?           |   998 | 29.7289999999998 |  998 | 100.0000000000000000
       SELECT name from style WHERE id=?            |  1616 |            26.01 | 1616 | 100.0000000000000000
      (5 rows)

      brewtarget=# select sum(calls) from pg_stat_statements;
        sum
      -------
       28871
      (1 row)

Same number of queries being called, but notice the times are significantly reduced. This strongly suggests some of the problem is the amount of data we were returning per query. But if we are calling the same query 4,347 times, wouldn't it be nice to prepare that?

## Being Well Prepared
With a few more changes, and a few new data structures, lets see what we can do?

    QVariant get( Brewtarget::DBTable table, int key, const char* col_name )
    {
       QSqlQuery q;
       QString index = QString("%1_%2").arg(tableNames[table]).arg(col_name);
   
       if ( ! selectSome.contains(index) ) {
          QString query = QString("SELECT %1 from %2 WHERE id=:id")
                            .arg(col_name)
                            .arg(tableNames[table]);
          q = QSqlQuery( sqlDatabase() );
          q.prepare(query);
          selectSome.insert(index,q);
       }
   
       q = selectSome.value(index);
       q.bindValue(":id", key);
   
       q.exec();
       if( !q.next() )
       {
          Brewtarget::logE( QString("Database::get(): %1 (%2) %3").arg(q.lastQuery()).arg(col_name).arg(q.lastError().text()));
          q.finish();
          return QVariant();
       }

       QVariant ret( q.record().value(col_name) );
       q.finish();
       return ret;
    }

So now we use a QHash to store a prepared query. If the query isn't in there, we build it on the fly.

### Results
Startup looked like this:

      [20:06:46.011] INFO : Loading database.
      [20:06:46.495] INFO : Starting Brewtarget.
      [20:06:46.496] INFO : Initializing GUI.
      [20:06:46.573] INFO : setupUI -- initializing trees
      [20:06:46.574] INFO : setupUI -- initializing tabTree_recipe
      [20:06:47.121] INFO : setupUI -- initializing tabTree_style
      [20:06:47.389] INFO : setupUI -- initializing tabTree_equip
      [20:06:47.434] INFO : setupUI -- initializing tabTree_ferm
      [20:06:48.182] INFO : setupUI -- initializing tabTree_hops
      [20:06:48.703] INFO : setupUI -- initializing tabTree_misc
      [20:06:49.126] INFO : setupUI -- initializing tabTree_yeast
      [20:06:49.422] INFO : setupUI -- trees done
      [20:06:49.444] INFO : Initializing dialogs.
      [20:06:51.681] INFO : Initializing ranges.
      [20:06:51.682] INFO : Initializing comboboxes.
      [20:06:52.124] INFO : Initializing tables.
      [20:06:52.266] INFO : Initializing contextmenus.
      [20:06:52.267] INFO : Initializing geometries.
      [20:06:53.080] INFO : Initializing signals.
      [20:06:53.533] INFO : Initializing finished.

No real difference. About 7 seconds from start to finish.

pg\_stat\_statments says this:

      brewtarget=# SELECT query, calls, total_time, rows, 100.0 * shared_blks_hit /
                       nullif(shared_blks_hit + shared_blks_read, 0) AS hit_percent
                FROM pg_stat_statements ORDER BY total_time DESC LIMIT 5;
                                         query                                 | calls |    total_time    | rows |     hit_percent
          -----------------------------------------------------------------------+-------+------------------+------+----------------------
           PREPARE qpsqlpstmt_49 AS SELECT name from fermentable WHERE id=$1     |  4403 | 55.9060000000005 | 4403 | 100.0000000000000000
           PREPARE qpsqlpstmt_38 AS SELECT name from recipe WHERE id=$1          |  1673 | 54.0079999999996 | 1673 | 100.0000000000000000
           PREPARE qpsqlpstmt_53 AS SELECT name from misc WHERE id=$1            |  1768 | 47.2299999999999 | 1768 | 100.0000000000000000
           SELECT parent_id FROM fermentable_children WHERE child_id = ? LIMIT ? |   297 |            35.65 |  100 | 100.0000000000000000
           PREPARE qpsqlpstmt_3a AS SELECT date from recipe WHERE id=$1          |   878 | 34.8619999999999 |  878 | 100.0000000000000000
          (5 rows)

It is nice to see that we are mostly hitting prepared statements, but... odd that not only was there little change in the load time, the total time spent getting the name of all fermentable's almost doubled.

I am still somewhat puzzled by this. A possible explanation is that prepared statements work best on large databases and complex queries. My database is quite small -- a couple thousand rows at best -- and is likely almost entirely in cache. PREPAREing the query probably just can't do that much more.

# Yeah. But 28891 queries?
That gets a lot more interesting. We have likely extracted just about as much efficiency from tuning the queries as we can get. Seriously, 4403 calls and spending a *total* of 56ms is ... um ... fast.

So the next approach has to be reducing the total number of queries. When doing this kind of optimization, it is helpful to know where to start. The previous queries ordered by most time spent. What do we see if we order by calls?

      postgres=# SELECT query, calls, total_time, rows, 100.0 * shared_blks_hit /
                   nullif(shared_blks_hit + shared_blks_read, 0) AS hit_percent
              FROM pg_stat_statements ORDER BY calls DESC LIMIT 10;
                                    query                                 | calls |    total_time    | rows |     hit_percent
      ----------------------------------------------------------------------+-------+------------------+------+----------------------
       PREPARE qpsqlpstmt_49 AS SELECT name from fermentable WHERE id=$1    |  4351 | 27.9010000000008 | 4351 | 100.0000000000000000
       PREPARE qpsqlpstmt_56 AS SELECT name from yeast WHERE id=$1          |  2508 | 15.3090000000004 | 2508 | 100.0000000000000000
       PREPARE qpsqlpstmt_53 AS SELECT name from misc WHERE id=$1           |  1768 | 39.3659999999996 | 1768 | 100.0000000000000000
       PREPARE qpsqlpstmt_4e AS SELECT name from hop WHERE id=$1            |  1751 | 11.2320000000001 | 1751 | 100.0000000000000000
       PREPARE qpsqlpstmt_3c AS SELECT name from style WHERE id=$1          |  1617 |           10.255 | 1617 |  99.9690785405071119
       PREPARE qpsqlpstmt_48 AS SELECT display from fermentable WHERE id=$1 |  1228 | 8.23500000000006 | 1228 | 100.0000000000000000
       PREPARE qpsqlpstmt_38 AS SELECT name from recipe WHERE id=$1         |  1088 | 18.4189999999999 | 1088 | 100.0000000000000000
       PREPARE qpsqlpstmt_4d AS SELECT display from hop WHERE id=$1         |  1032 | 6.86700000000002 | 1032 | 100.0000000000000000
       PREPARE qpsqlpstmt_68 AS SELECT amount from fermentable WHERE id=$1  |   966 | 7.05499999999993 |  966 | 100.0000000000000000
       PREPARE qpsqlpstmt_3e AS SELECT display from style WHERE id=$1       |   804 | 4.76099999999997 |  804 | 100.0000000000000000
      (10 rows)


## Caching. What could possibly go wrong?
One approach would be to start caching the values in memory instead of hitting the database each time. If we could just cache the name, it looks like we may be able to get some simple wins.

Since caching the name would get the biggest win for the least amount of work and the fermentable name is the most commonly requested, I will focus on that just to see what I get.

So we add a QString \_name to the fermentable, and change the getter and setter like this:

      QString Fermentable::name()
      {
         if ( _name.isEmpty() )
            _name = get("name").toString();

         return _name;
      }
      void Fermentable::setName( QString str )
      {
         set("name", "name", str);
         _name = str;
         emit changedName(str);
      }

Sorry, I had to strip some const declarations off, because the methods were no longer constant.

### Results

Start up looks like this:

      [21:44:21.834] INFO : Loading database.
      [21:44:22.087] INFO : Starting Brewtarget.
      [21:44:22.088] INFO : Initializing GUI.
      [21:44:22.118] INFO : setupUI -- initializing trees
      [21:44:22.118] INFO : setupUI -- initializing tabTree_recipe
      [21:44:22.441] INFO : setupUI -- initializing tabTree_style
      [21:44:22.687] INFO : setupUI -- initializing tabTree_equip
      [21:44:22.735] INFO : setupUI -- initializing tabTree_ferm
      [21:44:22.999] INFO : setupUI -- initializing tabTree_hops
      [21:44:23.287] INFO : setupUI -- initializing tabTree_misc
      [21:44:23.467] INFO : setupUI -- initializing tabTree_yeast
      [21:44:23.688] INFO : setupUI -- trees done
      [21:44:23.703] INFO : Initializing dialogs.
      [21:44:24.983] INFO : Initializing ranges.
      [21:44:24.983] INFO : Initializing comboboxes.
      [21:44:25.178] INFO : Initializing tables.
      [21:44:25.263] INFO : Initializing contextmenus.
      [21:44:25.264] INFO : Initializing geometries.
      [21:44:25.564] INFO : Initializing signals.
      [21:44:25.744] INFO : Initializing finished.

4 seconds from start to finish. This seems promising. Noticing loading the fermTree took about 200ms instead of the 700ms previous.

      postgres=# SELECT query, calls, total_time, rows, 100.0 * shared_blks_hit /
                   nullif(shared_blks_hit + shared_blks_read, 0) AS hit_percent
              FROM pg_stat_statements ORDER BY calls DESC LIMIT 15;
                                     query                                  | calls |    total_time    | rows |     hit_percent
      ------------------------------------------------------------------------+-------+------------------+------+----------------------
       PREPARE qpsqlpstmt_56 AS SELECT name from yeast WHERE id=$1            |  2508 | 12.9480000000002 | 2508 | 100.0000000000000000
       PREPARE qpsqlpstmt_53 AS SELECT name from misc WHERE id=$1             |  1768 | 42.6520000000005 | 1768 | 100.0000000000000000
       PREPARE qpsqlpstmt_4e AS SELECT name from hop WHERE id=$1              |  1751 | 11.0320000000002 | 1751 | 100.0000000000000000
       PREPARE qpsqlpstmt_3c AS SELECT name from style WHERE id=$1            |  1616 | 9.92499999999997 | 1616 | 100.0000000000000000
       PREPARE qpsqlpstmt_38 AS SELECT name from recipe WHERE id=$1           |  1268 |           21.141 | 1268 | 100.0000000000000000
       PREPARE qpsqlpstmt_48 AS SELECT display from fermentable WHERE id=$1   |  1228 | 7.94900000000004 | 1228 | 100.0000000000000000
       PREPARE qpsqlpstmt_4d AS SELECT display from hop WHERE id=$1           |  1032 | 6.64200000000001 | 1032 | 100.0000000000000000
       PREPARE qpsqlpstmt_68 AS SELECT amount from fermentable WHERE id=$1    |   998 | 6.65499999999991 |  998 | 100.0000000000000000
       PREPARE qpsqlpstmt_3e AS SELECT display from style WHERE id=$1         |   804 | 4.97299999999996 |  804 | 100.0000000000000000
       PREPARE qpsqlpstmt_47 AS SELECT folder from fermentable WHERE id=$1    |   764 | 5.02899999999997 |  764 | 100.0000000000000000
       PREPARE qpsqlpstmt_44 AS SELECT display from equipment WHERE id=$1     |   707 |           10.465 |  707 | 100.0000000000000000
       PREPARE qpsqlpstmt_49 AS SELECT name from fermentable WHERE id=$1      |   621 | 3.79999999999995 |  621 | 100.0000000000000000
       PREPARE qpsqlpstmt_4c AS SELECT folder from hop WHERE id=$1            |   516 | 3.52199999999998 |  516 | 100.0000000000000000
       PREPARE qpsqlpstmt_a5 AS SELECT amount_is_weight from misc WHERE id=$1 |   507 | 13.0299999999999 |  507 | 100.0000000000000000
       PREPARE qpsqlpstmt_3a AS SELECT date from recipe WHERE id=$1           |   473 | 8.31199999999999 |  473 | 100.0000000000000000
      (15 rows)

Notice I had to increase the limit to 15 to even find the fermentable name lookup? The call to fermentable name runs 621 times, exactly the number of fermentables I actually have. This seems very promising. 

## MOAR CACHES
Because if some is good, more is better and a massive s\*t ton is best (unless you are Conan the Barbarian)? Lets see what we get.

After a bunch of repetitive coding, I simply cached all the names.

### Results

The startup looked like:

      [22:12:59.921] INFO : Loading database.
      [22:13:00.169] INFO : Starting Brewtarget.
      [22:13:00.170] INFO : Initializing GUI.
      [22:13:00.198] INFO : setupUI -- initializing trees
      [22:13:00.199] INFO : setupUI -- initializing tabTree_recipe
      [22:13:00.393] INFO : setupUI -- initializing tabTree_style
      [22:13:00.494] INFO : setupUI -- initializing tabTree_equip
      [22:13:00.541] INFO : setupUI -- initializing tabTree_ferm
      [22:13:00.808] INFO : setupUI -- initializing tabTree_hops
      [22:13:00.994] INFO : setupUI -- initializing tabTree_misc
      [22:13:01.120] INFO : setupUI -- initializing tabTree_yeast
      [22:13:01.261] INFO : setupUI -- trees done
      [22:13:01.279] INFO : Initializing dialogs.
      [22:13:02.138] INFO : Initializing ranges.
      [22:13:02.139] INFO : Initializing comboboxes.
      [22:13:02.334] INFO : Initializing tables.
      [22:13:02.395] INFO : Initializing contextmenus.
      [22:13:02.396] INFO : Initializing geometries.
      [22:13:02.767] INFO : Initializing signals.
      [22:13:02.938] INFO : Initializing finished.

3 seconds to load, and the trees barely take a second. 

      postgres=# SELECT query, calls, total_time, rows, 100.0 * shared_blks_hit /
                   nullif(shared_blks_hit + shared_blks_read, 0) AS hit_percent
              FROM pg_stat_statements ORDER BY calls DESC LIMIT 10;
                                    query                                 | calls |    total_time    | rows |     hit_percent
      ----------------------------------------------------------------------+-------+------------------+------+----------------------
       PREPARE qpsqlpstmt_48 AS SELECT display from fermentable WHERE id=$1 |  1228 | 8.06800000000001 | 1228 | 100.0000000000000000
       PREPARE qpsqlpstmt_4d AS SELECT display from hop WHERE id=$1         |  1032 | 6.96300000000001 | 1032 | 100.0000000000000000
       PREPARE qpsqlpstmt_68 AS SELECT amount from fermentable WHERE id=$1  |  1022 |  7.1619999999999 | 1022 | 100.0000000000000000
       PREPARE qpsqlpstmt_3e AS SELECT display from style WHERE id=$1       |   804 | 5.16099999999997 |  804 | 100.0000000000000000
       PREPARE qpsqlpstmt_47 AS SELECT folder from fermentable WHERE id=$1  |   764 | 5.31499999999998 |  764 | 100.0000000000000000
       PREPARE qpsqlpstmt_44 AS SELECT display from equipment WHERE id=$1   |   707 |           10.745 |  707 | 100.0000000000000000
       PREPARE qpsqlpstmt_3a AS SELECT date from recipe WHERE id=$1         |   653 |           12.579 |  653 | 100.0000000000000000
       PREPARE qpsqlpstmt_49 AS SELECT name from fermentable WHERE id=$1    |   621 | 3.99199999999994 |  621 | 100.0000000000000000
       PREPARE qpsqlpstmt_4e AS SELECT name from hop WHERE id=$1            |   516 | 3.39399999999997 |  516 | 100.0000000000000000
       PREPARE qpsqlpstmt_4c AS SELECT folder from hop WHERE id=$1          |   516 | 3.56699999999997 |  516 | 100.0000000000000000

I've got this pretty tight. I could do the same with the display variable, but I am reaching the point of diminishing returns. Although the display variable suggests a better approach.

## BeerXMLElement caches?
display and deleted are actually defined on the parent objectclass BeerXMLElement. I have actually struggled a lot with the fact that the name isn't.

What if I move name into BeerXMLElement, and did all this silliness in just one place?

Before I go down that rabbit hole, let me take a quick second or three to cache display, delete and folder. Since this is all in the BeerXMLElement class, it is just as easy for me to hit all three as it isn't.

### Results
Startup:

      [22:23:36.410] INFO : Loading database.
      [22:23:36.670] INFO : Starting Brewtarget.
      [22:23:36.671] INFO : Initializing GUI.
      [22:23:36.701] INFO : setupUI -- initializing trees
      [22:23:36.702] INFO : setupUI -- initializing tabTree_recipe
      [22:23:36.899] INFO : setupUI -- initializing tabTree_style
      [22:23:37.002] INFO : setupUI -- initializing tabTree_equip
      [22:23:37.049] INFO : setupUI -- initializing tabTree_ferm
      [22:23:37.300] INFO : setupUI -- initializing tabTree_hops
      [22:23:37.507] INFO : setupUI -- initializing tabTree_misc
      [22:23:37.616] INFO : setupUI -- initializing tabTree_yeast
      [22:23:37.735] INFO : setupUI -- trees done
      [22:23:37.753] INFO : Initializing dialogs.
      [22:23:38.110] INFO : Initializing ranges.
      [22:23:38.111] INFO : Initializing comboboxes.
      [22:23:38.164] INFO : Initializing tables.
      [22:23:38.250] INFO : Initializing contextmenus.
      [22:23:38.250] INFO : Initializing geometries.
      [22:23:38.547] INFO : Initializing signals.
      [22:23:38.659] INFO : Initializing finished.

2 seconds? This is now snapping fast with the external database. Notice also I
shaved a good 0.5 seconds off initializing the dialogs.

      postgres=# SELECT query, calls, total_time, rows, 100.0 * shared_blks_hit /
                   nullif(shared_blks_hit + shared_blks_read, 0) AS hit_percent
              FROM pg_stat_statements ORDER BY calls DESC LIMIT 10;
                                       query                                  | calls |    total_time    | rows |     hit_percent
      ------------------------------------------------------------------------+-------+------------------+------+----------------------
       PREPARE qpsqlpstmt_68 AS SELECT amount from fermentable WHERE id=$1    |   982 | 6.74899999999992 |  982 | 100.0000000000000000
       PREPARE qpsqlpstmt_47 AS SELECT folder from fermentable WHERE id=$1    |   621 | 4.35899999999997 |  621 | 100.0000000000000000
       PREPARE qpsqlpstmt_49 AS SELECT name from fermentable WHERE id=$1      |   621 | 3.22599999999999 |  621 | 100.0000000000000000
       PREPARE qpsqlpstmt_48 AS SELECT display from fermentable WHERE id=$1   |   621 | 4.06999999999995 |  621 | 100.0000000000000000
       PREPARE qpsqlpstmt_4c AS SELECT folder from hop WHERE id=$1            |   516 | 3.45699999999997 |  516 | 100.0000000000000000
       PREPARE qpsqlpstmt_4d AS SELECT display from hop WHERE id=$1           |   516 | 3.63799999999997 |  516 | 100.0000000000000000
       PREPARE qpsqlpstmt_4e AS SELECT name from hop WHERE id=$1              |   516 | 2.56299999999999 |  516 | 100.0000000000000000
       PREPARE qpsqlpstmt_a5 AS SELECT amount_is_weight from misc WHERE id=$1 |   507 | 12.7939999999999 |  507 | 100.0000000000000000
       PREPARE qpsqlpstmt_4a AS SELECT ftype from fermentable WHERE id=$1     |   397 |            3.124 |  397 | 100.0000000000000000
       PREPARE qpsqlpstmt_3a AS SELECT date from recipe WHERE id=$1           |   383 | 7.00699999999998 |  383 | 100.0000000000000000

Yeah. That makes me happy. Happy enough I am not sure I need to go any further. I think 2 seconds is a very respectable load time.

## How Many Again?
I still haven't addressed one of the fundamental questions. Even after my tweeks, postgresql says

      postgres=# select sum(calls) from pg_stat_statements;
      sum
      -------
       14706
      (1 row)

We should consider addressing this.

### Caches
We could cache every attribute. The method I used for name, display and deleted could easily be extended to every attribute. 

I do not like this idea. As the man said, there are two types of errors in programming: logic errors, caching problems and off-by-one errors.

### Get a rectangle instead
Right now, we basically get every column for every row. This means the number of queries we run is row*column for each table we build. This includes the trees, since they are really just weirdly drawn tables.

What if we figured a clever way to get the rectangle instead? Throw in some fun joins like:

     SELECT f.name, f.type, f.amount 
       FROM fermentable f, fermentable_in_recipe fir 
       WHERE fir.recipe_id = 1 and f.id = fir.fermentable_id;

and now we get an entire table of data to display with just one easy query.

If I could figure out how to implement this ( temporary tables and a QSqlTableModel?), I think we could really do something interesting. But it would require we completely rethink how we model the data, and I am just not quite up for it.

# And what about SQLite?

    [22:47:44.904] INFO : Loading database.
    [22:47:44.957] INFO : Starting Brewtarget.
    [22:47:44.958] INFO : Initializing GUI.
    [22:47:44.984] INFO : setupUI -- initializing trees
    [22:47:44.984] INFO : setupUI -- initializing tabTree_recipe
    [22:47:45.013] INFO : setupUI -- initializing tabTree_style
    [22:47:45.022] INFO : setupUI -- initializing tabTree_equip
    [22:47:45.026] INFO : setupUI -- initializing tabTree_ferm
    [22:47:45.040] INFO : setupUI -- initializing tabTree_hops
    [22:47:45.052] INFO : setupUI -- initializing tabTree_misc
    [22:47:45.059] INFO : setupUI -- initializing tabTree_yeast
    [22:47:45.070] INFO : setupUI -- trees done
    [22:47:45.086] INFO : Initializing dialogs.
    [22:47:45.171] INFO : Initializing ranges.
    [22:47:45.171] INFO : Initializing comboboxes.
    [22:47:45.187] INFO : Initializing tables.
    [22:47:45.271] INFO : Initializing contextmenus.
    [22:47:45.271] INFO : Initializing geometries.
    [22:47:45.273] INFO : Initializing signals.
    [22:47:45.280] INFO : Initializing finished.


To quote the man, forget about it. My quick maths say my tweaks get the load time to 0.4 seconds or so. 

# Conclusion
If you've read this far, I'm impressed. What I am trying to do is some performance tuning. Slow systems drive me nuts. With a bit of database sleuthing, I've been able to crank the startup time using postgresql from 15 seconds to 2 seconds and the sqlite database just screams.

We need to make some minor changes to the code, and I need to clean up what I've got. I would argue this should go into the 2.4 release.

**Comment by rocketman768** [comment]
Nice job profiling the database! You found the biggest bottlenecks and cached them away. I think you are right not to cache all the things, because at some point you just go back to the in-memory model we started with.

One note: you made `setName()` non-`const` because now you are modifying `_name`. If you really really like const-correctness (like me), this is why the `mutable` keyword exists: to let the class know that `_name` is not _really_ like the other class members.

As for 2.4.0 vs. later, your call.

**Comment by mikfire** [comment]
I am going against 2.4.0. I also followed your suggestion about the mutables.

**Comment by lvincent81** [comment]
I've been lurking watching this, very good write up!

**Comment by mikfire** [comment]
Closed with mr #310
