### ISSUE TITLE
Number of decimals for the color in the fermentable editor

### ISSUE THREAD

**Issue by mordante** [Brewtarget/brewtarget#314]
When I open a record in the fermentable editor the color field initially has 3 decimals. For example the Candi Sugar, Amber has an initial value of "147.638 ebc". When I edit the field the new value is rounded to a integer value. When I look at the code the 0 decimals seems to be intended. But this was done in a rather large commit. So I'm not sure what should change: the number of decimal positions incremented, or the number of decimal positions initially displayed decremented.

I noticed the issue when I tried to enter a malt of Dingemans[1], they give their EBC range with one decimal position. (Seems always be a value of x or x.5.)

[1] http://www.dingemansmout.be/products/kilned-malts

**Comment by mikfire** [comment]
That would most likely be a mistake in the FermentableEditor::showChanges(). The default for setText() is a precision of 3 and I see that the editor doesn't specify the precision when it initially loads the value.

When you edit the field, though, the precision is supplied and is 0, so we simply round to the nearest integer value.

The best fix would be to change the showChanges() method to use a precision of 0.

I will put this into the next release, assuming I can ever get 2.4.0 out the door.
