### ISSUE TITLE
Initialising a new database

### ISSUE THREAD

**Issue by mordante** [Brewtarget/brewtarget#319]
I ran into an issue while creating a new database with a new user account. The problem is the application does not start when creating a new database, with a SQL error. I've seen the issue before but it is rather elusive to reproduce. It seems to have to do with SQL escaping. I think I have a solution, but since reproducing the issue is hard, it's hard to validate the fix. I expect to have a proper pull request next weekend. (If I fail to find a proper fix I'll give more details on the bug.)

I consider this issue a blocker for 2.4.0, but it does not affect translatable strings.

**Comment by mikfire** [comment]
The two referenced pull requests have been merged. Can this issue be closed?

**Comment by mordante** [comment]
Yes I can't recall other issues, else I'll file a new bug report or pull request.
