### ISSUE TITLE
[RFC] Recipe versioning

### ISSUE THREAD

**Issue by mikfire** [Brewtarget/brewtarget#327]
# An illustrated guide
Well. There won't be any pictures, but I will try to describe how they work and why.

I have almost completely implemented this feature. I am writing this RFC to make certain I haven't missed something obvious featurewise and to make sure some of my design decisions are acceptable. This will also provide a good record later for just why I screwed this up.

## Background
The very simple idea is to somehow provide a history of a recipe as you change it. I am particularly interested in being able to track a recipe through the various brewdays.

The idea is that if you have already brewed a recipe, any modification to the recipe would make a copy and any modifications are made to the copy -- in other words, copy on write. This will only happen on the first change to a brewed recipe. After the initial copy is made, you can make as many changes as you want and no further copies will be made until you brew the recipe again.

With the addition of folders somewhere around v2.1, how to represent it became pretty obvious. The HEAD of a recipe would appear in the tree, and the previous versions would be displayed underneath it, as if the HEAD were a folder.

The main question was what defines a "write" and when do we want to make the copy. If we literally copied on every write, the database would soon be littered with copies -- remember that we set og/fg on every load of the recipe. 

# Design Choices
There are any number of design choices that have to be made when doing something like this.

## Ancestors or Descendants?
I played with this for a bit and decided that a given recipe should know its nearest ancestor instead of knowing its nearest descendant. A root node will only know of itself. Every ancestor will have a display of false, with only the HEAD node having a display of true.

This had a few really easy wins for me. The BtTreeSortFilterProxy algorithm already shows only those recipes with display set to true. This allowed me to create a version and do nothing more to get the display behaving. It did mean I had to figure out some clever ways to override the display when I wanted.

This also introduces some basic terminology. I started thinking this in terms of fork, HEAD, etc. but somewhere transitioned to thinking in terms of ancestors and descendants. I will still sometimes discuss HEAD or leaf recipe, but I will mostly discuss things in terms of descendants and ancestors.

## Branches?
I am pretty much declaring there will be no branches. Branches imply merges and I do not feel smart enough to handle that sort of nonsense. I may work out some printable diff, though.

This has some consequences:
- Once a recipe is forked, the ancestor recipe becomes readonly;
- You cannot delete an ancestor, without first deleting all of its descendants;
- you will need to orphan each descendant if you want to reorder the relationship;
- you can only really operate on the HEAD recipe

## What "write" means.
Anything that changes the recipe after it has been brewed should fork the recipe. But what constitutes a "change"? For example, if I change the assistant brewer on the Extras tab should that fork the recipe?

I have basically come to this rule set:
   1. If a change is made to a Recipe object, the recipe does not fork;
   2. If a change is made to an Instruction object, the recipe does not fork;
   3. If a change is made to a Mash object, the recipe does not fork;
   4. If a change is made to a BrewNote object, the recipe does not fork;
   5. If a change is made to the first mash step that only changes the infusion
      temperature, the recipe does not fork;
   6. All other changes fork the recipe.

I am very conflicted about the instructions. I can make an argument for forking the recipe if a step is added, removed or moved -- it is an important change to the recipe, and people would want that history as well. I can also make an argument that says modifying the instructions doesn't change the recipe, only the process and it shouldn't fork. Right now, I am saying modifying the instructions won't fork.

The fifth rule is a bit weird. The problem is that users are supposed to be recalculating the mash each time they brew in order to adjust the starting temperature. Doing that would adjust the starting temperature, but not the target temp of the initial infusion. This should not fork a recipe. Any other change to a mash -- adding more steps, changing the volumes in a step,changing the target temperature, etc. -- should.

## Manual Controls
Another important series of considerations were just what manual controls would be allowed. This is important particularly when considering the first time this feature is exposed, it would be nice to allow people to say "this recipe is an ancestor of that" and have the right thing happen.

### Defining ancestors
The user will be able to manually mark a recipe as an ancestor of another, by simply dragging the ancestor to the descendant.

This causes a hard problem. To move a recipe into another folder, you simple drag the recipe and drop it anywhere in the other folder -- on the folder icon, on another recipe, etc. If I implement this feature as I want, there is a conflict. Dropping recipe A on recipe B will mean "make A an ancestor of B", where as right now it means "put A into the same folder as B".

My choice here is that if you drop recipe A on recipe B in the same folder, we make recipe A an ancestor of recipe B. If they are in different folder, we just move the dropped recipe into the new folder. I am concerned this may be a bit confusing, but I can't think of a better
idea.

### Spawning
Users will be able to manually spawn a recipe. This will override the usual checks and will be done even if the ancestor didn't get brewed.

### Orphaning a recipe
Users will also be able to remove the HEAD recipe from its ancestral chain. This will basically pop the HEAD recipe off, and make the nearest ancestor the new HEAD.
 
### Locking
Users will be able to hard lock the recipe. If I am going to make ancestors read only, that ability should be exposed to the users.

If a recipe is locked, it means no changes will be permitted to the recipe except brewnotes. This actually makes other aspects of the code easier -- when a recipe is locked, it just sets the lock flag and the same code that prevents an ancestor from being modified works.

### Disabling the versions
The final user control is that the option dialog allows the user to turn the versioning on or off. It was suggested by some people that they would not like the versioning happening automatically. By default, we will version. The value of this option will not impact the ability of the user to either manually lock or version a recipe.

## Locking Recipes
I had considered simply overloading the display variable to control if the recipe is locked; display == false would imply the recipe is locked.

If I want the users to be able to hard lock a recipe, setting display to false will make the recipe disappear from the tree. Mucking with the sort/filter/proxy simply isn't easy. And there may well come a time when we need to distinguish between the two states. Therefore, I will need a another column on the recipe table.

You should be able to unlock a leaf recipe, but you cannot unlock an ancestor (remember, no branches). I will need to make sure I can lock and unlock the lock flag.

## Deleting Recipes
This is a hard one. Assuming that ancestral recipes are locked and cannot be deleted, what happens when the descendant is deleted? Do we delete the entire history, or do we just delete the descendant and make the most recent ancestor active again?

The default behavior will be to only delete the HEAD recipe. The behavior can be changed via the options screen to delete the entire chain. There is no per-recipe prompt, as I would have wanted. There is just no sane way I could see to do that.

## Showing and hiding ancestors
The default option will be to show only the HEAD recipe. A right-click menu will allow you to show and hide the ancestors.

When just the HEAD recipe is shown, all of the brewnotes for every version will be displayed beneath the HEAD. When the full history is shown, the brewnotes will be shown with the correct version of the recipe.

Each recipe will be displayed with its version number. For example, if I have four versions of a recipe called "MyIpa", I would see the head displayed as "MyIpa[v4]".

## Open design questions
1. Am I right about what "write" means?
2. I really do not like the drag/drop thing. I cannot see a different way to do it that doesn't become modal.
3. I fear what this feature will do to the inventory magics.

**Comment by mikfire** [comment]
I think I may already have branching.

Assume recipe A begat recipe B begat recipe C. I make a copy of recipe C called recipe C'. Recipe C and C' share the ancestor, recipe B. I modify recipe C' but leave recipe C alone.

In other words, I branched. Bugger. I am also restraining myself from drawing things that look a lot like git diagrams.

**Comment by mikfire** [comment]
A few notes. I just pushed redux/rversion. Use that branch for any testing please. The skunks/rversion had something really weird happen to its history, and it looks like several commits got added twice. redux/rversion is clean.

There is an odd problem with the brewnotes. Currently, the default behaviour is that the leaf node displays its own brewnotes and the brewnotes of all its ancestors. If you double click on the brewnote, it loads the ancestoral recipe into the main panel. It raises an interesting question of what should that behavior be. I find it rather surprising, so I think I should fix it.

**Comment by mordante** [comment]
As already mentioned on IRC I played a bit with the branch and ran into some oddities/bugs
*  Right click Recipes item in the treeview results in a crash
* When a record is locked the fermentable dialogue still has an add button active. (Pressing it does nothing as wanted.)
* Does the brewday need to be locked?
* The extras fields of a locked record can be modified and some parts are saved.

I'm also not too fond of the dropping resulting in inheritance. I'm not sure what the best solution is.

I'm also not sure what the best default for the 'disabling versioning' option should be. Maybe to keep things simple for new users it should be disabled. (I still think we can enable it by default and make the final decision closer to the 2.5 release.) 

In general I really like this feature, but it is hard to answer some of the open questions, I think getting it in develop and use it might be the best way to tune things.

**Comment by mikfire** [comment]
The drag/drop problem was hard. If you notice the logs, I didn't much like my solution either. The only other thing I could come up with was some kind of dialog that specifically said "Make [drop down box] an ancestor of [drop down box]". I will try harder.

No. Brewnotes are not to be locked. The intent is a locked recipe cannot be changed, but it can be brewed again. The extras also were intended to not be locked. For example, the assistant brewer may change from brewday to brewday, but it really doesn't impact the recipe itself.

I will look into issues and see what I can see.

**Comment by mikfire** [comment]
Ok. Most recent version does a few things. 

I have set the versioning to off by default. This does not prevent people from locking recipes, setting up ancestors or versioning recipes themselves. It simply prevents it from happening automatically unless requested.

The other thing was to stop the drag/drop for defining an ancestor. There is now a tool for doing that. I think it actually works better -- it at least works in a way I understand. Sorry for the "begat", but it makes me laugh so I used it.

**Comment by mordante** [comment]
Thanks for the changes.

I played a bit with the new changes, and some remarks:

I can no longer drag a recipe to a folder. Is this intentional?

The ancestor dialogue seems to work, the dialogue needs a bit more love an should not be able to maximize.

In general I like the begetting, but have a minor feature request:
If I select Bt: Saison, begat, Bt: Saison – Extract
I get a 'Bt: Saison – Extract [v2]' in a bold font
Would it be possible to directly activate the 'Show Ancestors' for 'Bt: Saison – Extract [v2]'? Then the listbox directly shows there is an ancestor. Now when using the begat feature I feel I lost my original recipe. (Of course I didn't lose the recipe, it's just hidden.)

**Comment by mikfire** [comment]
I did not intend on breaking drag/drop of the recipes. I will see
what I broke.


Yes. The dialog needs a lot of work. :)



I had played with an idea of automatically showing ancestors, mostly to
allow the user to say "Always show ancestors" as an option. It turned
out to be harder than I had expected. I am trying to do this, and want
to. I think I have an idea that will work without a lot of changes, so
let me see what I can do.


Mik



--

  Mik Firestone

  mikfire@fastmail.com







On Sun, Dec 18, 2016, at 09:05, mordante wrote:

> Thanks for the changes.



> I played a bit with the new changes, and some remarks:



> I can no longer drag a recipe to a folder. Is this intentional?



> The ancestor dialogue seems to work, the dialogue needs a bit more
> love an should not be able to maximize.
> In general I like the begetting, but have a minor feature request:

>  If I select Bt: Saison, begat, Bt: Saison – Extract

>  I get a 'Bt: Saison – Extract [v2]' in a bold font

>  Would it be possible to directly activate the 'Show Ancestors' for
>  'Bt: Saison – Extract [v2]'? Then the listbox directly shows there is
>  an ancestor. Now when using the begat feature I feel I lost my
>  original recipe. (Of course I didn't lose the recipe, it's just
>  hidden.)
> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].
> 




Links:

  1. https://github.com/Brewtarget/brewtarget/issues/327#issuecomment-267823010

**Comment by cgiacofei** [comment]
I like the idea of this so far, I think it would be nice to be able to see ancestors by default as you mentioned above. One thing I've found is that the program crashes when I try to delete a recipe.

`
ASSERT failure in QList<T>::at: "index out of range", file /usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h, line 531
[1]    7290 abort (core dumped)  /usr/local/bin/brewtarget
`

I am able to delete all of the descendants of a recipe without issue but run into the error when deleting the top-most recipe.

This is on a linux machine running Ubuntu.

**Comment by pricelessbrewing** [comment]
Can't say I followed all of this very well. Would this be in addition to, or in place of, the "brew it" brew sessions function?

My comments would be to remove any automatic creating of child (descendant) recipes and have it behave like the brew it function. 

hvae folders of recipes, where you can have version history, but no branches. If you make a branch, you're turning one of the versions into a new head/master/parent recipe. 

So basically

>saisons

>>My Rye Saison (master)
>>>Version 1.01
>>>Version 1.02

Next version is a branch, so it should be a new parent.
>>Rye saison Version 2,
>>>Version 2.01
>>>Version 2.02 

>Belgian Table beers 


ETc etc. 

Brew it sessions should then be moved only to tabs at the top of the 

So the existing folders of different brew sessions get removed from the recipe directory window and will only be shown next to extras and brewday, with "brewday 1" set to show by default, and change tab names (dates) to be editable, or to simply be numbered in sequence as brewday 1, brewday 2 etc. and have date as a user input field.

**Comment by matty0ung** [comment]
I don't know what current status of this is, but I rather agree with @pricelessbrewing about branches - ie keeping to a simple principle that if you want one recipe to evolve into two new ones, then only one of those two ones retains the history, and the other just becomes a brand new recipe.   I would be inclined to present versioning to the user in somewhat the same way as versioning of wiki pages is presented.

**Comment by mattiasmaahl** [comment]
This is resolved in #586, closing
