### ISSUE TITLE
Hydrometer 60F calibration

### ISSUE THREAD

**Issue by Esslingers** [Brewtarget/brewtarget#330]
My hydrometer is calibrated for 60F instead of the 20C/68F. It would be nice if I was able to set this as an option so my AVB, OG, and FG worked out without having to use a separate calculator

**Comment by jawsdaws** [comment]
Just added a pull request with a fix for this.

**Comment by jawsdaws** [comment]
There is a fix merged now.  This can be closed.

**Comment by pricelessbrewing** [comment]
Closed, hydrometer calibration temp is variable in the "OG correction help" tool.
