### ISSUE TITLE
Fetaure proposal: Duplicate button in inventory

### ISSUE THREAD

**Issue by tpiszcze** [Brewtarget/brewtarget#332]
What do you think about "duplicate" button in inventory window? It would be handy when you have eg. new supply of hops you already have but with different parameters. For some time there would be two ingredients with the same name in the database but when you run out of old hops it could be deleted.

**Comment by pricelessbrewing** [comment]
I'm not sure I understand, any ingredient can be copy and pasted via right clicking to produce a duplicate. You can then change the name, and properties as desired.

**Comment by tpiszcze** [comment]
Right. I did not try it before. It works exactly as the feature I proposed.
