### ISSUE TITLE
Unable to build on Linux Mint 18.1

### ISSUE THREAD

**Issue by begin-again** [Brewtarget/brewtarget#337]
I installed the dependencies listed [here](https://github.com/Brewtarget/brewtarget/tree/stable/2.4.0). 

-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:318 (QT5_WRAP_UI):
  Unknown CMake command "QT5_WRAP_UI".

CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

  cmake_minimum_required(VERSION 3.5)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!

**Comment by mikfire** [comment]
Can you tell me which version of Qt5 and cmake are you using? And what version of brewtarget are you trying to build?

**Comment by mikfire** [comment]
I spun a Mint 18.1 Mate vm and followed the directions. There are a few discrepancies: it should be libqt5svg5-dev, we don't depend on the webkit any more and we should likely mention wanting libqt5sql-psql. I will fix these.

However, I don't think those are causing your problem. My guess is that you are referencing the wrong directory on the cmake command. Instead of saying "cmake ~/brewtarget/src", say "cmake ~/brewtarget" -- in other words, reference the top directory of the project instead of the src subdirectory. If I stop knowing how it works, and just read the directions, I can see the confusion.

My usual process is:
1. git clone https://github.com/Brewtarget/brewtarget.git
2. cd brewtarget
3. mkdir build
4. cd build
5. cmake ..
6. make

**Comment by begin-again** [comment]
I installed libqt5svg5-dev, but didn't find libqt5sql-psql. I'm using cmake 3.5.1 trying to build brewtarget 2.4 stable. I'm on Mint 18.1 Cinnamon.  Here is what I get  when i issue the cmake command from within a build sub folder with this command: cmake ..

CMake Error: The source "brewtarget-240/CMakeLists.txt" does not match the source "brewtarget-240/src/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.

So i specify the path to the source (cmake ../src) and get the QT5_WRAP_UI error:

CMake Error at CMakeLists.txt:318 (QT5_WRAP_UI):
  Unknown CMake command "QT5_WRAP_UI".

**Comment by mikfire** [comment]
Ugh. The proper name of the postgresql package is libqt5sql5-psql. I always forget the extra 5. Sorry for that. There's a POSTGRES.markdown in the dev-doc directory that will give some minor help in setting up the postgresql database if you want, including the proper package names.

You will need to clean the build directory out before running cmake with a new path. Either rm -rf the directory and then mkdir it again or cd into the directory and rm -rf *. Once the build directory is empty, run:

     cmake ..

If you have problems, keep going in this thread or try catching me in #brewtarget on freenode

**Comment by begin-again** [comment]
Installing libqt5sql5-psql did the trick. Thanks for your assistance.

**Comment by dpettersson** [comment]
Maybe we should close this issue as it looks like it is resolved
