### ISSUE TITLE
Trying to delete "brewtarget" folder in the Recipes list causes segfault

### ISSUE THREAD

**Issue by eltomek** [Brewtarget/brewtarget#338]
Found on 2.4.0
Removing folders causes a segfault (and sometimes db corruption). 
When investigating the reproduction scenario I identified that the Del keypress events always refer to last selected _Recipe_ and not the item that was selected afterwards:
1. select a _Recipes_ tab in the `BtTreeView`
2. double-click on any recipe to edit it
3. select some fermentable row on the recipe and hit Del button
4. a confirmation dialog is shown. Because the `deleteSelected` action is tied to the recipe item in the `BtTreeView` no matter what other element in any other view you select and as a result it is the recipe entry on the `BtTreeView` that is about to be deleted, not the fermentable one
5. Choose "No" on the dialog. When you hit "No" the cursor in the `BtTreeView` is moved back to the 1st element on that view which happens to be a "brewtarget" folder
6. If you select the fermentable again (step 3) the Del button will trigger the "brewtarget" folder deletion action that will eventually result with a sigsegv.

**Comment by eltomek** [comment]
This is a bit more general problem, as a user I'd expect Del button to be supported for rows in other Views, like e.g in `fermentableTable` or `hopTable` but instead the `treeView_recipe` or `treeView_style` is handled (even though user clicked on other elements, like rows). There are some more strange behaviors, but I'll submit separate issues for these.

**Comment by mikfire** [comment]
Hmm. That is not how brewtarget has historically worked. That isn't an argument, merely an observation. If there's a coherent way to make that work, I'm willing to discuss.

Whatever we come up with would have to handle something like: I have a recipe selected in the tree, and a fermentable selected in the ingredient pane and the mouse isn't focused in either. When you press the Del key, what do expect to have deleted? And would it be reasonable to expect others to expect the same thing?

**Comment by eltomek** [comment]
Personally, I'd expect the last consciously selected item (on any widget) to be the subject of the deletion upon Del keypress. The mouse position and the object it is at shall be disregarded as it can point accidentaly to anything on the screen and until the user deliberately clicks on some object nothing shall be actually selected. In other words, if I clicked on the BtTreeView item and then clicked on other entries like in TableView or so the last thing I expect is that it is the last but one items that I clicked to be deleted :)

**Comment by mikfire** [comment]
One of the hardest things in programming like this is to realize when the other person is right. You are right. I hate the way deleting works.

See if the referenced commit makes sense to you. If not, lets talk and see what I'm missing.

**Comment by eltomek** [comment]
With your commit  https://github.com/mikfire/brewtarget/commit/0908b5516f4d7a8a92b4cc3de3e0c93b4c9142d0 deleting works just as I'd expect as a user and I think it greatly improves the overall BT app experience. Thank you for that!
The original issue though is about crashing upon deleting a folder and I just checked that it crashes on deleting **any** folder, not just the _brewtarget_ one. I will redefine the original issue description.
As you're rewiring signals around `*Table`s it may possibly be convenient for you to cover for issue #341

**Comment by mikfire** [comment]
I am doing some signal rewiring, but I will handle issue #341 in a different commit. 

I need to redo this slightly to use the new signal/slot connections, and then will submit the merge request.

**Comment by pricelessbrewing** [comment]
I'm still crashing when trying to delete the brewtarget folder of recipes.

**Comment by xzfantom** [comment]
This bug still exists, at least in windows build. Think, should add it to milestone or project to fix before 2.4.0 release
