### ISSUE TITLE
BtTreeView selected items take precendence over locally selected entities

### ISSUE THREAD

**Issue by eltomek** [Brewtarget/brewtarget#340]
Found on 2.4.0
I had some problems trying to figure out the headline, here are the steps:
1. open some recipe to be edited and switch to `Recipe` tab of the main window
2. in the left hand-side `BtTreeView` tree select the Equipment tab and double-click some entry that is different to the equipment selected in the Equipment field of the recipe
3. an Equipment edit dialog will pop up, press Cancel
4. click on the currently selected Equipment button of the recipe to open the Equipment edit dialog (**issue** is that the Equipment edit dialog now calls for the one that you double-clicked in the  `BtTreeView`, not the one that you had picked for your recipe. The same works for style.

**Comment by pricelessbrewing** [comment]
Confirmed still an issue.
