### ISSUE TITLE
Removing ingredient from the recipe does not update calculated beer parameters

### ISSUE THREAD

**Issue by eltomek** [Brewtarget/brewtarget#341]
The easiest scenario on hop example (the same works for any ingredient that impacts beer parameter calculations):
1. add some hop item to the recipe, it will get added with 0,0 mass amount
2. change the amount to e.g 100g and see the IBU changed on the recipe details
3. remove the hop you just added and observe **that the IBU did not change (issue)**.

There are 2 actions that update the beer recipe calculations:
1. changing the parameters of any ingredient entry in the recipe (on the hop example you can change the _Amount_ or _Use_ values). So if you remove the hop entry the IBU will not change, but if you just update any other ingredient on the recipe the calculations will update
2. dragging and dripping new ingredient from the let hand side `BtTreeView`.

**Comment by jawsdaws** [comment]
Removing fermentables and removing yeast also have the same problem.  I think I have a fix.  I need to do more testing...

**Comment by jawsdaws** [comment]
This appears to be a bug in 2.4.0 and not in 2.3.0
