### ISSUE TITLE
Mash Profile deletion causes fatal error

### ISSUE THREAD

**Issue by begin-again** [Brewtarget/brewtarget#342]
Version: 2.40
Compiled from Source on Linux Mint 18.1
DB: SQLite

I noticed that I had several mash profiles all with the same name. Thus I attempted to delete those which were not needed. This error occurred on the first attempt. I tried on another profile but that resulted in same error.

![brewtarget-error](https://cloud.githubusercontent.com/assets/11179873/22176256/18a75fa8-dfd4-11e6-8da0-83afc4a28f72.png)

**Comment by eltomek** [comment]
Fixed by https://github.com/Brewtarget/brewtarget/pull/349

**Comment by begin-again** [comment]
Is this fix going to be added to the 2.4 branch?

**Comment by eltomek** [comment]
@mikfire could you please review and merge/reject https://github.com/Brewtarget/brewtarget/pull/349 ?

**Comment by mikfire** [comment]
Sorry. Had to attend a funeral. It's slowed me down a bit. I'm home, but
I still need a few days to relax. Once I'm a little more recovered, I'll
review and commit.


Mik



--

  Mik Firestone

  mikfire@fastmail.com







On Sat, Feb 11, 2017, at 12:40, Tomek Lorek wrote:

> @mikfire[1] could you please review and merge/reject #349[2] ?



> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[3], or mute the thread[4].
> 


Links:

  1. https://github.com/mikfire
  2. https://github.com/Brewtarget/brewtarget/pull/349
  3. https://github.com/Brewtarget/brewtarget/issues/342#issuecomment-279162448
