### ISSUE TITLE
Color of the malt as displayed in the treeView_ferm is expressed in SRM regardless of unit settings

### ISSUE THREAD

**Issue by eltomek** [Brewtarget/brewtarget#345]
Seen in 2.4.0

![image](https://cloud.githubusercontent.com/assets/3283040/22350959/12afee58-e416-11e6-8470-06b72ca1d341.png)

**Comment by pricelessbrewing** [comment]
Confirmed still an issue.  

Additionally, changes in the fermentables table (circled in bottom right in OPs image) does not update when the unit options are changed and the options window is closed, you have to click something.

**Comment by dpettersson** [comment]
I have located the line that needs to be changed, but i am having trouble finding a good way to determine the current unit. It can be found in QVariant BtTreeItem::dataFermentable(int column)

A working solution is 
 //default to SRM
double currentColor = ferm->color_srm();

if (Brewtarget::getColorUnit() == Unit::displayEbc)
{
    EBCUnit u;
    currentColor = u.fromSI(currentColor);
}
return QVariant(currentColor);

but it relies on information from the brewtarget class. There must be a  better way.
