### ISSUE TITLE
Newly created folders are not stored in the db

### ISSUE THREAD

**Issue by eltomek** [Brewtarget/brewtarget#346]
Seen in 2.4.0
Steps to reproduce:
1. Right click on any item in `treeView_ferm` and choose `New->Folder`
2. Enter folder name and hit Enter, see the newly added folder in the `treeView_ferm`
3. Gracefully close the Brewtarget and run it again
4. There is no folder created in step 2.

I noticed that in order to activate the context menu you need to right-click on list item, it is not invoked upon right-clickig the empty area, in that case we could have the minimum context menu with just `New >` option available.

**Comment by mikfire** [comment]
Yes. That is working as designed. Or, at least, it is a known limitation
with the implementation. I would have to completely reimplement the
folders to fix this.


Mi



--

  Mik Firestone

  mikfire@fastmail.com







On Thu, Jan 26, 2017, at 16:35, Tomek Lorek wrote:

> Seen in 2.4.0

>  Steps to reproduce:


>  1. Right click on any item in treeView_ferm and choose New->Folder
>  2. Enter folder name and hit Enter, see the newly added folder in the
>     treeView_ferm
>  3. Gracefully close the Brewtarget and run it again
>  4. There is no folder created in step 2.
> I noticed that in order to activate the context menu you need to right-
> click on list item, it is not invoked upon right-clickig the empty
> area, in that case we could have the minimum context menu with just
> New > option available.
> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].
> 


Links:

  1. https://github.com/Brewtarget/brewtarget/issues/346

**Comment by eltomek** [comment]
I understand not saving an empty folder, but if I add a recipe to a newly created folder it gets stored in the top-level "folder" and the newly created folder is not there, so effectively there is no folder support.  In that case how about removing references to folder maintenance in the UI so the users are not concerned?

**Comment by mikfire** [comment]
I am sorry. I may have misunderstood something.



The way I understood your original bug was that empty folders are not
preserved over a restart, which is a known limitation. There was no
mention of moving something into the folder.


The way I understand your second comment is that no new folders
are being created, even if they are populated. That is a very
different problem.


I am now slightly confused. Is this about not saving empty folders, or
not saving folders at all?


--

  Mik Firestone

  mikfire@fastmail.com







On Fri, Jan 27, 2017, at 09:54, Tomek Lorek wrote:

> I understand not saving an empty folder, but if I add a recipe to a
> newly created folder it gets stored in the top-level "folder" and the
> newly created folder is not there, so effectively there is no folder
> support.  In that case how about removing references to folder
> maintenance in the UI so the users are not concerned?
> — You are receiving this because you commented. Reply to this email
> directly, view it on GitHub[1], or mute the thread[2].
> 




Links:

  1. https://github.com/Brewtarget/brewtarget/issues/346#issuecomment-275683389

**Comment by eltomek** [comment]
@mikfire you've replied too fast :) The latter comment was my mistake, I re-tested the non-empty case and it works as expected. You can remove my defect.

**Comment by eltomek** [comment]
Works as expected
