### ISSUE TITLE
Request: Double click ingredient opens ingredient editor

### ISSUE THREAD

**Issue by pricelessbrewing** [Brewtarget/brewtarget#350]
When double clicking the name of the ingredient while within the fermentables/hops/yeast table, it should open the relevant ingredient editor. This will make it more user friendly, especially for new users. 

Haven't kept track of all the 2.4 changes, but I don't think this was one of them?

**Comment by jonte** [comment]
@pricelessbrewing please check if the PR referenced above fixes your issue. I believe it should!

**Comment by pricelessbrewing** [comment]
If it works as described, then yes that's perfect.
