### ISSUE TITLE
Remove Default amounts in ingredients editors

### ISSUE THREAD

**Issue by eltomek** [Brewtarget/brewtarget#359]
I am focusing a bit on UI/UX aspects of Brewtarget and as part of my observations I'd like to suggest removing  _Default Ammount_ field that is present in each ingredient editor.

![image](https://cloud.githubusercontent.com/assets/3283040/23745267/e885c69e-04b7-11e7-9228-dcd63cea3611.png)

![image](https://cloud.githubusercontent.com/assets/3283040/23745327/110ea89c-04b8-11e7-8258-11589ae32fff.png)

This information seems to me to bring no value and if you share my view on that **I'd opt for removing it** to increase application experience (of course this is just a single field but if we focus on what's usable/important and what is not we may make the app even more user-friendly).

For any ingredient the amount needs to be manually dialed in anyway, I personally did not experience any that would appear as some specific default amount (other than 0 upon adding to the recipe) and this amount would be valid; fermentable, hop, yeast, all depend really on the recipe.

**Comment by pricelessbrewing** [comment]
I have no idea if that variable is used anywhere else, but I agree that removing it would increase user experience. 

On a similar note: Why do fermentables have a _Bitterness (IBU*gal/lb)_ property? Is there any case where this is applicable?

**Comment by rocketman768** [comment]
Prehopped extract.

**Comment by eltomek** [comment]
> Prehopped extract

Do we need it?

**Comment by kapinga** [comment]
As a small time homebrewer, it's nice to have things like yeast packets (which have a well defined size and are almost never used partially) default to a non-zero volume. It saves me needing to look up or memorize the amount of yeast in a particular package when building a recipe.

I would say the same goes for LME (I design my recipes to use exactly 3.3 lb increments of LME so I don't have partial cans of it) but LME seems to have a default volume of 0 as well.

I'd be OK if the 'default amount' option was removed from fermentables, hops, water, and misc, but I think it's useful in the yeast definition at least.

**Comment by kapinga** [comment]
> Do we need it?

Quickly scanning the fermentables list it doesn't look like BrewTarget by default includes profiles for pre-hopped extract, but if someone were to import a BeerXML recipe including one then BrewTarget would correctly process it. If we remove it from the UI, we end up in the weird place where BrewTarget would use the fermentable bitterness value without ever displaying to the user what that value is.

TBH, the ingredient editor is not something I actually use as an ordinary user very often - BrewTarget's default list of ingredients more than covers the selection of ingredients I actually use (save tweaking hops AA content, which can be done from the main UI). There are a lot of UI issues with BrewTarget, but I'm not sure this is the place to start chopping out features.

**Comment by pricelessbrewing** [comment]
So back to the root question, I don't see anywhere "default amount" is added. It's not when you add an ingredient, at least isn't for the tests I just did. When I added a grain, it still added 0 oz, even when the default amount was 15 lbs. 

If this isn't used anywhere, we should either remove it, or start using it.

**Comment by jhmcstanton** [comment]
I'm interested in picking this up.

If its decided to just remove it, is it just a matter of removing the field from the UI files? Likewise, if we decide to use it where should that change be made?

**Comment by jhmcstanton** [comment]
Went ahead and implemented the removal change, see commit 8cef99c above. If that isn't the desired change please let me know.

**Comment by jawsdaws** [comment]
From my testing, default amount is used when you double click an ingredient to add it to a recipe.  It seems to work on develop.  That said, I vote for taking it out.  It's seldom right and you always need to double check that its right when it does hit.

**Comment by pricelessbrewing** [comment]
I do see that it's working now, IDK why this wasn't working at the time. If it's working as intended, lets just leave it for now. Low priority. 

In the long term, I'd rather this work as a global setting, like "default amounts: Grain 1 lb, hops, 1 oz, yeast 200mL" something like that.

**Comment by jhmcstanton** [comment]
I'm more than happy to investigate the crash in #436 if we decide to remove the amount. If not, we can close the PR whenever.

**Comment by matty0ung** [comment]
I have removed these fields as part of the BeerJSON work.
