### ISSUE TITLE
Is there anyone building this on macOS?

### ISSUE THREAD

**Issue by ryho** [Brewtarget/brewtarget#375]
Sorry that this isn't the perfect venue, but I'm looking a project to start contributing to outside of work, and as the documentation stands, there's no way to get anywhere near running this program from source on macOS.

**Comment by rscmbbng** [comment]
There is a reference to mac packaging in the wiki: https://github.com/Brewtarget/brewtarget/wiki/Mac-Packaging

**Comment by ryho** [comment]
One of the prerequisites is:
You can successfully build and run Brewtarget on your mac.
I think this is about getting the final .app file that you can distribute to others.

**Comment by rocketman768** [comment]
The continuous integration build is a mac build. You pretty much just need to install the usual dev tools from xcode, cmake, and qt5. See the [.travis.yml](https://github.com/Brewtarget/brewtarget/blob/develop/.travis.yml) file.

**Comment by pricelessbrewing** [comment]
Going to close this. Been a year, and information was resolved. @ryho if further help is warranted, please reopen issue.
