### ISSUE TITLE
Dependencies are not the same in the main README and the vagrant provisioning file.

### ISSUE THREAD

**Issue by malavv** [Brewtarget/brewtarget#376]
Hey guys,

Trying to set up Vagrant provisioning, I noticed the dependencies it requires are different from those listed in the project's README. The inclusion of `libqt5svg5-dev` tells me that Vagrant's configuration is more up-to-date. In any case, a review of the dependencies should be made and the two synced and updated.

**Comment by xzfantom** [comment]
Is somebody uses vagrant now for developing? Should we keep it in main codebase?

**Comment by matty0ung** [comment]
Personally, I don't see the need for it.  If I want to keep "dev" and "personal" data separate, it's a couple of files (database and config) to copy, so having an entire virtual environment seems like overkill.  And if you did want to do testing in a separate VM, why not just build the brewtarget installer/package and run that to get all the dependencies installed.

**Comment by matty0ung** [comment]
Closing this ticket as I believe the dependencies listed at https://github.com/Brewtarget/brewtarget/wiki/Development:-Getting-Started are now up-to-date for Linux at least.  Please re-open (or better still update the wiki directly) if that's not the case.
