### ISSUE TITLE
Add "each" as a unit of measurement

### ISSUE THREAD

**Issue by dotps1** [Brewtarget/brewtarget#383]
I thought it would be a good idea to add the "each" as a unit of measurement,  for example, when adding an oak spiral stave, i would like to add it by _1 stave_ rather then by weight.

**Comment by matty0ung** [comment]
This is now possible in [Brewtarget 4.0](https://github.com/Brewtarget/brewtarget/releases/tag/v4.0.0) by setting "Amount Type" to "Count" for the Misc ingredient in question.
