### ISSUE TITLE
Typo in Yeast editor

### ISSUE THREAD

**Issue by dotps1** [Brewtarget/brewtarget#384]
there is a typo in in the Yeast editor dialog.  see screen shot:
![image](https://user-images.githubusercontent.com/1016996/32627418-5deca600-c560-11e7-9f2f-c54a573df3a8.png)

**Comment by rocketman768** [comment]
That is a valid word and is intended.

**Comment by dotps1** [comment]
looks like _quanta_ is plural for _quantum_.  https://en.wikipedia.org/wiki/Quanta.  I also searched _quanta yeast_ and i did not see any useful results.
