### ISSUE TITLE
Kettle volume loss due to trub

### ISSUE THREAD

**Issue by dotps1** [Brewtarget/brewtarget#385]
I feel like there should be another value when defining your equipment.  There should be the ability to account for trub loss in the kettle when transferring to fermenter.  I generally loose at least a half gallon on that right now, so it would be nice to have that calculated in my strike/sparge water when defining the mash.

**Comment by pricelessbrewing** [comment]
This exists in the equipment editor on the right under Losses and is labelled "Kettle to fermenter".

**Comment by dotps1** [comment]
thanks for the tip, I've moved on and purchased beersmith2.  thanks.
