### ISSUE TITLE
BeerJSON format development

### ISSUE THREAD

**Issue by superroma** [Brewtarget/brewtarget#388]
Hi

My name is Roman Eremin, and I have started a github repo to work on BeerJSON format.

https://github.com/beerjson/beerjson

BeerJSON is based on unfinished BeerXML 2.x, and hopefully will be less limited than BeerXML 1

If you are interested in joining the working group, let me know.

**Comment by matty0ung** [comment]
I have started working on adding BeerJSON support to Brewtarget (and Brewken).  Not sure yet how long it's going to take, but I think the prior work on improving BeerXML processing and enhancing the database layer will stand us in good stead here.

**Comment by matty0ung** [comment]
For anyone taking an interest, I'm at the stage where I can read and write Hop records to and from BeerJSON files (plus validate an entire file against the schema).  There's still a good bit more work to do, but it feels like it's all coming together.

**Comment by matty0ung** [comment]
After https://github.com/Brewtarget/brewtarget/pull/796 is merged, this should be done.  There will doubtless be a few glitches to iron out, but those can be new tickets.
