### ISSUE TITLE
 Notepad style recipe option.

### ISSUE THREAD

**Issue by jawsdaws** [Brewtarget/brewtarget#394]
A feature I would like to see would be to add an option to have a notepad/blank textedit box as a recipe of some kind.  The recipe could go into the recipe tree or maybe add another tab to the left and then to the right just have a textbox to write notes in.  It would be very nice to be able to keep some of my homebrewing instructions and notes that are not particularly related to a beer recipe.  Couple examples are home roasted grain and home canned wort for yeast starters. 

I'm willing to put the effort in to write code for this, although I haven't dug into if this is even possible.  I just wanted to see if this is something that would have a chance to be merged, and if so, some suggestions on what design would work.

**Comment by dpettersson** [comment]
There is already a notes field in the tab when you select "brew it". Isn't that what you are looking for or am i getting it wrong?

**Comment by jawsdaws** [comment]
I do use the "brew it" notes now as a workaround, but I thought it would be nice to have just a note so that the unused recipe data/ui is not in the way.  This is a very rough estimate of what I was thinking.

![screenshot from 2018-03-25 19-36-11](https://user-images.githubusercontent.com/3501812/37881369-0cc3bb4a-3065-11e8-87e6-ad9d02f4aa02.png)

**Comment by pricelessbrewing** [comment]
There's already a large, resizable note section that will expand as needed based on it's content in the Extras, taste notes and notes section. Going to close this.
