### ISSUE TITLE
Fermentable added to recipe has inventory amount set to zero.

### ISSUE THREAD

**Issue by JakeFry** [Brewtarget/brewtarget#396]
Fermentable added to recipe has inventory amount field set to zero. Fermentable inventory is not updated after using "brew it" even after changing fermentable inventory amount in recipe to actual value.

**Comment by MedicMomcilo** [comment]
I can confirm this behaviour, it seems like inventory doesn't update.
Tested also by setting default amount to a value and adding it to a recipe.

No matter what, I couldn't change amount of ingredients in the inventory via Brew It!.
With this, inventory function can't be used.

Tested against develop branch.

Please let me know if there is anything I can help with.

**Comment by pricelessbrewing** [comment]
Tested, confirmed still an issue in dev branch. 

No changes to creating new recipes, adding ingredients, and creating brew session via brew it! seemed to cause any change in fermentable inventory. 

Confirmed working for hops, and yeast. Although inventory for yeast is a bit strange how inventory is handled as an integer and isn't typed according to form.
