### ISSUE TITLE
ABV doesn't update after adding yeast

### ISSUE THREAD

**Issue by rocketman768** [Brewtarget/brewtarget#4]
Brewtarget 2.1.0_x86
Windows 7

To recreate:
1. Add fermentables
2. Add hops
3. Add a yeast product.

Expected result:
ABV is updated immediately.

Actual result:
All other scales are update except for the ABV. Only after closing the application and re-opening does the ABV update.

**Comment by IcanBENCHurCAT** [comment]
Can be closed
