### ISSUE TITLE
Brew it / generate brew notes

### ISSUE THREAD

**Issue by pricelessbrewing** [Brewtarget/brewtarget#403]
Soooo I didn't even know this existed and I've been using brewtarget for awhile. @mikfire  

I'm going to suggest making one of these tabs visible at all times, and that the "date" text field change the name of the tab? Or maybe change the tab name from a date to a sequential number system, so brew 1, brew 2 etc? That would make it more visible IMO.

**Comment by pricelessbrewing** [comment]
Alternatively, have that as a button along the toolbar? 

Honestly I couldn't figure out where this was again today and had to go look on the issue Mikfire wrote out on beerjson repo...

**Comment by matty0ung** [comment]
I do agree this is a bit of a hidden feature.  I only discovered its existence from working on the code.  Will have a think about where to put an additional more visible way to access it than the current right-click on a recipe.

**Comment by matty0ung** [comment]
I've added a fairly visible button for this functionality - see https://github.com/Brewtarget/brewtarget/pull/525.
Happy to hear views about whether the button should be in a different place or have a little icon instead of text etc.
