### ISSUE TITLE
Specific heat label fix (cal/(g*K)) to (Cal/(g*K))

### ISSUE THREAD

**Issue by pricelessbrewing** [Brewtarget/brewtarget#404]
According to the brewtargets typical values for specific heat (0.12 for aluminum), this should be labelled as a function of Cal, not cal. Otherwise aluminum would have a typical value of 0.00012.

I'll take this on as my first commit. Should be pretty straight forward, change to equipment UI, and manual, no changes to formulas or anything.

**Comment by dpettersson** [comment]
Assigning to @pricelessbrewing. Looking forward to reviewing :)

**Comment by pricelessbrewing** [comment]
Going with (Cal/(g*C)) since deltas in C and K are equivalent, and the Kelvin scale is not a supported temperature system. Moreover it is then equivalent with the standard in most software I'm aware of, which might be easier in the event that specific heat for equipment is ever part of the BeerXML/BeerJSON standard.
