### ISSUE TITLE
Doesn't build using cmake 3.x

### ISSUE THREAD

**Issue by zephrax** [Brewtarget/brewtarget#409]
It cannot build using cmake 3.x

As far as I searched on the internet, the QT5_USE_MODULES routine is obsolete and seems to be deprecated in that version.

Reference:  https://doc.qt.io/qt-5/cmake-manual.html

CMake version: cmake version 3.11.2
My build output log:

-- The C compiler identification is GNU 8.1.0
-- The CXX compiler identification is GNU 8.1.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_SYSTEM_INCLUDE_PATH: /usr/include/X11
-- Building Brewtarget.
CMake Error at src/CMakeLists.txt:432 (QT5_USE_MODULES):
  Unknown CMake command "QT5_USE_MODULES".

**Comment by dpettersson** [comment]
Strangely enough it builds for me (using cmake 3.5.1)

**Comment by david-geiger** [comment]
This build issue come from new Qt5 5.11 not from cmake. Upstream now removed the QT5_USE_MODULES function.
