### ISSUE TITLE
Support for Brew-in-a-bag

### ISSUE THREAD

**Issue by Mackanzx** [Brewtarget/brewtarget#41]
I am currently only brewing using the BIAB method, which makes the mash editor/wizard a bit confusing to use in BT. (from what i understand, the calculations depend on using the mash wizard to create the "final batch sparge")

I think many other new brewers looking for a software to use are also using/planning to use BIAB. I also think that it is hard to get BIAB brewers that use other software to switch to brewtarget unless there's a simple and obvious way to configure BIAB.

I looked at supporting BIAB as an "actual mash style", and found that it would require a few changes:
- Extending the DB with a brew/mash style of the equipment
- Adaptations to the equipment editor. (selection of mash/brew style, disabling irrelevant fields such as mash tun)
- Adaptations to the math and logic behind calculating the mash, and quite some GUI changes in the mash tab.

I started doing the first two tasks since they're pretty simple, but hit a wall when looking at how to actually create and calculate the mash step.

My point with this issue is to start a discussion about the direction BT should take regarding BIAB as a growing brew method, and if it should be implemented as a bigger feature or maybe just as a simple button in the mash tab to create a "BIAB mash step". I'm sure mikfire has some input here :smile_cat:

**Comment by mikfire** [comment]
All I can say is I have been working on it. It is a long explanation, but
it sort of boils down to brewtarget makes an awful lot of assumptions about
the brewing methods. Even something as simple as adding support for a
double batch sparge has me completely stumped.

I've extended the database (not really required, but close enough), I've
modified things to support many different sparge methods but I cannot make
the math work properly. I quite literally cannot find the code that is
assuming the last sparge must make the difference between the amount of
water from all the infusions and your preboil volume.

And until I can get this working, everything else is sort of blocked.

Mik

On Sun, May 17, 2015 at 3:17 PM, Mackanzx <notifications@github.com> wrote:

> I am currently only brewing using the BIAB method, which makes the mash
> editor/wizard a bit confusing to use in BT. (from what i understand, the
> calculations depend on using the mash wizard to create the "final batch
> sparge")
>
> I think many other new brewers looking for a software to use are also
> using/planning to use BIAB. I also think that it is hard to get BIAB
> brewers that use other software to switch to brewtarget unless there's a
> simple and obvious way to configure BIAB.
>
> I looked at supporting BIAB as an "actual mash style", and found that it
> would require a few changes:
>
>    - Extending the DB with a brew/mash style of the equipment
>    - Adaptations to the equipment editor. (selection of mash/brew style,
>    disabling irrelevant fields such as mash tun)
>    - Adaptations to the math and logic behind calculating the mash, and
>    quite some GUI changes in the mash tab.
>
> I started doing the first two tasks since they're pretty simple, but hit a
> wall when looking at how to actually create and calculate the mash step.
>
> My point with this issue is to start a discussion about the direction BT
> should take regarding BIAB as a growing brew method, and if it should be
> implemented as a bigger feature or maybe just as a simple button in the
> mash tab to create a "BIAB mash step". I'm sure mikfire has some input here [image:
> :smile_cat:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Brewtarget/brewtarget/issues/41>.
>



-- 
In a world of ninja v. pirate, I pilot a Gundam

**Comment by Mackanzx** [comment]
Oh, so you're already under way. Great news :+1:

**Comment by rocketman768** [comment]
There's [this line](https://github.com/Brewtarget/brewtarget/blob/master/src/MashWizard.cpp#L221) if it helps.

**Comment by mikfire** [comment]
It might, but that's not the only one. The mash designer does the same kind of magic and that's the one that has had me scratching my head for a while. But maybe this will be enough of a hint to find it in the mash designer.

**Comment by pricelessbrewing** [comment]
Alright so I know this is super old, but I think this is actually supported in a round about way. 

1) Ignore thermal mass of mash tun, you can do this by setting the heat capacity of the mash tun to 0.00.

2) Single stage full volume infusion. Either use the mash designed and increase the infusion volume until the total collected wort matches the target preboil volume. OR enter the manually calculated mash thickness that will give the corresponding run off volume to match the preboil volume. 

3) Adjust the grain absorption rate to match your biab absorption rate (note that the default units are qt/lb)

4) Click finish. If done properly, it should be correct.

**Comment by Mackanzx** [comment]
Thank you for the instructions, I was experimenting with something like this but it's great to have clear instructions. I havent yet brewed a beer with a recipe like this and compared it to the results.

There's another step too. If you want to add water after removing the bag you need to edit the "kettle top-up" in the equipment. Or perhaps it is just easier (and mathematically still correct) to just add that water to the mash step instead, even though you're mashing with a lesser amount.

I realise that maybe we don't need to change all that much to support BIAB in a simple manner if you just need to adapt the equipment and have a single mash step for it to be accurate.

Do you guys think a guide like this would suffice as BIAB support?

**Comment by pricelessbrewing** [comment]
Correct, if you're doing a kettle top off (into fermenter, after the boil)  then you should use the kettle top off feature. 

If you're doing a sparge, then you should add an additional infusion step and reduce the initial infusion volume accordingly so the sum of the two run off volumes (after squeezing and after sparging) equal the preboil volume. 

Iyou're topping off the kettle between mashing and starting the boil, then you really are hurting your lauter efficiency for no reason and should employ a sparge instead. 

I think it would be helpful to set up three mash profiles by default.  Have the default be a single step batch sparge, with the two other options being biab full volume mash, and a too stage step mash.

**Comment by cgspeck** [comment]
Thank you @pricelessbrewing for posting your workaround

**Comment by pricelessbrewing** [comment]
Closing as changes to code is not needed. Documentation should be adjusted accordingly before release of 2.4

**Comment by karthil** [comment]
I attempted to follow the directions to match up with brew in a bag but couldn't find the exact settings mentioned in the description. Are they perhaps outdated it just not quite accurate?  Thanks!

**Comment by pricelessbrewing** [comment]
@karthil 
> I attempted to follow the directions to match up with brew in a bag but couldn't find the exact settings mentioned in the description. Are they perhaps outdated it just not quite accurate? Thanks!

What version of brewtarget are you using? And what brewing process type are you performing, brew in a bag full volume / no sparge?

**Comment by karthil** [comment]
Hi Mark,
I'm performing full volume, brew in a bag brewing (with no sparge).  And
I'm using version 2.3.0.

Thanks!

**Comment by pricelessbrewing** [comment]
Alright here's a complete guide to setting up brew in a bag, no sparge / full volume single vessel (brew kettle, no mashtun). 

Equipment Profile:
Set mashtun mass and specific heat to zero. Set Lauter deadspace to zero. 
In the Boiling & water section, change the grain absorption rate (qt/lb) to around 0.32 qt/lb. 

Using the mash designer:
Type = Infusion
Set target temp
Set time

Using the slider, drag it to the right until the "total collected wort" shows 100%. Note that it is possible to exceed 100%, but it will continue to show 100%. The value in the center is the total run off wort, and the value on the right is the target preboil volume. 

Click finish. 

Alternatively You can use do the calculation by hand and use the mash wizard to set the mash thickness. 

Mash Thickness = (Preboil_Volume + (Grain_Absorption_Rate * 4) * Total_Grain_Weight) / Total_Grain_Weight. 

Or use an online calculator to get the mash thickness, like mine (priceless biab calc), or biabcalculator.com etc. 

Let me know if you still have any questions.

**Comment by karthil** [comment]
Thanks a lot, Mark.  Everything's clear until the mash designer step.  When
you mention moving the slider, are you referring to the "Infusion/Decoction
Amount"?  If so, I can never get the total collected wort to reach 100%.  I
presume it's related to the fact that the min value on the slider is
2.802qt while the max is -1.299 gal (yes, negative).  Thoughts on what
might be misconfigured there?  I just started witht the 5.5 gallon all
grain equipment profile if that matters.

**Comment by karthil** [comment]
For those curious...make sure you're not an idiot like me...my mash tun
volume was also zeroed out.  Everything looks great once I set it
properly.  Thanks Mark!
