### ISSUE TITLE
Mash Designer Temperature Bugs

### ISSUE THREAD

**Issue by trinkner** [Brewtarget/brewtarget#412]
In version 2.3.1, using the Mash Designer to create a mash schedule calculates temperatures that are far too high. I'm running Ubuntu 18.04, and saw exactly the same bugs on Windows 10.

To reproduce:

Set preferences to US Imperial units and Fahrenheit.
Create new recipe. 
Add fermentables, hops, etc.
Click on Mash tab.
Click on Mash Des button.
I entered 75 for the initial equipment temperature.
In the Mash Designer window, give name to step ("Mash In"), select "Batch Sparge" checkbox (checked), Enter 152 for temperature and 1 hour for time.
BUG: notice the temperature range in the center of the dialog box: it's "low" temperature on the left reads 218.864 and the "high" temperature reads 212.000.  The low temperature cannot be higher than the high.  (See screen shot 1).  When the user slides the top Infusion/Decoction slider to add water to the step, the temperature calculated in the center does not change from 218.864.
Unclicking the Batch Sparge checkbox and then mousing the Infusion/Decoction slider causes the calculated temperature to change correctly. (See screen shot 2).

I've seen the same results with two brews on two computers on two OSs (Windows, Ubuntu) both running 2.3.1.

Since calculating mash volume and temperature is in one of the most important calculations, this seems like a highly important bug.

Thanks very much for an otherwise good product!
![bt_1](https://user-images.githubusercontent.com/28911690/42413885-fae6c858-81e6-11e8-87d7-3695037418a1.jpg)
![bt_2](https://user-images.githubusercontent.com/28911690/42413886-fafac42a-81e6-11e8-9935-eb466c660624.jpg)

**Comment by pricelessbrewing** [comment]
I believe this is fixed in 2.4, not getting the issue on my build.

Related:
https://github.com/Brewtarget/brewtarget/issues/283
https://github.com/Brewtarget/brewtarget/issues/279

https://github.com/Brewtarget/brewtarget/pull/297

**Comment by pricelessbrewing** [comment]
Don't know. @rocketman768, what's the status #289 ? Is there anything specific we're waiting on? Any testing I can help with?

**Comment by pricelessbrewing** [comment]
@trinkner I'm going to close this as the issue in question has been patched. Questions regarding the release schedule will depend on when the open bug issues and any relevent features get completed, and should be directed at #289
