### ISSUE TITLE
Brewnotes don't work any more

### ISSUE THREAD

**Issue by mikfire** [Brewtarget/brewtarget#417]
Trying to create a new brewnote throws this error:
```
[08:20:54.537] ERROR : void Database::updateEntry(Brewtarget::DBTable, int, const char*, QVariant, QMetaProperty, BeerXMLElement*, bool, bool) Could not update brewnote.attenuation to 100: UPDATE brewnote set attenuation=:value where id=121 ERROR:  syntax error at or near "("
LINE 1: EXECUTE  (100)
```

This is caused by 
```
const QString kAttenuation("attenuation");
```
in brewnote.cpp. The brewnote table in the database does not have a field called "attenuation". I believe this should be 
```
const QString kAttenuation("projected_atten");
```

**Comment by mikfire** [comment]
It would seem the event that should have added this to the table definition didn't fire? My table version is at 8 and has been at least as far back as 2017-12-27. This update marks database v7, so it looks like the code would have never fired.

This is  likely my problem. Closing the ticket.

**Comment by pricelessbrewing** [comment]
Tested on latest build, notes and taste notes are both working for me.
