### ISSUE TITLE
Old recipe crashes Brewtarget

### ISSUE THREAD

**Issue by anderwm** [Brewtarget/brewtarget#420]
I have a database with old recipes from much earlier versions of brewtarget. When I restore the database and double click on those recipes Brewtarget crashes immediately. Anybody seen this?

**Comment by anderwm** [comment]
I'm not sure exactly how old, I've used Brewtarget for about 5 years. But I brewed this recipe this year and I usually add to the brewnotes each time. I tried exporting and importing and it still crashes on import (terminate called without an active exception). XML looks clean, see what you think when you recover from your sampling. I had to change the extension to get it to upload.
[germanPils.txt](https://github.com/Brewtarget/brewtarget/files/2297294/germanPils.txt)

**Comment by jawsdaws** [comment]
I gave your XML a try and I get a crash too. I get this error.

'QObject::connect: No such slot MashDesigner::typeChanged(int) in MashDesigner.cpp:65'
'QObject::connect:  (sender name:   'comboBox_type')'
'QObject::connect:  (receiver name: 'mashDesigner')'
'terminate called without an active exception'
'Aborted (core dumped)'

 I can't really look any further into until next week though... I have a busy weekend planned.

**Comment by anderwm** [comment]
No rush on my end, I have all the information from the recipe...just a bug

**Comment by jawsdaws** [comment]
This appears to be a bug from when you exported.  Do you know what version you used to do the export?  I tried to replicate this with a 2.4.0 build from git, but I could not replicate a bad XML export.  That said, database.cpp calls `throw;` without a log of any kind in quite a few different places.  That's not ideal when importing who knows what in an XML.  Some better error handling would be very useful.

Here's a fix for your file in the mean time.  At least it worked on my git build. :-)

Line 255 should read `<TYPE>Infusion</TYPE>`  "Batch sparge" is not a valid BeerXML type and the code does not support it.

Line 277 `<DATE_FERMENTED_OUT>CURRENT_DATETIME</DATE_FERMENTED_OUT>` can be deleted and changed back to the proper date inside Brewtarget after you get the import done.

**Comment by anderwm** [comment]
Who knows what version, I build from source and update randomly whenever the mood strikes. Probably not important what the XML error is but I just expected it would get caught somewhere and not crash the Main. Thanks for looking at it.

**Comment by jawsdaws** [comment]
> get caught somewhere and not crash the Main.
Agree.  I'll start a new issue and see about making some of the XML error handling more robust. Cheers!

**Comment by mikfire** [comment]
Can this issue be closed?

**Comment by mattiasmaahl** [comment]
I would say Its closed.
Open new ticket if this is still an issue.
