### ISSUE TITLE
Improve XML import/export error handling.

### ISSUE THREAD

**Issue by jawsdaws** [Brewtarget/brewtarget#421]
As stated in #420 , database.cpp calls `throw;` without a log of any kind in quite a few different places in the XML import/export code.  It should be improved to be more robust.  I'll work on it, if you want to assign me.

Edit: This might help with #280 too.

**Comment by pricelessbrewing** [comment]
Thanks! I've assigned it to you. 

For #280 I think an error log would be helpful, but I'm not holding my breath that it will be solved as the error is likely to be on other softwares xml

**Comment by jawsdaws** [comment]
So apparently everywhere in database.cpp where `throw QString(...);` is called the program will crash with the error message

> Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt.
You must not let any exception whatsoever propagate through Qt code.
If that is not possible, in Qt 5 you must at least reimplement
QCoreApplication::notify() and catch all exceptions there.

Is this new behavior for QT?  I would not think it has always been this way?  Anyways, it makes me think that error messages and logs would be a better way to go and just do away with exceptions where possible, but that's going to be a lot of work.  I don't mind doing the work, but I figured I would see what others think.  Can I get some confirmation this is a good path before I put in some work?

**Comment by jawsdaws** [comment]
If there is no feedback for now, I'll submit a merge request soon for some fixes for the files in #280 and #420.  There will still most likely be bugs if other xml files are nonstandard in some way.

**Comment by dpettersson** [comment]
Please do. :)

**Comment by jawsdaws** [comment]
This can be closed now.
