### ISSUE TITLE
Lovibond as color unit option

### ISSUE THREAD

**Issue by pricelessbrewing** [Brewtarget/brewtarget#428]
Lovibond, or Lovi for short, is the industry standard in the US for malt color specification. Should be an option for unit type. 

Of note is that SRM is defined by how much light is absorbed when passing through a specific distance of beer/liquid (1 cm IIRC), so it shouldn't be applicable to fermentables. 

Although you could make the argument that they're analogous if a beer is the same color as a malt then the malt also has the same SRM value.

**Comment by jmichalicek** [comment]
I would love to see this. I just asked a related question about this on the google group for Brewtarget. When talking srm and lovibond in the range of actual beer, there's not a ton of difference, but possibly noticeable as the numbers get much above 20.

With dark grains the difference between srm and lovibond is pretty high but I had noticed that Brewtarget seems to assume they are the same. For example Briess Caramel 80 is in the database as 80 srm when it's actually 80 lovibond which is about 108 srm. The darker the grain, the more off that is going to be.

**Comment by jmichalicek** [comment]
Just read over #366 which I missed before. So it looks like the correct units are being used and all is calculated correctly. The label is just incorrect. That's good to know.

**Comment by matty0ung** [comment]
FYI I have added support for Lovibond to Brewken as part of the work to support BeerJSON.  At some point this will get merged in to Brewtarget code.  (I'm trying to avoid cluttering up Brewtarget with too much work-in-progress.  There's still a fair way to go on BeerJSON because it's such a big change from the status quo. I have code reading & validating the files just fine but there are a lot of changes required to the DB schema to support all the fields that aren't present in BeerXML.)

**Comment by matty0ung** [comment]
Code changes are in `develop`, so will be included in the 4.0 release.

**Comment by gdselzer** [comment]
I do not see Lovibond as an option under Options>Units>Color.  Only SRM and EBC.  Am I doing something wrong, or was it removed after v4.0?  I'm on 4.1.3.

**Comment by matty0ung** [comment]
Ah, yes, I see what you mean.  I'll do a fix.  Lovibond is there generally, eg if you click on the label for any field that shows a color, you'll have the options to show Default/Lovibond/SRM/EBC.  There must be something excluding it from the options menu.  Have raised https://github.com/Brewtarget/brewtarget/issues/1010 for this.
