### ISSUE TITLE
High DPI Display problems

### ISSUE THREAD

**Issue by jawsdaws** [Brewtarget/brewtarget#434]
![brewtargethdpi](https://user-images.githubusercontent.com/3501812/46827224-18b9fb00-cd66-11e8-968c-170ce391eb7f.png)
On my new HDPI (to me anyways) display there are some strange artifacts and general weirdness.  I've worked on some fixes.  They are at https://github.com/jawsdaws/brewtarget if anyone wants to take a look.  There's more to do though before I have a merge ready.

**Comment by jawsdaws** [comment]
There looks to be an easy fix.  I'm going to do more testing over the weekend, and next week.  You can assign this one to me if you like.

**Comment by jawsdaws** [comment]
I have some code for quite a few fixes here, but I'm not done.  I would like to get some help testing to make sure I'm on the right path.  I only have Linux available to test on so Mac and Windows help is needed.  Not sure the best way to get help on this though.  Maybe just merge the changes and see if it breaks?  I guess also if you see this and can help, checkout [https://github.com/jawsdaws/brewtarget/tree/HiDPI](https://github.com/jawsdaws/brewtarget/tree/HiDPI)

**Comment by jawsdaws** [comment]
Thanks @DRiKE  . I tried that, but it was unreliable.  It appears to work for some display drivers, but not others.  I may be wrong, but that seemed to be the only thing I changed when it stopped working on Ubuntu 18.04.  I've some code to adjust some of the pixel values based on logicalDotsPerInch() and it seems to work and be more robust.  I've just been distracted with other things lately. :-)

**Comment by dzsquared** [comment]
Just a note for anyone who comes across the high-DPI scaling issues on Windows - these are the properties changes to BrewTarget.exe that I've made to display the app
![image](https://user-images.githubusercontent.com/12227241/89969576-9c1b3080-dc0b-11ea-8582-69e48a09bed3.png)

**Comment by Wyrmwood** [comment]
Thanks!

Regards,
Grognard

וצריך ביאור
*One way is to make it so simple that there are obviously no deficiencies,
and the other way is to make it so complicated that there are no obvious
deficiencies. - Tony Hoare*

**Comment by dschwilk** [comment]
I have this issue with current develop branch build on kubuntu 20.04. Setting the environment variable QT_FONT_DPI=96 on the brewtarget command call does help.

**Comment by jawsdaws** [comment]
> I have this issue with current develop branch build on kubuntu 20.04. Setting the environment variable QT_FONT_DPI=96 on the brewtarget command line fixes.

This is a much better solution than the hackery I was working on.

**Comment by matty0ung** [comment]
I have a fix that addresses this without having to set environment variables etc.  Specifically it makes the icons and range sliders a sensible size.
