### ISSUE TITLE
2.2.0 Stable Branch

### ISSUE THREAD

**Issue by rocketman768** [Brewtarget/brewtarget#44]
@Brewtarget/developers 

I am creating a stable branch for the 2.2.0 release. No need for you to do anything extra or differently. If a pull request is a new feature, I will pull it only to the master branch. If a pull request is a bug fix, then I will pull it to both the master and stable branch. This way, nobody is blocked from working on new features, and we are able to stabilize 2.2.0 concurrently.

The only thing to consider is that if you are working on a new feature and are tempted to **also** fix a bug, please fix the bug in a separate pull request so that it may be applied to the stable branch.

**Comment by theophae** [comment]
What is the plan for this release ?
Don't you think that some simple feature should be included in this version ? I'm thinking to the BBCode export which come with a lot of bug fix on recipe export.

**Comment by rocketman768** [comment]
Sorry for delaying the release; if I have time this weekend I'll do a thorough regression test and finalize the branch for release.

#66 is a very large commit. What do you estimate is the risk?

**Comment by theophae** [comment]
About #66, I think that the risk is very small. Almost all the changes are in the recipe formatter file. I've done many test to check that there is no crashes, and it is ok.
Don't forget to update translation on launchpad after merging this branch. Translation will be impacted.

**Comment by theophae** [comment]
I've seen you've merge my branch with the recipe export Text/BBCode. Do you plane to merge it in 2.2.0 too ?
To me it is necessary because it fixes a lot of bugs in Text export and also in HTML print/export for both recipe and brewday. The BBCode is a new feature, but it is a minor change compare to all the bug fixed.

**Comment by rocketman768** [comment]
It is a good change. Unfortunately, the bug fixes are mixed with both new features and translation string changes. The new feature is not so bad, but it takes Launchpad months to update our strings. The change is on-track for 2.3.0, which I will release in just 2 months anyway to get back on a biannual release schedule.

**Comment by theophae** [comment]
Ok, I understand the point about launchpad. And if the 2.3.0 will come out in little time it is OK.
