### ISSUE TITLE
Where is database stored?

### ISSUE THREAD

**Issue by EricFries** [Brewtarget/brewtarget#441]
I'm using Brewtarget on OS X, and my database seems to have disappeared.  I am going to try and restore it from a backup, but I'm not sure where to look.  Where is the database stored?

**Comment by matty0ung** [comment]
Hopefully you already found an answer after all this time, but adding a comment here for the benefit of anyone else who has a similar question.

From looking at the source code, it looks like (for both Mac and Linux), the DB files (main and automatic backups) usually live in ~/.config/brewtarget. (In other words, in your home folder, there's a hidden subfolder called ".config" and inside that there's another folder called "brewtarget", and that's where the files are.)  Main DB file is called "database.sqlite". Automatic backups are called things like "bt_database.20201025".

(It's possible to override the default location where database files are stored, via the XDG_CONFIG_HOME environment variable, but I'm guessing you didn't do this!)

**Comment by EricFries** [comment]
Thank you @matty0ung, I was able to track it down.  I'm not sure why the database gets nuked but it does seem to happen now and then.

**Comment by jmtremblay2** [comment]
for the benefit of everyone else, this is also available in tools->options, under the "directories" tab (on 2.3.1)
![image](https://user-images.githubusercontent.com/40041845/127585748-cab6f74c-af6c-4d10-b029-ce47cb74da73.png)
