### ISSUE TITLE
Why does MainWindow create a recipe by poking directly into the Database()?

### ISSUE THREAD

**Issue by mikfire** [Brewtarget/brewtarget#446]
I am sure I am responsible for this, but I cannot remember the logic behind it. In my rough estimation, MainWindow() is the view and the Recipe object is both model and controller.

Shouldn't MainWindow() call the Recipe objectclass to create a new Recipe object and have exactly no knowledge of the database?

Oh. And I suspect this may just be a "because we always did it that way". Which is an acceptable answer.

**Comment by matty0ung** [comment]
Might be time to refactor a bit?

**Comment by matty0ung** [comment]
Pull request https://github.com/Brewtarget/brewtarget/pull/499 takes a step in the right direction here - asking Recipe to insert itself in the database.  Just need a bit more work to make the Recipe object handle adding equipment to itself.

**Comment by mikfire** [comment]
Cool. I will close this in anticipation of PR#499
