### ISSUE TITLE
Printouts are black with dark theme.

### ISSUE THREAD

**Issue by hawesy** [Brewtarget/brewtarget#454]
My Qt theme is a Breeze-Dark theme with dark grey everywhere. It seems this theme follows into the draw canvas for printouts. Recipes and brewday are both unreadable.

I can work around it by changing my theme before I print, but it might be worth changing the print engine to force a light theme or just ignore the theme completely.

**Comment by hawesy** [comment]
Brewtarget 2.3.1 on Manjaro. KDE 5.18.

**Comment by matty0ung** [comment]
@mattiasmaahl rewrote all the printing code a while back, so I believe this is now fixed in the 3.0 release.  As ever though, please re-open if you still experience the same problem with the latest code.
