### ISSUE TITLE
Time automatically displayed in hours if the value in minute exceeds 60 min

### ISSUE THREAD

**Issue by theophae** [Brewtarget/brewtarget#46]
It is not really a bug, but when I enter a boil time, 75 min for example, BT transforms it automatically to 1.250 hr. It is a bit annoying to me, because it is not very natural to work with time using power of ten. I checked in the code to see if I could simply change that, but it is not that simple because it uses the same mechanism as for weight and volumes, so we have to treat time values separately.

Two options can be chosen to change this:
 1 - Using the bigger unit only if the smaller ones have a null value. For example 75 min stays like that, but 120 min is changed to 2 h.
 2 - Displaying the time always as hh:mm:ss

I prefer the first option.

**Comment by mikfire** [comment]
Or you can right click and set the scale to minutes?

**Comment by theophae** [comment]
And for hop boiling duration ?

**Comment by mikfire** [comment]
Yup. Right click the column header and set the scale there. If I've done my work properly, that should display properly in all of the print outs too.

I will fix the formatting of the output. 1.25 hour is technically correct, but is somewhat jarring.

**Comment by theophae** [comment]
You did a great job !
This unit management is really a plus comparing with the other brewing software.
Now I know how to choose all the display unit it is ok.
We may find a way to make these parameters easier to see.

**Comment by theophae** [comment]
About this, I noticed that the unit choice is not used for recipe export.
I think the units and scales should be the same for export formats as for the main window.
This need to be clarified.

**Comment by theophae** [comment]
I've done this enhancement in the pull request #66, so this can be closed.
