### ISSUE TITLE
SQL Database Error in mashstep

### ISSUE THREAD

**Issue by nob0dy73** [Brewtarget/brewtarget#461]
First time commenting so please bear with me. 

Program crashes with a cryptic error of "Parameter count mismatch" when trying to use the Mash Des or the Mash wiz as shown below:
>[15:20:58.375] ERROR : int Database::insertElement(BeerXMLElement*) could not insert a record into mashstep: INSERT INTO mashstep (decoction_amount,deleted,display,end_temp,folder,infuse_amount,infuse_temp,name,ramp_time,step_number,step_temp,step_time,mstype) VALUES(:decoctionAmount_l,:deleted,:display,:endTemp_c,:folder,:infuseAmount_l,:infuseTemp_c,:name,:rampTime_min,:stepNumber,:stepTemp_c,:stepTime_min,:typeString) Parameter count mismatch

When manually inserting the same entry into the SQL database sqlite3 produces an error:

> sqlite> INSERT INTO mashstep (decoction_amount,deleted,display,end_temp,folder,infuse_amount,infuse_temp,name,ramp_time,step_number,
>step_temp,step_time,mstype) VALUES(:decoctionAmount_l,:deleted,:display,:endTemp_c,:folder,:infuseAmount_l,:infuseTemp_c,:name,:ramp
Time_min,:stepNumber,:stepTemp_c,:stepTime_min,:typeString);
                      
>Error: table mashstep has no column named folder

Taking folder out of the expression fixes the error and an entry can be made.

Looking into how the SQL entries are made in brewtarget I've discovered that in TableSchema::defineMashstepTable() that there is a  m_properties[kpropFolder]. By commenting this line out this fixes the issue. 

I haven't tested further to see how this affects the program but I'm assuming that this will start affecting thing poorly.

**Comment by mikfire** [comment]
Hum. Mashsteps should not have folders.
