### ISSUE TITLE
Will there be version 2.3.1 for Windows?

### ISSUE THREAD

**Issue by mrkaban** [Brewtarget/brewtarget#464]
Thank you very much for such a program under the free GNU GPL license! This is a great contribution to the development of everything in the world in general!

Added it to the site about free software in Russian ([link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D0%B4%D1%80%D1%83%D0%B3%D0%B8%D0%B5-%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D1%8B/brewtarget-%D0%BF%D0%B8%D0%B2%D0%BE%D0%B2%D0%B0%D1%80%D0%B5%D0%BD%D0%B8%D0%B5.html)).

The first thing I said when I saw your program is "for 8 years of the existence of the site this is the first really interesting program."

Immediately the question is, will there be version 2.3.1 for Windows?

**Comment by mikfire** [comment]
No. The 2.3.1 release was specific to Ubuntu and had no real code impact. 

If we release anything new for windows, it will be 2.4.0
