### ISSUE TITLE
Feature request - Alpha % in Inventory Report

### ISSUE THREAD

**Issue by tpiszcze** [Brewtarget/brewtarget#466]
I think it would be helpful to have Alpha % column in Hops section in Inventory Report.

**Comment by matty0ung** [comment]
This is probably small work to code.  I'll have a look at it once my fix (https://github.com/Brewtarget/brewtarget/pull/499) for https://github.com/Brewtarget/brewtarget/issues/370 is merged.

**Comment by matty0ung** [comment]
@tpiszcze I have just uploaded a patch for this which hopefully does more or less what you want.  (Sorry for the delay since my last post.  I did some work on XML that proved to be a deeper rabbit hole than I expected.)

**Comment by tpiszcze** [comment]
Works great.
Many thanks!
