### ISSUE TITLE
Database gone/reset to defaults

### ISSUE THREAD

**Issue by brianbuccola** [Brewtarget/brewtarget#469]
Hi,

Basically the same thing as #247, it seems. I opened brewtarget, and all my settings, equipment, recipes, etc. are gone. Tried quitting and restarting several times, no luck.

One thing that may be related: I often open brewtarget just to check some info and then close it, without changing anything. Yet brewtarget asks if I want to save my changes. I always click "No" just to be safe (in case I did accidentally change something), but now I wonder whether by clicking "No" at some point, it decided simply to wipe out my database entirely.

Not sure there's anything I can do besides report the experience. I guess from now on I'll save a copy in Dropbox.

Brian

**Comment by mikfire** [comment]
I am honestly very sorry this happened. Right now, using dropbox as your data directory is our best recommendation. What version are you using?

PR #260 did resolve as many of the issues as I could find. But I am not certain it ever made it into a release. We lost our release manager just before 2.4.0, and nobody has yet volunteered to try again.

**Comment by brianbuccola** [comment]
I'm on version 2.3.1, from the Arch Linux repository. I'll try upgrading to 2.4.0 and see if that helps.

> I am honestly very sorry that this happened.

No worries at all. Thanks for all the hard work. Brewtarget has been very useful.

**Comment by soldbyboyd** [comment]
This is also my experience--everything is gone :(. Another problem I have, though, is that whenever I click the button/field next to beer category, or try to add a fermentable, the program closes out without warning.

I really love this program and would like to use it again! A little sad about losing a few dozen recipes but we can rebuild. Any advice?

**Comment by matty0ung** [comment]
@soldbyboyd, I wonder if the crashing is perhaps because of some permissions issue either with your database file or with the directory it lives in.  Can you upload your log file (brewtarget_log.txt), configuration file (brewtarget.conf) and database file (database.sqlite)?

**Comment by matty0ung** [comment]
@mikfire What needs to be done to get 2.4.0 out the door? Happy to help...

**Comment by dpettersson** [comment]
Hi,

The database should have been backed up and they should be located in the
same directory as the regular db. Replace the current db with an older copy
and your recipies should be back.

These older copies are replace at some points so it might be to late, but
it is worth a try.

/Dpettersson

Den lör 12 sep. 2020 01:19soldbyboyd <notifications@github.com> skrev:

**Comment by matty0ung** [comment]
Closing this ticket as I believe this should no longer be an issue with the latest release (3.0.0) as there has been quite a lot of work to make DB handling more robust, including adding automatic DB backups.
