### ISSUE TITLE
Critical regression in several tools due to auto unit display

### ISSUE THREAD

**Issue by theophae** [Brewtarget/brewtarget#47]
The refractometer tool is broken because of the automatic conversion to "sg" gravity for all input fields. Because of that, it is impossible to correctly fill the input fields. For example, il you want to enter 15 Plato in the Original Plato field, it will be automatically replaced by 15.000 sg
I've seen a bug on the strike water calculator too. This time, the unit entered is not read, but it choose the smallest unit instead. To enter the weight of the grain, if I enter 5 kg it will change it to 5 mg. If I really want to put 5 kg I need to enter 5 000 000, then 5 kg is displayed.

@mikfire : This bug is coming from the BtLineEdit widget you've added. I think that this feature is very cool because it keeps the displayed field consistent. The problem is that for most of the tools, there are fields that needs to be filled with a specific unit, so we need to add something to allow forcing it. I'm not really a specialist of QtCreator, so I don't know yet how to implement it, so if you have something in mind please tell me ;) 

The 2.2.0 version mustn't be released with this bug.

**Comment by theophae** [comment]
I've seen a bug on the strike water calculator too. This time, the unit entered is not read, but it choose the smallest unit instead. To enter the weight of the grain, if I enter 5 kg it will change it to 5 mg. If I really want to put 5 kg I need to enter 5 000 000, then 5 kg is displayed.

I confirm that this bug it critical because it may touch every part of the software.

**Comment by mikfire** [comment]
I thought I had fixed that at some point. Assign this to me.

**Comment by theophae** [comment]
How can I assign it to you ?

**Comment by mikfire** [comment]
Beats me. As far as I've been able to see, only rocketman can assign tickets.

**Comment by rocketman768** [comment]
Yeah, this part of github's interface sucks.

**Comment by mikfire** [comment]
I think I can provide a per-field over ride. It will take me a few days to worm back through the unit system and make sure my idea will work. 

In the meantime, can somebody generate a list of the ui files (at least) that need to be fixed?

**Comment by theophae** [comment]
These are the fields that have a problem:

OG Calculation help:
 - Plato
 
Refractometer Tools:
 - Original Plato
 - Current Plato

Equipement editor:
 - Mass (Problem with mass conversion)
 - Specific heat (always display "?")
 
Name Mash Editor:
 - Tun mass (Problem with mass conversion)
 
Strike water calculator:
 - Weight of grain (Problem with mass conversion)
 - Grain Weight (Problem with mass conversion)

**Comment by mikfire** [comment]
Thanks!

This is really frustrating, because I know I've fixed many of these. I just need to find the branch. Include the Mash Editor window too.

**Comment by mikfire** [comment]
Ok. The mass conversion problems are the result of the resetting of the default unit from kilograms -> grams. I had fixed that one, but then broke it. I will have to find a better fix this time.

I am tempted to convert the other fields to BtGenericEdit, but need to consider side effects.

**Comment by mikfire** [comment]
The mass conversion had been previously fixed, but I hadn't actually made the pull request. I just did that.

**Comment by theophae** [comment]
Cool ! One less problem.
You are planning for fixing the problem of the field which need to have a fixed unit ?
Will you had a way to force the display unit keeping the possibility of entering the value in another unit for it to be converted (for example entering a SG gravity which will be converted into Plato), or only set these fields as generic ?

**Comment by mikfire** [comment]
All better -- if you can call the FSM weeps request "better". The resolution is split over three pulls. Combine all three to get what works. I think they are mostly orthogonal.

**Comment by theophae** [comment]
Cool ! This is quite what I had in mind.
Looking at the commit, I didn't see a change for the case when the field is erased. Until now, this result is filling the field with a null value. I suspect it comes from the brewtarget::toDouble() method which returns 0.0 if the regex fails. it may be a good idea to check if the field is empty first.
