### ISSUE TITLE
consider alternate ABV calculation method

### ISSUE THREAD

**Issue by knifewine** [Brewtarget/brewtarget#48]
I could be misinformed, but it seems the ABV calculation method used in brewtarget is less accurate for higher gravity beers. For a large barleywine this accounts for 1%+ discrepancy in calculated ABV.

Using the standard method my OG/FG of 1.098 works out to about 9.9%
If I calculate using the "alternate" method which is reputed to have better accuracy on higher gravity beers I arrive at 11%.

My source on this information is http://www.brewersfriend.com/2011/06/16/alcohol-by-volume-calculator-updated/

btw, thanks for great software, and Cheers!

**Comment by rocketman768** [comment]
We should do this. New equation in-line for ease of reference:

    ABV =(76.08 * (og-fg) / (1.775-og)) * (fg / 0.794)

**Comment by theophae** [comment]
If this formula is better, I can't see any reason not to implement it. It is really painless to do it.
