### ISSUE TITLE
Saving a "note" to a the dated tab causes application to crash

### ISSUE THREAD

**Issue by dschwilk** [Brewtarget/brewtarget#483]
Hello,

I built and installed (as .deb) the current development version. I had to fool around with the dependencies for the package but otherwise no problem.  I built it rather than installing the released 2.3.1 because I had trouble with the mash schedule part in 2.3.1 and saw that some work had been done in that area.

I ran into a problem, however. When I tried to enter a note regarding the brewday (under the recipe version that shows as a folded item and is created when I clicked "Brew It!"), the program crashes as soon as it tries to save the note (when I move focus to another tab, etc). If the note text is "a_note" the error is

The application encountered a fatal error.
Error message:
Could not update brewnote.notes to a_note: UPDATE brewnote set notes=:value where id=1  Parameter count mismatch

I also just noticed while recreating this that the "Recaclulate eff" context menu item on the same recipe/brewdate results in nonsense numbers (efficiency over 1000 % although original calculations before clicking "Recalculate eff" look close to my own.

On Kubuntu 20.04 LTS.

**Comment by mikfire** [comment]
Uh. That's not good. You sort of have two choices.

Assuming you didn't change your data directory, the best option is probably to do this:
```bash
sqlite3 ~/.config/brewtarget/database.sqlite
sqlite> alter table brewnote add column notes text default '';
sqlite> exit
```
If you changed your data directory, the path will be different but the command is the same.

There's a PR that will fix this issue in the default database. You caught this bug right in the middle of me causing it, finding it and fixing it.

**Comment by dschwilk** [comment]
Thanks!  Oops, that's what comes from using the development branch :).  But this way I hope I do catch bugs in the future, and not just those already found.

Thanks for your work!

**Comment by mattiasmaahl** [comment]
Is this still an issue after latest merge? can we close?
