### ISSUE TITLE
dpkg -i deb throws up errors - old dependenices listed as required

### ISSUE THREAD

**Issue by padraic7a** [Brewtarget/brewtarget#489]
Hi, I am trying to build on Ubuntu 20.04. No problem with these steps:

```
$ mkdir brewtarget-build
$ cd brewtarget-build
$ cmake /path/to/brewtarget-src
$ make
$ make package
```

When I get to ``` $ sudo dpkg -i brewtarget_2.4.0_x86_64.deb``` it throws up a bunch of errors:

```
pkg: dependency problems prevent configuration of brewtarget_2.4.0:
 brewtarget_2.4.0 depends on libphonon4 (>= 4:4.2.0); however:
  Package libphonon4 is not installed.
 brewtarget_2.4.0 depends on libqt4-dbus (>= 4:4.5.3); however:
  Package libqt4-dbus is not installed.
 brewtarget_2.4.0 depends on libqt4-network (>= 4:4.5.3); however:
  Package libqt4-network is not installed.
 brewtarget_2.4.0 depends on libqt4-svg (>= 4:4.5.3); however:
  Package libqt4-svg is not installed.
 brewtarget_2.4.0 depends on libqtwebkit4 (>= 2.3.4.dfsg-9.1); however:
  Package libqtwebkit4 is not installed.
 brewtarget_2.4.0 depends on libqt4-xml (>= 4:4.5.3); however:
  Package libqt4-xml is not installed.
 brewtarget_2.4.0 depends on libqtcore4 (>= 4:4.6.1); however:
  Package libqtcore4 is not installed.
 brewtarget_2.4.0 depends on libqtgui4 (>= 4:4.5.3); however:
  Package libqtgui4 is not installed.
 brewtarget_2.4.0 depends on phonon (>= 4:4.5.2); however:
  Package phonon is not installed.

```

Full paste at https://pastebin.com/6f5FvtET

The deb builds and installs fine so I guess it's not a big issue but listing the out of date packages is confusing.

**Comment by mikfire** [comment]
I am working on this and should have something available soonish

**Comment by mattiasmaahl** [comment]
I have a fix ready for this, if you want it. @mikfire 
I'll create a PR for it.
also, when installing the package, use apt install ./brewtarget_2.4.0_x86_64.deb, this will ensure dependencies are installed as well.

**Comment by mikfire** [comment]
I would prefer the changes to be made against the proper packaging branch, to be honest. I am not quite sure what the intent was previously, but I really do not want to track these files in two places. We should get rid of one of them, or do something really clever like a sub-project.

**Comment by mattiasmaahl** [comment]
ok, I'll look into it, but if I remember correctly the dependencies have to be correct in the development source for the packaging to work properly, there are dependencies listed also in the packaging branch, but those are for the packare reference.
I may have misread or misunderstood this workflow but I will look into it thoroughly and revert, although the above PR is necessary to build the .deb package from source and then install it.

will revert with my findings at a later time.

**Comment by xzfantom** [comment]
@mattiasmaahl did you discover smth?
As far as I understand there is two ways to build packages for debian - with target package (uses CMake plugin CPack) and with external utility dpkg-buildpackage. They are independent and looks like result is pretty much the same. The only problem is that if we change smth, we should update two places - CMakeLists.txt for CPack and [debian-packaging](https://github.com/Brewtarget/debian-packaging) for second way.
Did I get it right?

**Comment by matty0ung** [comment]
This might be heresy, but do we really need https://github.com/Brewtarget/debian-packaging?  If we can accomplish the same thing with CMake then it sounds simpler than having a tiny extra repository just for Debian packaging.

**Comment by mattiasmaahl** [comment]
Good day folks!
Well, first off, @xzfantom, sorry I have not had the time to look into that to any extent I'm afraid. First there was Christmas and then I've had a new born at home, so sleep has been a rare commodity as of late!

As for the Debian-package Repo, There are settings and package information set in that repo specific to the .deb package that needs to be there when publishing the files. 
And yes, you can build a .deb from Cmake. That is what the debian-package repo does as well only adding a few details for the packaging to Debian/Ubuntu package distributions. @mikfire may have more info on the matter, but I believe that if you want to release the software in Debian/Ubuntu package managers it needs to be of a specific format. And as Always, I may be wrong! 😊

**Comment by matty0ung** [comment]
Thanks for quick reply @mattiasmaahl.  Hope all is going well with your new arrival!

It would be nice if we could get CMake to do everything necessary for Debian/Ubuntu so we can absorb debian-packaging back into brewtarget.  This would avoid having to maintain same/similar thing in two places as @xzfantom says.  But, of course, I don't know if this would turn out to be easier said than done. :smile:

**Comment by mattiasmaahl** [comment]
@matty0ung, Maintaining 1 is always easier than 2, but we have to take into account that there is also the RPM-build that has it's own set of package information that needs to be included in the package.
But as I see it there is a lot of overlapping of information, such as Changelog, maintainers list, source package and so on.
I do agree that we could have all in one repo, but I don't have all the background to why there are separate repos for packaging. That was set up by the original author waay before my time int this project.
The beauty is that we can now have a discussion to get to where we now want to be, but  I would like to have @mikfire opinion on this as well.

**Comment by xzfantom** [comment]
@mattiasmaahl I do understand you very good) I just got some time for side projects and my son is 1 year and 9 months. Just was curious if you had discovered smth before.
Right now deb package with CPack throws a lot of errors when checked with lintian:

_~/brewtarget/build$ lintian --pedantic brewtarget_2.4.0_x86_64.deb_
```
E: brewtarget_2.4.0: bad-package-name
E: brewtarget_2.4.0: debian-changelog-file-missing
E: brewtarget_2.4.0: dir-in-usr-local usr/local/bin/
E: brewtarget_2.4.0: dir-in-usr-local usr/local/share/
E: brewtarget_2.4.0: dir-in-usr-local usr/local/share/applications/
E: brewtarget_2.4.0: dir-in-usr-local ... use --no-tag-display-limit to see all (or pipe to a file/program)
E: brewtarget_2.4.0: file-in-usr-local usr/local/bin/brewtarget
E: brewtarget_2.4.0: file-in-usr-local usr/local/share/applications/brewtarget.desktop
E: brewtarget_2.4.0: file-in-usr-local usr/local/share/brewtarget/default_db.sqlite
E: brewtarget_2.4.0: file-in-usr-local ... use --no-tag-display-limit to see all (or pipe to a file/program)
E: brewtarget_2.4.0: no-copyright-file
E: brewtarget_2.4.0: unstripped-binary-or-object usr/local/bin/brewtarget
W: brewtarget_2.4.0: extended-description-line-too-long
W: brewtarget_2.4.0: extended-description-line-too-long
W: brewtarget_2.4.0: file-in-unusual-dir usr/local/bin/brewtarget
W: brewtarget_2.4.0: file-in-unusual-dir usr/local/share/applications/brewtarget.desktop
W: brewtarget_2.4.0: file-in-unusual-dir usr/local/share/brewtarget/default_db.sqlite
W: brewtarget_2.4.0: file-in-unusual-dir ... use --no-tag-display-limit to see all (or pipe to a file/program)
W: brewtarget_2.4.0: non-standard-dir-perm usr/ 0775 != 0755
W: brewtarget_2.4.0: non-standard-dir-perm usr/local/ 0775 != 0755
W: brewtarget_2.4.0: non-standard-dir-perm usr/local/bin/ 0775 != 0755
W: brewtarget_2.4.0: non-standard-dir-perm ... use --no-tag-display-limit to see all (or pipe to a file/program)
```
May be it can be fixed some way, but no such problems with **dpkg-buildpackage**

**Comment by mattiasmaahl** [comment]
@xzfantom did you run the lintian against develop or 2.4.0/stable branch? because develop is throwing a lot of error I know, but last I tried, the 2.4.0 branch it worked?

**Comment by xzfantom** [comment]
It was branch created from #515 
I created GitHub Action file to test autobuild. In autobuild I use debian-packaging [develop.yml](https://github.com/xzfantom/brewtarget/blob/feature-gha-pr515/.github/workflows/develop.yml). On my linuxbox - make package. It's all on same code base. Lintian gives no mistakes in **autobuild**, but gives errors on **make package** build. I'll check stable branch, too.

**Comment by xzfantom** [comment]
Nope, lintian don't like packages made with CPack, just checked on stable/2.4.0

**Comment by mattiasmaahl** [comment]
ok, did you also try to make the project from the Debian-Package repo?

**Comment by xzfantom** [comment]
If you mean stable/2.4.0, I didn't check it with autobild. I think it's Ok, because #515 is Ok with Debian-Package.

**Comment by mattiasmaahl** [comment]
well, I need to investigate further into the workings of dpkg-buildpackage to take this discussion further. 
But anyhow, I do believe we can make a sub-directory structure where the different requirements for the package builders are kept, that could work. i.e. packages/debian, packages/win and packages/rpm. that would include them in the same repo but at the same time keep them somewhat separate from the source.
But I think that the separate repo was created to have a "cleaner" interface, independent from the development of the app, so that the packaging settings and package-specific files don't get included in the source-package for the distribution package.
Does that make any sense at all??  🤔or am I talking myself into a quadratic-circle??

**Comment by xzfantom** [comment]
It's not an easy question. Mostly question if architecture and different  decisions here have their pluses and minuses. In my opinion one repo is better - we can bring atomic changes in functional, add new dependencies and update manual with one PR and everything is good and consistent. Text files don't use much space and if create some clean directory structure it will keep project clean, too.

**Comment by mattiasmaahl** [comment]
I absolutely agree with you @xzfantom.
@mikfire, would you kindly give your opinion on the matter, as you have been in this project the longest?

**Comment by xzfantom** [comment]
I did some investigation about making deb & rpm by "make package". It looks like it's possible to create ideal deb-package and maybe rpm-package, too. Only problem is that you have to include such files like changelog.Debian in both packages (as you can't choose what to install for one package and not to install for another).
Probably, it's ok to build packages for dev builds but use appropriate repo for release packages.

**Comment by matty0ung** [comment]
I had a lot of fun(‡) getting `make package` to work for Deb, RPM, Windows, etc the 3.0.0 build, so I think we can close this ticket now.

‡ for some masochistic definition of the word "fun"... :smiley:
