### ISSUE TITLE
Brewtarget should log its version number

### ISSUE THREAD

**Issue by matty0ung** [Brewtarget/brewtarget#495]
When Brewtarget starts up, it logs "INFO : Starting Brewtarget."  It would potentially help debugging user problems if it could also log version and platform info.  This is partly in case the user doesn't remember which version is installed and has a problem that prevents them from accessing the "About" menu.  But it's also ultimately simpler to have essential info in the log file (if most users are able and willing to submit the log file with a bug report) as it saves having to ask the user for "standard" additional info.

**Comment by mattiasmaahl** [comment]
This issue was closed with PR#496.
Closing it.
