### ISSUE TITLE
 Backup Database - can't choose filename, and clicking Cancel gives error

### ISSUE THREAD

**Issue by matty0ung** [Brewtarget/brewtarget#497]
Per https://bugs.launchpad.net/brewtarget/+bug/1109751 and https://bugs.launchpad.net/brewtarget/+bug/1372087, there are a couple of issues with the database backup dialog:
 * You can currently only choose a backup directory, not a filename - which is annoying if you want to make several manual backups and keep them in the same directory
 * If you select manual backup and then click cancel, you get an error message

Proposed fixes for both these issues in https://github.com/Brewtarget/brewtarget/pull/492

**Comment by mattiasmaahl** [comment]
This issue resolved by PR #492, closing, can reopen if necessary.
