### ISSUE TITLE
Efficiency and boil time not sticking

### ISSUE THREAD

**Issue by rocketman768** [Brewtarget/brewtarget#5]
@mikfire says:

Changing either the boil time or the efficiency on the main panel doesn't seem to do anything. Neither the volumes or the OG change, respectively.

Also, changing the amount of fermentables in the recipe will reset the two fields to their defaults. This is almost certainly a side effect of MR#99.

**Comment by IcanBENCHurCAT** [comment]
Can be closed

**Comment by mikfire** [comment]
I thought I fixed this at some point?

**Comment by IcanBENCHurCAT** [comment]
@mikfire it is in source, but not release. a few of these issues are

**Comment by rocketman768** [comment]
I just copied some open issues from Launchpad to Github so we didn't miss them as we moved.
