### ISSUE TITLE
Double vision when importing a recipe

### ISSUE THREAD

**Issue by mikfire** [Brewtarget/brewtarget#514]
This is a display layer bug, as restarting brewtarget makes the duplicate entries in the tree go away. This suggests we are signaling twice when we should be signaling once. I suspect this is related to the 

To reproduce:
1. Export a recipe;
2. Modify the XML to change the name, just for clarity;
3. Modify the mash (if required) to have a name -- I need to fix that;
4. ![See double](https://www.dropbox.com/s/dpyypatu03kc8iw/doublevision.png?dl=0)

**Comment by matty0ung** [comment]
I couldn't get the "See double" link to show me anything.  Does this problem still occur with https://github.com/Brewtarget/brewtarget/pull/515?

**Comment by matty0ung** [comment]
Closing this on the assumption it's now fixed (as there have been a lot of changes in the code that imports recipes).  Of course, as always, please reopen if bug is still occurring in latest code.
