### ISSUE TITLE
QT5 minimal version

### ISSUE THREAD

**Issue by xzfantom** [Brewtarget/brewtarget#521]
In CMakeLists.txt QT5_MIN_VERSION is declared as 5.3. It's outdated value and current project can't build with QT older than 5.10.
Looks like we should update this value to more reasonable one.
And one more thing - in Ubuntu 18.04 LTS in packages QT5 is [5.9.5](https://packages.ubuntu.com/bionic/qt5-default). Do we need to support it?
@mikfire

**Comment by matty0ung** [comment]
From the dates at https://en.wikipedia.org/wiki/Qt_version_history it seems like 5.12 would be a sensible minimum.
OTOH, if a lot of end users are likely to already have old versions of Qt installed, maybe we should just static link against a fixed version of Qt?

**Comment by xzfantom** [comment]
I think that as far as we don't use features of new QT releases we should use as low version as we can. For example in current Debian Buster QT is 5.11, so using 5.10 will allow this people to use BT with no additional effort. As for me, I'd prefer static linking only if using new QT version will bring us real benefits. 
I'm not good in QT development, so I don't have reasonable opinion here.
Maybe somebody else can say something on this topic.

**Comment by matty0ung** [comment]
Yes, you're right we should make things as easy as possible for users.  And dynamic linking is generally preferable for lots of reasons.  I guess I was just thinking about static linking as a fall-back if we can't rely on a new enough version of Qt being installed.  Eg, AIUI, we need at least 5.11 for High-DPI Support, so I'd worry a bit about anything older than that.

As an aside, I can see a few places in the code that seem to do _compile-time_ checks against Qt version (`grep -ir "QT_VERSION" ../src` returns 11 results), but I haven't dug into any of these so I don't know if any of the should cause concern.

**Comment by xzfantom** [comment]
> As an aside, I can see a few places in the code that seem to do _compile-time_ checks against Qt version (`grep -ir "QT_VERSION" ../src` returns 11 results), but I haven't dug into any of these so I don't know if any of the should cause concern.

It's to hide some stuff deprecated in new QT versions if new feature is not introduced in old version. Should be no problem, most checks are with 5.15, some with 5.13.

**Comment by matty0ung** [comment]
Ah, OK, cool.

**Comment by xzfantom** [comment]
Looks like we have some consensus about QT 5.9.5 in LTS Ubuntu 18.04. Some discussion in this pr #550.
