### ISSUE TITLE
App initialization at start

### ISSUE THREAD

**Issue by xzfantom** [Brewtarget/brewtarget#522]
While I was playing around with windows builds I found some things that in my opinion we can make a little different.
Most annoying problem with windows installer NSIS is that we use 2 outdated plugins there. They are only x32 and were not supported for years. They are used for finding old database from previous version and saving info about it, so during app start we get this db and do upgrade stuff with it. Our app supports PostgreSQL now, too. So my thought is to move all this stuff from installer to main application like this:

- App starts
- If we can't find any saved config, we decide that it's first start, save default config
- If no info in config about DB, provide dialog window with some choice: create new db, connect to PostgreSQL or use existed db
- If we there is info about db in config, but we can't connect to it we can provide same dialog as above

So it makes app more robust at startup and installer script easier. And this code is more universal, not only for windows.

**Comment by matty0ung** [comment]
AIUI there is already a bunch of stuff in the app about doing DB schema upgrades (in DatabaseSchemaHelper) so perhaps the logic belongs there?

**Comment by xzfantom** [comment]
It's mostly UI thing. AFAIK we have all code needed, just rearrange it a little bit. Installer asks to point to old db and saves this info in config, BT uses this info at startup and does all convertation stuff, etc. I just wont to throw out this part from installer script and make BT handle it itself. So installer just unpack and copy files in folder, no more logic there.
Now if PostgreSQL is used and no connection to it, BT just keep asking for password. If no sqlite file found BT just silently creates an empty one and so on.
I propose to change this a little bit - if we foind no db file/connection to PostgreSQL, we can offer user to choose what to do with it - create new or open file in new location. Also we can just open Options window and ask to configure it there, so we don't need new entities. After db is opened DatabaseSchemaHelper checks it's version and updates if needed - it works now.
It will make BT portable, too. In Windows you can copy folder with BT on new machine, start it and it should just work.

**Comment by matty0ung** [comment]
We are now 64-bit on Windows, and the packaging code was completely rewritten, so I'm going to close this.  If you're hitting the same problems however, please reopen.   Equally, if you hit other install problems, please don't hesitate to raise a new ticket.
