### ISSUE TITLE
Enable GitHub Discussions?

### ISSUE THREAD

**Issue by matty0ung** [Brewtarget/brewtarget#528]
What do people think about enabling GitHub Discussions (https://docs.github.com/en/discussions/quickstart) for Brewtarget?  We already have GitHub for bug tracking / feature requests, so why not enable the discussion board too as a replacement for the Google Groups forum that nobody uses any more (https://groups.google.com/g/brewtarget-help).  It would also be a place for devs to discuss general issues that are not related to an individual bug/feature ticket.

**Comment by xzfantom** [comment]
I think it's good idea. I have some ideas, but don't feel like open issue for them and discussions looks like good place for them.

**Comment by mattiasmaahl** [comment]
I agree that it's a good idea, 
I don't think that bouncing ideas and having a discussion regarding a suggestion belongs in the Issues-tab.

**Comment by matty0ung** [comment]
Cool.  I think we need @mikfire to enable it so, if he agrees, maybe he can do it on his next visit.

**Comment by mikfire** [comment]
Done, but I left the welcome message at its fairly awful default. If somebody wants something more clever, I will be more than happy to change it around. I am just mostly awful at writing content.
