### ISSUE TITLE
Graphics on new install glitched

### ISSUE THREAD

**Issue by dozer7308** [Brewtarget/brewtarget#537]
New install of Brewtarget on Windows. Resulted in the style graphs being bunched. Ideas on how to fix? Installed on 2 other machines in the past with no issues. 
![Screenshot 2021-04-02 083215](https://user-images.githubusercontent.com/81784454/113367201-fda43100-938d-11eb-9055-df474e2e8311.png)

**Comment by matty0ung** [comment]
My guess would be that this is because you have a high DPI display.  If so, then the problem is already largely fixed in the dev branch (see https://github.com/Brewtarget/brewtarget/pull/502).

**Comment by dozer7308** [comment]
That was it - with thanks @matty0ung
