### ISSUE TITLE
Incorrect balloon comments for Strike Temp and Final Temp

### ISSUE THREAD

**Issue by clmoore3rd** [Brewtarget/brewtarget#54]
The balloon comments for Strike Temp and Final Temp are incorrect on the Brew It! tab.  This is for the 64bit Linux package brewtarget_2.1.0-1_amd64.deb. 

They read:
Strike Temp "Temperature of mash after dough in"
Final Temp "Temperature of mash before mash out"

According to the online manual the balloon comments should be:
Strike Temp "The temperature of your strike water before dough in"
Final Temp "The temperature of your mash after dough in"

**Comment by janjachnik** [comment]
I think the terms are ambiguous.

It might be clearer to have 3 temperatures:

1) Temperature before dough in (strike water temperature)
2) Temperature after dough in
3) Final mash temp (before mash out)

**Comment by clmoore3rd** [comment]
With those three temperatures it should be possible to calculate actual specific heat of the mash tun, right?  So where the value in the equipment profile is feed forward to calculate strike water temp to get mash-in temp, having an actual value calculated from brewday measurements would give the user feedback to dial in the equipment profile:)

My approach was to iterate the specific heat value so the mash wizard calculator (great feature BTW) closely matched actual results from previous brew sessions.

**Comment by eltomek** [comment]
Are the _Strike temp_ and _Final temp_ fields really needed/usable on the `brewNoteWidget`? The _Strike temp_ value (unless the brewer decided else, but the calculated values are what he uses Brewtarget for) is the one that we have in the _Mash Step'_s _Infuse temp._ field. If he decided to use different strike temp. he could store it simply in the _Notes_ field. I have the same concerns regarding  the _Final temp_ (temp. of mash before mash out). 
Of course, this may be some valuable parameter for the brewer but until it is used to calculate anything in Brewtarget it is a redundant data field that as a result contributes (as a practice) to make software overcomplicated and unfriendly to new users.

**Comment by mikfire** [comment]
The idea of the strike temp field was to allow the user to record the temperature they actually heated the strike water to -- I am sometimes distracted and sometimes (maybe) strike a little hotter than expected. Recording this sort of information is exactly what I wanted the brewnotes for -- so the little deviations that just happen on a brewday can be recorded.

The intent of the Final temp was a dual purpose, depending on how the user wanted to use it. The first idea was to give them a place to record what the *actual* mash temp was. The software is using theoretical models for the temperature calculation, which will almost always be a little off from reality. By recording the actual mash temp, the user would be able to dial brewtarget in for their specific system. Alternately, they could use it to record the temperature of the mash at the end of the mash step. Again, given enough entries over time the user could get a decent idea of how their mash tun kept heat.

Hmm. One thing I've always wanted to try is to allow the user to "customize" the display -- remove fields, etc. Maybe this would be a good place to figure out how to do that. We can preserve the current interface for those who do use the fields, and those who don't want to can remove them.

**Comment by eltomek** [comment]
I understand your point @mikfire, I think of a way to logically separate information fields from data fields (by data fields I understand values that take part in some calculations). When I first played with these values I was wondering what they impact (in contrast _SG_ and _Volume_ fields do impact i.a efficiency values) and was a bit concerned to see no effect.

**Comment by kapinga** [comment]
Since this is apparently a blocking bug for the 2.4.0 release, I vote that we clarify the tooltips and PDF to be consistent with each other and call it a day. Additional fields might be nice, but adding them requires editing the database schema and adding in yet more UI elements.

The relevant database fields are called `strike_temp` and `mash_final_temp`. I vote that we update the labels (and online manual) to be their intuitive meanings:

- Strike Temp: "Temperature of the strike water before dough in"
- Final Temp: "Temperature of the mash before mash out"

We can think about what additional fields should be added in a future release.

**Comment by malavv** [comment]
This fix was pulled onto v2.4 stable. I assume this bug is fixed.
