### ISSUE TITLE
Boil time for hops is shown in whole hours (90 min -> 2h)

### ISSUE THREAD

**Issue by Alge** [Brewtarget/brewtarget#560]
When adding hops, the time is shown rounded to 2 hours instead of 1.5.

When I enter the time:
![Screenshot from 2021-04-14 13-51-48](https://user-images.githubusercontent.com/7383768/114706101-d869d800-9d28-11eb-90a9-030119accbe6.png)

After I press enter:
![Screenshot from 2021-04-14 13-51-53](https://user-images.githubusercontent.com/7383768/114706100-d7d14180-9d28-11eb-997c-b1e74b71b806.png)

On the preview:
![Screenshot from 2021-04-14 13-52-41](https://user-images.githubusercontent.com/7383768/114706099-d738ab00-9d28-11eb-9047-9fdca43b1cb5.png)

**Comment by xzfantom** [comment]
Hello! What version do you use? Try download latest build from Actions: https://github.com/Brewtarget/brewtarget/actions and check.
![изображение](https://user-images.githubusercontent.com/5746986/114750570-cc980900-9d5c-11eb-965f-10d42e5d6975.png)
Be aware it's betta, but close to release.

**Comment by Alge** [comment]
I'm using 2.3.1 downloaded yesterday. I'll try out the beta!

**Comment by Alge** [comment]
Confirmed that it works in the beta! Always nice when issues are solved before reporting ;)

![Screenshot from 2021-04-15 09-18-33](https://user-images.githubusercontent.com/7383768/114829649-a3629180-9dcb-11eb-8e98-44ff3abfe284.png)

**Comment by Alge** [comment]
Found another place where the time is rounded up!
Using 2.4.0, when showing the brewday print preview the time is still shown as 2 hours
![Screenshot from 2021-05-06 16-58-17](https://user-images.githubusercontent.com/7383768/117320388-78c89d80-ae8c-11eb-92a2-eaba42a7bc95.png)

**Comment by matty0ung** [comment]
I'm getting minutes rather than hours for my fields in print preview, but it might be that the recipe I'm testing with doesn't have the problem fields.  Could you export your recipe to XML and then add that XML file to this ticket?

**Comment by Alge** [comment]
Sure!

Couldn't add the file in the comment, so here's a pastebin link: https://pastebin.com/XMV5xvwD

**Comment by Alge** [comment]
and here is a complete picture of the print preview:
![Screenshot from 2021-05-07 13-45-23](https://user-images.githubusercontent.com/7383768/117445055-89cfe800-af3a-11eb-85d2-6c481e2bd76c.png)

**Comment by matty0ung** [comment]
Thanks, that's very helpful.
The good news is I already did some refactoring that fixed this bug in Brewken (my downstream project that, ultimately, will add Microbrewery features to Brewtarget).  I think I remember where the relevant code was and I just need to backport it to Brewtarget.  Watch this space. :)

**Comment by Alge** [comment]
Perfect!

**Comment by matty0ung** [comment]
OK, so this took slightly longer as I couldn't resist tidying up UnitSystem and its subclasses.  I think we saved a couple of thousand lines of code (at least that's what git says), so it feels like a worthwhile refactoring!

Looks to me like it fixes this problem, but would welcome any further testing.  Hopefully any other bugs of this sort will now be simpler to find/fix.
