### ISSUE TITLE
Xerces-C and Xalan-C is not included in NSIS Installer

### ISSUE THREAD

**Issue by mattiasmaahl** [Brewtarget/brewtarget#567]
So when compiling the NSIS installer and installing Brewtarget on a new machine, you cannot run brewtarget due to missing xerces and xalan libraries.

We need to include those DLLs like we include the QT-DLLs in the install tree.

I'm working on a solution for this as it seemed as a simple fix at first, i.e. just include the files! but no...
when Cmake goes out to find the libraries it finds the ones named .dll.a files, these won't do, bacause Windows.

I will continue to try and find a fix for this. but if any of you guys have any tips or trix feel free to point me in the right direction. 😄

**Comment by matty0ung** [comment]
It's been a while since I did stuff on Windows, but I guess worst case we could just link against the static libraries (which AIUI is what the dll.a. files are) - if, of course, we have them.

**Comment by xzfantom** [comment]
It's strange. Are you compiling in MSYS2 environment or in VS?

**Comment by mattiasmaahl** [comment]
@xzfantom I'm compiling with mingw64 compiler and MSYS libraries. (in Visual studio Code) (msvc was giving me to much trouble as of late)
thing is, I have both the dll and dll.a installed with MSYS and when Cmake goes to find the libraries is finds the lib\xxx.dll.a files instead of the bin\xxx.dll files.
this is a "feature" of cmake since a few versions back from what I can find.

**Comment by xzfantom** [comment]
Still strange situation. Are CMakeLists.txt in root and src folder updated to latest develop version? It should show in terminal all shared libs when making package:
![изображение](https://user-images.githubusercontent.com/5746986/114992465-75e91700-9ea3-11eb-8dfa-6c8ec765f3c2.png)

**Comment by mattiasmaahl** [comment]
well, yes all updated to the latest version, but for some reason it does not list xalan/xerces on my machine. Now I'm beginning to think there is an issue with my setup... need to check that

**Comment by xzfantom** [comment]
Is there msys/mingw64/bin in your PATH variable?

**Comment by mattiasmaahl** [comment]
Yes, it is. but I'm not using the Msys-supplied mingw compiler & cmake, I'm using the QT-supplied mingw compiler & cmake. Maybe that has something to do with it.
I can try to run the package build with the msys/mingw instead. I'll revert with my findings.

**Comment by mattiasmaahl** [comment]
Yes, can confirm, If you run all tools from the msys container you get all dependencies included in the package. although, you were right on that the Nsis has to be 32 bit because of the plugins.
BUT... When I install this package on a fresh Windows 10 machine I get:
![QT-Error](https://user-images.githubusercontent.com/1370239/115019232-91631a80-9ec1-11eb-80ca-805db666922d.JPG)
So now I have to figure out what is happening there. any thoughts?

**Comment by xzfantom** [comment]
Curiouser and curiouser
can you attach package here?

**Comment by mattiasmaahl** [comment]
You can download the package I created from this link: [Owncloud-maahl.com](https://owncloud.maahl.com/index.php/s/u3NZ6t2OmWX1OX5)

**Comment by xzfantom** [comment]
QT libs in distrib are of different size than I have. Other libs looks like the same size as mine.
The problem can be that if you have stand-alone QT distrib in Path and MSYS2 QT distrib in path - installer can mess them up.
Or I don't know what magic is here)

**Comment by mattiasmaahl** [comment]
I also thought that it could be "dual" Qt install that messed everything up, så I removed all references to the non-msys one and restarted all programs and command prompts to have all fresh references to ONLY Msys libraries. And I believe that I only have 64-bit libraries installed on my system, with the exception from Nsis that is required to be 32-bit, but that one collects the 64-bit libraries according to the build log.
![bild](https://user-images.githubusercontent.com/1370239/115028159-3a634280-9ecd-11eb-9bc3-ab117558306d.png)

**Comment by xzfantom** [comment]
Do you build in VSC? Or in terminal? 
As for me it looks like there is 32 and 64 bit stuff in one build.
If you plan create installer with nsis, I'd suggest do all things in 32bit environment yet.
I plan to get rid of this plug-ins, but there should be some code added to application, I'm discovering yet what to do.

**Comment by mattiasmaahl** [comment]
I build in VSC when I am coding and testing. But the package och built in a terminal/command prompt as VSC don't recognize the "package" target automatically.
Question though, the Github Action, is that compiling in 32- or 64-bit version of the software? as I discussed with Mikfire a while ago we decided to move to a 64-bit only build/release ditching the 32-bit version all together. 

moving forward, I think it is a good idea to move away from the plugins as well, and move to a all 64-bit build. I'll poke around in the code and see what I can come up with and lets continue this at a later point.

**Comment by xzfantom** [comment]
This plugins are used only to get folder were previous version of base is located. Maybe it's safe to delete this code from script and nothing bad could happen, but better check clean install and upgrade from previous version.
I'm studying startup flow to see if we can show options dialog in case if some checks are failed instead of panic and exit. I'm not experienced in c++ and qt, so it takes some time)

**Comment by mattiasmaahl** [comment]
This issue is no more. I will close. Problem was i was using the wrong compiler/linker.
