### ISSUE TITLE
Right-click on top level Recipes in treeview Segfaults with null pointer

### ISSUE THREAD

**Issue by mattiasmaahl** [Brewtarget/brewtarget#609]
So, I was looking into issue #10 and found that when you right click on the top-level, *[image 1](#image_1)*, item in Treeview, namly 'Recipes', Brewtarget crashes with a Segfault, *[image 2](#image_2)*. My theory is that due to the fact that this is not a recipe the below *[image 3](#image_3)*.
I'm not all read up on @mikfire code regarding the recipe versioning and locking, but a null-check might be in order.
Maybe a Check if it was the top-most item clicked?

#### Image 1
![bild](https://user-images.githubusercontent.com/1370239/125035265-43158000-e09a-11eb-8f64-81cb1fb94e06.png)

#### Image 2
![bild](https://user-images.githubusercontent.com/1370239/125035377-66d8c600-e09a-11eb-9bcc-6d6511e339ec.png)

#### Image 3
![bild](https://user-images.githubusercontent.com/1370239/125036487-bc61a280-e09b-11eb-8098-a2ff6fb54895.png)

**Comment by mattiasmaahl** [comment]
I may have a fix for this coming soon.

Ugly it may be, but fix the issue it will. 😉

**Comment by matty0ung** [comment]
The null check you suggested seems to work for me when I added it to my local copy of the code.  But I didn't dive into the root cause, so maybe @mikfire has something more elegant.

**Comment by mattiasmaahl** [comment]
Yes, null-check works, but it will present a menu that will do a bunch of stuff that you can't do on that item. I'm figuring out how to alter the menu to only enable the things available. should have a fix up in a PR today.

**Comment by matty0ung** [comment]
Ah, OK, cool.
