### ISSUE TITLE
Why Xerces & Xalan?

### ISSUE THREAD

**Issue by treaves** [Brewtarget/brewtarget#625]
Is there an actual reason these two external libraries were used instead of the standard Qt XML processing?  Why increase dependencies?

**Comment by matty0ung** [comment]
If you look at line 50 of https://github.com/Brewtarget/brewtarget/blob/develop/src/xml/XmlCoding.cpp there is a comment that explains why we use these libraries.  The short answer is that XML support in Qt has been significantly reduced in the Qt6.0 release of December 2020.

**Comment by matty0ung** [comment]
Closing this, but please do re-open (or post in https://github.com/Brewtarget/brewtarget/discussions) if you have follow-up questions.
