### ISSUE TITLE
New MashStep doesn't get saved properly

### ISSUE THREAD

**Issue by matty0ung** [Brewtarget/brewtarget#628]
Adding a new mash step to an existing recipe, the mash step gets stored in the database but not associated with the mash, so it's disappeared next time you run the program.  Culprit is `NamedMashEditor::addMashStep()` which is directly calling `ObjectStoreWrapper::insert()` instead of `Mash::addMashStep()`, plus, `MashStep::setMashId()` doesn't use the same boilerplate as all the other setters, which means it's not calling down to the ObjectStore/DB layer.

Working on a fix.

**Comment by matty0ung** [comment]
Have made some progress.  Code is no longer crashing but still two problems on recipe import from XML:

- MashStep step numbers are not getting set
- Mash / MashSteps are not showing up in the UI until you restart Brewtarget

Will continue investigating!

**Comment by matty0ung** [comment]
Nearly there. Just have the MashSteps coming in backwards, which I know how to fix...

**Comment by mattiasmaahl** [comment]
Merged, closing.
