### ISSUE TITLE
Fixed efficiency

### ISSUE THREAD

**Issue by RSP1000** [Brewtarget/brewtarget#641]
Hello there  :)
I used to be able to change the value of the expected efficiency in the window composing a recipe. Now the value is fixed at 70% and cannot be changed. I'm using the latest version from git on linux. Does anyone else have a similar problem?.

Have a good one.

**Comment by matty0ung** [comment]
OK, I think I have a fix. `BtLineEdit::onLineChanged()` needs to `emit textModified()` in the event that the field does not hold a physical quantity.  It's a small change.  I'll do a patch either tonight or tomorrow morning.

**Comment by matty0ung** [comment]
Patch uploaded at https://github.com/Brewtarget/brewtarget/pull/642.  Awaiting review.
