### ISSUE TITLE
Brewtarget exit after clicking on...

### ISSUE THREAD

**Issue by ghost** [Brewtarget/brewtarget#649]
Hello :)

When you click on a long rectangle at base profile or target profie in the "water chemistry" tab without selecting any profile, default setting, brewtarget exit. In the log file or command line there's the following error message:
ERROR : ASSERT: "basePixelDistanceBetweenCircles > 0" in file /tmp/brewtarget-git_20220411_213e54c5/src/RadarChart.cpp, line 257  [RadarChart.cpp:257]

![brewtarget_water_chemistry](https://user-images.githubusercontent.com/102156551/166864041-decbb500-2b21-4e45-b8dc-396e44236cb2.png)

Regards

**Comment by matty0ung** [comment]
Thanks for the bug report.  Will take a look.

From a quick look:
 • The code that draws the radar chart on the water profile editor isn't liking the fact that it's being asked to draw a chart with no data.  (It can handle all the data being zero, eg when you create a new water profile.  But here we're trying to show a non-existent profile.)
 • In this case, it may be best for us to make default selections for the water profiles, on the grounds that it doesn't make sense for no profiles to be selected in a tool that's supposed to help you with mineral additions to one profile to mimic another.  (It's notable that, once you've selected a profile for Base or Target, you can't unselect it.)  Failing that, we could have clicking on blank "nothing selected" box just do nothing.

**Comment by matty0ung** [comment]
Sorry that "soon" turned out to be a while.  I have a one-line fix that prevents the crash, but I'm going to carry on looking a bit as there's some other behaviour that's not ideal.

**Comment by matty0ung** [comment]
This should be fixed in the latest release (https://github.com/Brewtarget/brewtarget/releases/tag/v3.0.1).  Please re-open if not.
