### ISSUE TITLE
register actual OG, FG and final volume, and calculate real IBU and efficiency

### ISSUE THREAD

**Issue by pbgapski** [Brewtarget/brewtarget#658]
Brewtarget calculates designed OG, FG, color, IBU and ABV from the recipe. 

I suggest adding optional fields to register actual measured values for OG, FG and final volume; with these, actual values for ABV, IBU and color can be calculated by Brewtarget, and real efficiency as well. This will provide a valuable log to allow for recipe improvement in future brews.

Thanks for this great brewing software!

**Comment by mikfire** [comment]
The feature you requesting is called a brew note. They are already implemented, but I hid the interface so well that it feels like I am the only person who knows they exist.

If you right click on a recipe in the tree and then select "Brew it!" you will create a brew note, which provides fields for various measurements taken through the brew day. It will also calculate your actual efficiencies. Finally, it offers a notepad for any thing you want to record that doesn't fit the fields -- I used to record water adjustments, for example.

The recipe will then show a "twisty" in the tree. If you expand the twisty, you will see all the notes associated with that recipe.

**Comment by pbgapski** [comment]
Now that you mentioned it, I found it. Basically perfect!!!

Thanks for the fast response!
