### ISSUE TITLE
LGPL-2.1-only and LGPL-3.0-only license text not shipped

### ISSUE THREAD

**Issue by penguinpee** [Brewtarget/brewtarget#664]
Hi. I've adopted brewtarget for Fedora recently. While updating to the latest release, I noticed that the license text for LGPL-2.1-only is not present in COPYRIGHT. That license applies to a single file: `images/backup.png`. The link mentioned in the corresponding commit now redirects to http://www.icon-king.com/, which has no licensing information on the site.

I'm not sure if the license still applies, but if it does, the license text needs to be added to COPYRIGHT as required by the license:

> and distribute a copy of this License along with the Library

I'm not a licensing guru, but I'm inclined to think that replacing the license for that file with GPL-3.0-only, which is already present, is valid:

> You may opt to apply the terms of the ordinary GNU General Public License instead of this License to a given copy of the Library. To do this, you must alter all the notices that refer to this License, so that they refer to the ordinary GNU General Public License, version 2, instead of to this License. (If a newer version than version 2 of the ordinary GNU General Public License has appeared, then you can specify that version instead if you wish.) Do not make any other change in these notices.
Once this change is made in a given copy, it is irreversible for that copy, so the ordinary GNU General Public License applies to all subsequent copies and derivative works made from that copy.

In that case simply listing it as GPL-3.0-only should suffice.

**Comment by matty0ung** [comment]
Thanks for this.  I think you're right that going with GPL3 is simplest, as that's already the licence for the rest of the code.

**Comment by penguinpee** [comment]
Actually the .png icons which have a dual license also require some attention. Though, I'm not sure if the LGPL-3.0-only text needs to be shipped, since there's a choice of license and CC-BY-SA-3.0 is being shipped.

I'm currently checking with other packagers, who have more experience with licensing questions.

LGPL-3.0-only does not allow you to apply another license, though.

**Comment by penguinpee** [comment]
LGPL-3.0-only text needs to be shipped. Since I was at it, I also added LGPL-2.1-only text and moved CC-BY-SA-3.0 text into its own file. License texts have been removed from COPYRIGHT to avoid (partial) duplication.

The feedback I got is in the [mailing list](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/GWENS52KNPBTMNM3VGNSKS7JHML3IQH4/).
