### ISSUE TITLE
Flags in language selection

### ISSUE THREAD

**Issue by penguinpee** [Brewtarget/brewtarget#675]
I just updated brewtarget to 3.0.2 for Fedora. I adopted the package after is was orphaned as a hobby project.

Clicking through the software as a very low level smoke test, I noticed some flags are missing in the language selection. These are:

- Estonian
- Basque
- Galician
- Hungarian
- Latvian
- Serbian
- Turkish

Moreover, flags are displayed in a square shape, making some of them look odd. The Danish flag i.e. looks like an inverted Swiss flag.

![brewtarget_language_flags](https://user-images.githubusercontent.com/98259694/198669561-dd51df0f-71ca-42e8-80c9-2e6d76bb0e25.png)

**Comment by matty0ung** [comment]
Hmm, yes, good point.  It looks like 2:3 is the most usual ratio for flags (https://en.wikipedia.org/wiki/List_of_aspect_ratios_of_national_flags).  Hopefully this is an easy fix.  I'll have a look.

**Comment by matty0ung** [comment]
Fixed in 3.0.3.
