### ISSUE TITLE
Water Chemistry: Crash when selecting added salt name or amount

### ISSUE THREAD

**Issue by OWoolland** [Brewtarget/brewtarget#685]
Hello, I've been having a play with the water chemistry tool that has been added. It's looking really cool and really promising, thank you for the work on it.

I'm having trouble using the interface, receiving:

`munmap_chunk(): invalid pointer`

when selecting a salt name or amount on the Water Chemistry tool. I have attached a full backtrace [gdb.txt](https://github.com/Brewtarget/brewtarget/files/10095997/gdb.txt)

I attempted to chase the error out but not being super familiar with Brewtarget's source code, QT or more complex databases I may have been barking up the wrong tree. I got as far as finding that disabling this [line](https://github.com/Brewtarget/brewtarget/blob/develop/src/model/NamedEntity.cpp#L356) allowed the water calculator to proceed as I hoped but presumably wasn't a good idea for the software as a whole!

Having a look around in the database generated during compilation I notice that (for me) the Salt table appears to be empty.
![foo](https://user-images.githubusercontent.com/11718812/204083477-12325499-5a5a-45da-8eca-e3f166d0c7ff.png)
Could this be related?

All the best and keep up the good work!

FWIW I am mostly clean building in a Docker container to try to keep things sane.

**Comment by matty0ung** [comment]
Hi, Thanks for the detailed bug report and diagnostics.  I'll have a look and see if I can workout what's going on.

**Comment by matty0ung** [comment]
OK, good news is I can reproduce the bug and I know why it's happening.  I need to think about the right fix, which might not be entirely trivial, but I have a couple of ideas...

**Comment by OWoolland** [comment]
That's great! Good luck and thank you for taking a look 🙂

**Comment by matty0ung** [comment]
I have uploaded a fix that works-on-my-machine™ to https://github.com/Brewtarget/brewtarget/pull/684.  We'll include it in the 3.0.4 release.

As ever, please don't hesitate to let us know if you hit other problems.

**Comment by OWoolland** [comment]
First impressions for me are that the fix works really nicely! Thanks again for looking in to it - amazingly quick response and fix!

From my perspective I am happy for the issue to close whenever you it is appropriate.

All the best :)

**Comment by matty0ung** [comment]
Closing now that [release 3.0.4](https://github.com/Brewtarget/brewtarget/releases/tag/v3.0.4) is out.
