### ISSUE TITLE
`.deb` packages are missing from v3.0.5 release

### ISSUE THREAD

**Issue by arongergely** [Brewtarget/brewtarget#693]
Hi,

The [release text](https://github.com/Brewtarget/brewtarget/releases/tag/v3.0.5)  mentions `.deb`s but they are not included.

Thank you for maintaining the software, it's really handy in my hobby!

**Comment by matty0ung** [comment]
Ah, sorry, that's my bad.  Should be uploaded now.

**Comment by arongergely** [comment]
Thank you! Works fine on my ubuntu 22.04
