### ISSUE TITLE
Brewtarget logo is missing from main window

### ISSUE THREAD

**Issue by matty0ung** [Brewtarget/brewtarget#697]
Normally, below the big blue plus and minus symbols there should be the red "target" Brewtarget logo and the word "Brewtarget" in two shades of brown (eg see the screenshot in https://github.com/Brewtarget/brewtarget/issues/609).  I've just noticed on my local build that it's not there any more.  I'm guessing it's some one-line error somewhere (and quite likely as an oversight on my part), but, off the bat, I can't see where.  Eg I had a look at mainWindow.ui and brewtarget.qrc and couldn't see what might have changed (or when) for this to disappear.

**Comment by mikfire** [comment]
That may not be a clean merge request. It has now been years since I've done this. If it is too unclean, reject it and I will try again.
