### ISSUE TITLE
Noonan IBUs

### ISSUE THREAD

**Issue by rocketman768** [Brewtarget/brewtarget#7]
From [launchpad](https://bugs.launchpad.net/brewtarget/+bug/1424160)

It would be handy if Brewtarget had support for IBU estimations based on Greg Noonan's work.

**Comment by dpettersson** [comment]
I think o have most of it worked out now. 
The only thing left is the gravity corrections but i cannot find the data for that online (it seems that they can only be found in the book "Brewing Lager beers").
