### ISSUE TITLE
Drag and drop is broken

### ISSUE THREAD

**Issue by mikfire** [Brewtarget/brewtarget#701]
I cannot drag fermentables, hops, misc or yeast from the trees onto the new recipe. Style and equipment work.

**Comment by matty0ung** [comment]
I didn't know about drag-and-drop!
Is this likely to be a signals and slots thing?

**Comment by mikfire** [comment]
Man, I sweat and labor on these features and I am the only person in the world who uses them. One should be able to simply drag an item from the tree on the left onto the tables in the center and it will be added to the recipe. It should also change the focused table (so if you have hops showing and you drag a fermentable, it will switch the tab to the fermentables).

It is a signal/slot thing, but it is a special set of it. You have to do work in the UI file and then properly plumb all the data. It looks like some of the plumbing is still there, but I haven't dug into it far enough. Give me a bit and I can probably find this.

**Comment by matty0ung** [comment]
It's a cool feature. I just didn't realise it was there.  (Took me a while to discover right-click as well.  I think I'm a bit slow on the uptake! :smile:)
