### ISSUE TITLE
WARNING : QObject::connect: No such signal BrewNote::brewDateChanged(QDateTime) in /home/mik/brewtarget/mik/src/BtTreeModel.cpp

### ISSUE THREAD

**Issue by mikfire** [Brewtarget/brewtarget#703]
It is a simple fix, with the PR incoming in just a few seconds.

**Comment by matty0ung** [comment]
Good spot!  Longer term I would like to eliminate the use of the old SIGNAL and SLOT macros as they prevent these sorts of errors being detected at compile-time.
