### ISSUE TITLE
Case insensitive matching of unit names (mL vs ml etc)

### ISSUE THREAD

**Issue by mikfire** [Brewtarget/brewtarget#725]
I know the proper notation is mL. But could we maybe stretch the definitions a little and make 'ml' an equivalent? I keep forgetting and the volume entries will default to L when they don't recognize the unit. The difference between 3 mL of lactic acid and 3 L is significant and somewhat surprising.

**Comment by matty0ung** [comment]
Yes, that's a good idea.  I wouldn't remember it was mL either!  Maybe it will suffice to do case-insensitive matching.  I'll have a look.

**Comment by matty0ung** [comment]
Looks like the fix isn't too bad, but I need to make it in two different places, which is annoying me.  I'll either try to fix that duplication or comment why it's hard to do so! :smiley:

**Comment by matty0ung** [comment]
Included in https://github.com/Brewtarget/brewtarget/releases/tag/v3.0.8..
