### ISSUE TITLE
M_PI undefined when Compiling on Windows 10 under Visual Studio 2022

### ISSUE THREAD

**Issue by matty0ung** [Brewtarget/brewtarget#741]
Compiling on Windows 10 under Visual Studio 2022 still getting error. Please see below.
C++ Language Standard used: ISO C++17 Standard (/std:c++17).
3>RadarChart.cpp
3>D:\Git\brewtarget\src\RadarChart.cpp(50,40): error C2065: 'M_PI': undeclared identifier
3>D:\Git\brewtarget\src\RadarChart.cpp(50,17): error C2737: '`anonymous-namespace'::RadiansInACircle': const object must be initialized

_Originally posted by @Lubart in https://github.com/Brewtarget/brewtarget/issues/539#issuecomment-1507564599_

**Comment by Lubart** [comment]
Should be also an easy fix. If C++20 is used. Tested on  VS 2022 and Kali, GCC v. 12.2.0.
#include <numbers> // std::numbers
#include <iomanip>
#include <iostream>
int main() {
    std::cout << std::fixed << std::setprecision(20);
    std::cout << "float       " << std::numbers::pi_v<float> << std::endl;
    std::cout << "double      " << std::numbers::pi << std::endl;
    std::cout << "long double " << std::numbers::pi_v<long double> << std::endl;
    std::cout << "exact       " << "3.141592653589793238462643383279502884197169399375105820974944" << std::endl;
}

**Comment by matty0ung** [comment]
I've made the fix on my local machine, so will include it in the next PR.

**Comment by matty0ung** [comment]
I hope this is fixed in https://github.com/Brewtarget/brewtarget/releases/tag/v3.0.8, but I don't have Visual Studio installed, so have not checked directly.  Please reopen this issue if the problem persists.
