### ISSUE TITLE
Are you interested in adding a formula suitable for red wine

### ISSUE THREAD

**Issue by mrz5802** [Brewtarget/brewtarget#768]

**Comment by matty0ung** [comment]
Hello!
I don't know too much about making wine.  Do people use (or want to use) Brewtarget for wine recipes?
My impression from the work I'm doing on BeerJSON is that the new data structures will support a wider range of fermentation recipes than is currently possible, so future versions of the software might lend themselves more to more diverse recipes.
If you tell us a bit more about the formula, then we can definitely take a look at how easy it would be to integrate.

**Comment by matty0ung** [comment]
Closing in the absence of further info.
