### ISSUE TITLE
Resolution and scaling issues

### ISSUE THREAD

**Issue by intergil** [Brewtarget/brewtarget#769]
Running in Mac OS Ventura. Native resolution is 1440x900. Brewtarget doesn't seem to scale, looking blurry. Any adjustments or settings to match native resolution?

**Comment by matty0ung** [comment]
Hmm.  Usually the problems are with HDPI displays rather than "normal" resolution.  Could you add a screenshot to show which bits are blurry?  Is it everything, or just icons?

**Comment by intergil** [comment]
It's the entire GUI. Here is a screenshot 
![image](https://github.com/Brewtarget/brewtarget/assets/31230833/9247c7d5-5460-442f-b5cb-5400a16fc459)

**Comment by matty0ung** [comment]
Ah, yes, I see what you mean.  It looks rather badly scaled.  Is it the same if you try a more recent version of Brewtarget?  (Version 2.3.0 is from 7 years ago...)

**Comment by matty0ung** [comment]
In the absence of further info, I'll close this, but please re-open if you see the same problem with the current version of Brewtarget.

**Comment by intergil** [comment]
Thanks Matt,

I didn't realize I was using that old a version. I will update to the
latest and give it a whirl. I appreciate you looking into it.

Gil

Gil Lopez, CTS, CDT, ING
415.608.1306
