### ISSUE TITLE
Improper localization behavior for "Specific heat (cal/(g*K))"

### ISSUE THREAD

**Issue by renato** [Brewtarget/brewtarget#77]
When I change the Specific Heat field in the Equipment Editor and type, for instance, "0,215", it shows as "0,215" and is apparently save correctly because when I save and re-open the Editor, it is still showing as "0,215".

However, I can verify it's not yet persisted as it's not used in the "Mash wiz".

When I close Brewtarget and re-open it, the Specific heat for the same Equipment is now shown as "215,000", and the "Mash wiz", using this as specific heat, suggests an Infusion Temp of "519.536,000 C".

If I open with LC_ALL=en_US.UTF-8, then the Specific heat is shown correctly as 0.215.

This issue is likely related to #65, because it goes through Brewtarget::toDouble() which uses QLocale.toDouble():
https://github.com/Brewtarget/brewtarget/blob/master/src/equipment.cpp#L452
https://github.com/Brewtarget/brewtarget/blob/master/src/brewtarget.cpp#L1069

**Comment by rocketman768** [comment]
Yes, you are exactly right. I'll push up a fix shortly.
