### ISSUE TITLE
Insane IBU calculated when using First Wort for hop use

### ISSUE THREAD

**Issue by ve3jrw** [Brewtarget/brewtarget#772]
I add 43 grams of Amarillo hops and select usage of first wort the application computes the IBU to be 4653.1.

Using Windows version of Brewtarget v2.3.0

**Comment by matty0ung** [comment]
Hello,
Sorry to hear you're having problems.
Could you download a newer version of the software and try with that?  Version 2.3.0 is very old, and a lot of things have changed since it was released.

**Comment by ve3jrw** [comment]
Ok, I had gone to the web site and it said 2.3.0 was the latest.

I'll pick up the github version. Here is the latest on the site currently:

http://www.brewtarget.org/

<html><body>


Windows | brewtarget-2.3.0_x86.exe | 28 MB
-- | -- | --
Linux 32-bit | brewtarget_2.1.0-1_i386.deb                                brewtarget-2.1.0-1.fc17.i686.rpm | 3.1 MB                                3.1 MB
Linux 64-bit | brewtarget_2.3.0-1_amd64.deb                                brewtarget-2.3.0-1.fc23.x86_64.rpm | 3.2 MB                                2.6 MB
Mac 64-bit | Brewtarget-2.3.0.dmg | 24.6 MB
Source Code | brewtarget_2.3.0.orig.tar.xz                                GitHub Repository | 9.1 MB                                8.2 MB


</body>
</html>Windows 	[brewtarget-2.3.0_x86.exe](https://launchpad.net/brewtarget/trunk/2.3.0/+download/brewtarget_2.3.0_x86.exe) 	28 MB
Linux 32-bit 	[brewtarget_2.1.0-1_i386.deb](https://launchpad.net/brewtarget/trunk/2.1.0/+download/brewtarget_2.1.0-1_i386.deb)
[brewtarget-2.1.0-1.fc17.i686.rpm](https://launchpad.net/brewtarget/trunk/2.1.0/+download/brewtarget-2.1.0-1.fc17.i686.rpm) 	3.1 MB
3.1 MB
Linux 64-bit 	[brewtarget_2.3.0-1_amd64.deb](https://launchpad.net/brewtarget/trunk/2.3.0/+download/brewtarget_2.3.0-1_amd64.deb)
[brewtarget-2.3.0-1.fc23.x86_64.rpm](https://launchpad.net/brewtarget/trunk/2.3.0/+download/brewtarget-2.3.0-1.fc23.x86_64.rpm) 	3.2 MB
2.6 MB
Mac 64-bit 	[Brewtarget-2.3.0.dmg](https://launchpad.net/brewtarget/trunk/2.3.0/+download/Brewtarget-2.3.0.dmg) 	24.6 MB
Source Code 	[brewtarget_2.3.0.orig.tar.xz](https://launchpad.net/brewtarget/trunk/2.3.0/+download/brewtarget_2.3.0.orig.tar.xz)
[GitHub Repository](https://github.com/Brewtarget/brewtarget) 	9.1 MB
8.2 MB

**Comment by ve3jrw** [comment]
All good in 3.0.9! You might want to update the brewtarget.org site or have it reference github for the downloads so you don't need to maintain the two.

Thanks for your help, you can close!

**Comment by matty0ung** [comment]
Unfortunately, the person who owns the brewtarget.org site will not give us access to update it. :disappointed:
