### ISSUE TITLE
Can't change time when first wort is used for hop use

### ISSUE THREAD

**Issue by ve3jrw** [Brewtarget/brewtarget#773]
It is stuck at 1 h, cannot alter it at all.

**Comment by matty0ung** [comment]
Is this also for Brewtarget 2.3.0?  If so, as per https://github.com/Brewtarget/brewtarget/issues/772, could you try with a more recent version of the software?  You can download from https://github.com/Brewtarget/brewtarget/releases.

**Comment by ve3jrw** [comment]
Ok, I had gone to the web site and it said 2.3.0 was the latest.

I'll pick up the github version.  Here is the latest on the site currently:

http://www.brewtarget.org/

Windows | brewtarget-2.3.0_x86.exe | 28 MB
-- | -- | --
Linux 32-bit | brewtarget_2.1.0-1_i386.deb                                brewtarget-2.1.0-1.fc17.i686.rpm | 3.1 MB                                3.1 MB
Linux 64-bit | brewtarget_2.3.0-1_amd64.deb                                brewtarget-2.3.0-1.fc23.x86_64.rpm | 3.2 MB                                2.6 MB
Mac 64-bit | Brewtarget-2.3.0.dmg | 24.6 MB
Source Code | brewtarget_2.3.0.orig.tar.xz                                GitHub Repository | 9.1 MB                                8.2 MB


</body>
</html>Windows 	[brewtarget-2.3.0_x86.exe](https://launchpad.net/brewtarget/trunk/2.3.0/+download/brewtarget_2.3.0_x86.exe) 	28 MB
Linux 32-bit 	[brewtarget_2.1.0-1_i386.deb](https://launchpad.net/brewtarget/trunk/2.1.0/+download/brewtarget_2.1.0-1_i386.deb)
[brewtarget-2.1.0-1.fc17.i686.rpm](https://launchpad.net/brewtarget/trunk/2.1.0/+download/brewtarget-2.1.0-1.fc17.i686.rpm) 	3.1 MB
3.1 MB
Linux 64-bit 	[brewtarget_2.3.0-1_amd64.deb](https://launchpad.net/brewtarget/trunk/2.3.0/+download/brewtarget_2.3.0-1_amd64.deb)
[brewtarget-2.3.0-1.fc23.x86_64.rpm](https://launchpad.net/brewtarget/trunk/2.3.0/+download/brewtarget-2.3.0-1.fc23.x86_64.rpm) 	3.2 MB
2.6 MB
Mac 64-bit 	[Brewtarget-2.3.0.dmg](https://launchpad.net/brewtarget/trunk/2.3.0/+download/Brewtarget-2.3.0.dmg) 	24.6 MB
Source Code 	[brewtarget_2.3.0.orig.tar.xz](https://launchpad.net/brewtarget/trunk/2.3.0/+download/brewtarget_2.3.0.orig.tar.xz)
[GitHub Repository](https://github.com/Brewtarget/brewtarget) 	9.1 MB
8.2 MB

**Comment by ve3jrw** [comment]
All good in 3.0.9! You might want to update the brewtarget.org site or have it reference github for the downloads so you don't need to maintain the two.

Thanks for your help!

**Comment by matty0ung** [comment]
I would **love** to update the brewtarget.org website but I do not have access to it.  (The site was set up by one of the original coders who is no longer involved in the project.  He has never responded to my requests to have access to update the website.)
