### ISSUE TITLE
Hops Use combo has entry that says "Aroma" but ends up listed as "Post-Boil" in the display

### ISSUE THREAD

**Issue by ve3jrw** [Brewtarget/brewtarget#775]
It is inconsistent.  They should match, they used to.  

I don't really care what they are as long as they match. 

However, it would be nice to have more specific ones added like whirlpool, steeping to reflect the actual process being used as I currently have to do this manually by editing the Brewday steps.

**Comment by matty0ung** [comment]
The inconsistency should be fixed as part of the BeerJSON upgrade I am working on.

**Comment by matty0ung** [comment]
AFAICT this is now fixed in the `develop` branch (ie soon-to-be 4.0 release).  Please reopen if not.
