### ISSUE TITLE
Printing recipe without beer style will crash software

### ISSUE THREAD

**Issue by eyousey** [Brewtarget/brewtarget#79]
Brewtarget ver: 2.1.0
FreeBSD foo.bar 10.1-RELEASE-p16 FreeBSD 10.1-RELEASE-p16 #0: Tue Jul 28 12:04:19 UTC 2015     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64

If printing a recipe or brew day notes for a recipe without a beer style, the software will crash.  Set a beer style, and it will print without issue.

**Comment by rocketman768** [comment]
Can't reproduce on current master.
