### ISSUE TITLE
The font size too small

### ISSUE THREAD

**Issue by llinlluo** [Brewtarget/brewtarget#793]
The font size of the text in some parts of the software is so small that it's completely unreadable, is it possible to resize the characters?
![屏幕截图 2024-03-31 154412](https://github.com/Brewtarget/brewtarget/assets/122716833/ccc0abca-278a-47b5-9255-1fdf627f04ad)

**Comment by matty0ung** [comment]
Sorry to hear you're having problems.  I will have a look at this.  A couple of questions to help with disgnostics: 

- Are you running on Windows?  
- What resolution is your monitor?  
- Do you have Display DPI Scaling settings configured to scale other fonts on your system?

We had a few issues with high DPI displays, which I thought I had mostly had fixed.  At least, it looks fine on my HDPI Linux display.  But maybe there are some other tweaks needed for Windows.

Normally the text circled in the picture is the same size as most of the other text on the screen.  For some reason it must either be picking up a different font size or the font sizes are specified in different ways in different places.  (We're trying to get away from specifying things in pixels, as that's going to look wrong somewhere, depending on the resolution of the monitor.)

**Comment by matty0ung** [comment]
I'm hoping the move to Qt6 in the most recent release will address some scaling issues.  It certainly seems to make icons appear a better size on my monitor.

Please reopen this issue if you hit problems with the 4.0.7 or later releases.
