### ISSUE TITLE
DefaultContent004-MoreYeasts.json not in cmake files

### ISSUE THREAD

**Issue by jimdbr** [Brewtarget/brewtarget#806]
When I was troubleshooting my database issues I had to install DefaultContent004-MoreYeasts.json by hand to get rid of an error message. It seems that this file name is missing from the cmake files and isn't installed by default.

**Comment by matty0ung** [comment]
Ah, good spot -- thanks!  Will fix in 4.0.1 release.

**Comment by matty0ung** [comment]
Closing now 4.0.1 release is out.
