### ISSUE TITLE
Change weird checkbox in fermentable table

### ISSUE THREAD

**Issue by theophae** [Brewtarget/brewtarget#81]
Since I use BT, I think the checkboxes that change when selected are very weird and unnatural.
For example, when the checkbox in unchecked, it indicate "steeped", but when I see it beside an unckecked checkbox, it seems to mean that the grain is not steeped.
I would be much clearer to have either a checkbox alone to indicate if the grain is mashed or a combo box with "Yes" or "No".
Same remark for the "Late Addition", it should use a combo box with "Normal" and "Late" as value.

If you think of other weird checkboxes like those, do not hesitate to add them.

I'd like to do this change, but I prefer to discuss what to do with you first.

**Comment by rocketman768** [comment]
I think a combobox is the right replacement here. Thanks for pointing out these UI things that we've come to live with.

**Comment by theophae** [comment]
I working on this point for a couple of days, and I quite stuck with some problems:
* I am searching a way to set the column width to the size of the longer choice in the comboBoxes. I think it is very annoying when you desire to change the type from grain to Dry Extract, for example, to have to  resize the column manually.
* As I replaced the checkbox with a combobox, I'm looking for how to hide one of the combobox parameters (Steeped or Not mashed regarding the case). More generally, I don't see how to access the combobox when I'm outside of the FermentableItemDelegate class (which as no access to fermentable data).

If any of you can help me with those points I'll be very grateful.

**Comment by rocketman768** [comment]
Do you have any code we can look at? You can create a pull request if so.

**Comment by theophae** [comment]
I've created the pull request.

**Comment by mikfire** [comment]
You need to poke at the sizeHints for the first question.

Assuming you are using the standard editor delegates, you can do this:
  box->setMinimumWidth( box->minimumSizeHint().width() );
and the dropdown box will be properly sized. I've played a bit with the hop
table (one of the places where this annoys me to no end) and it does work.

If I understand the documentation correctly, you can't really access the
combobox "outside" of the delegate. The combobox is created when you start
editing the field, and then it is deleted when you are done. I don't think
there is a cached version of it to be accessed.

Mik

On Mon, Sep 21, 2015 at 7:16 AM, theophae <notifications@github.com> wrote:

> I working on this point for a couple of days, and I quite stuck with some
> problems:
>
>    - I am searching a way to set the column width to the size of the
>    longer choice in the comboBoxes. I think it is very annoying when you
>    desire to change the type from grain to Dry Extract, for example, to have
>    to resize the column manually.
>    - As I replaced the checkbox with a combobox, I'm looking for how to
>    hide one of the combobox parameters (Steeped or Not mashed regarding the
>    case). More generally, I don't see how to access the combobox when I'm
>    outside of the FermentableItemDelegate class (which as no access to
>    fermentable data).
>
> If any of you can help me with those points I'll be very grateful.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Brewtarget/brewtarget/issues/81#issuecomment-141944799>
> .
>



-- 
In a world of ninja v. pirate, I pilot a Gundam

**Comment by theophae** [comment]
Thanks for the tips, it works very well and give the same result than my solution but in a simpler way.
About the second point, it is really to bad if we can't do it. What I've made works, but I feel it is weird to choose "Not Mashed" and to get "Steeped" afterwards. I really need to find a better way to do it.
