### ISSUE TITLE
Yeasts have no Attenuation

### ISSUE THREAD

**Issue by jeroen79** [Brewtarget/brewtarget#812]
In version 4.0.2 yeast seem to have lost there Attenuation, both old and new.

And when trying to enter Attenuation and Max Attenuation it crashes.

**Comment by matty0ung** [comment]
To add to this, there is still a single attenuation field for the _use_ of a specific yeast in a recipe, and if this was set on an existing recipe it _should_ (in theory at least) have been retained in the data migration.

**Comment by jeroen79** [comment]
I am afraid all Attenuation gets lost in migration.

I turned om the log and the following appears after the crash, i just entered some value in Attenuation and blurred the field.

[widgets/SmartAmountSettings.cpp:194]
[17:48:49.822] (az4) DEBUG : void SmartLineEdit::onLineChanged()  [widgets/SmartLineEdit.cpp:154]
[17:48:49.823] (az4) ERROR : ASSERT: "this->isInitialised()" in file ../src/widgets/SmartLineEdit.cpp, line 155  [widgets/SmartLineEdit.cpp:155]

**Comment by matty0ung** [comment]
Ah, OK, I understand.  Sounds like I need to do a fix in the migration code.  Would you be able to upload your pre-migration database file?  It should have been automatically saved in the same directory as the `database.sqlite` file with some name along the lines of `2024-07-27 21˸01˸16 database.sqlite backup (before upgrade from v9 to v11)`.

**Comment by jeroen79** [comment]
I also tried with a clean database from 3.0.11 and it also has the issue, so i don't think its data related.

**Comment by matty0ung** [comment]
I now have a fix for the missing attenuation (https://github.com/Brewtarget/brewtarget/pull/813) but, so far, I haven't been able to replicate the crash.  Could you upload the whole log file (from start-up to crash)?  Might give some more clues.  (I can see from the error above that it's an issue with the meta-info for one of the input fields not being initialised, so I'm hoping the rest of the log might offer some clue about why this initialisation didn't happen.)

**Comment by matty0ung** [comment]
Sorry, I've found where the bug is now -- it was staring me in the face!  That "Attenuation" field that's causing the crash should have been removed in the 4.0 release, because it's replaced by "Min Attenunation" and "Max Attenuation" fields below it.  I'll fix that and then make the recipe-specific attenuation visible on the Yeast tab under the recipe.

**Comment by matty0ung** [comment]
Should be fixed in [4.0.3](https://github.com/Brewtarget/brewtarget/releases/tag/v4.0.3), but please reopen this issue if not.  As ever, if you find other problems, please don't hesitate to open a new issue.
