### ISSUE TITLE
[BeerXML/BeerJSON] Recipe export does not match selected type

### ISSUE THREAD

**Issue by bebenlebricolo** [Brewtarget/brewtarget#835]
Hi Matt !

I noticed on [latest commit(8d5fb471f6640bef561d2d5b36d11654e422128c)](https://github.com/Brewtarget/brewtarget/commit/8d5fb471f6640bef561d2d5b36d11654e422128c) of develop/ branch that when you try to export a recipe from the database using Brewtarget UI, the file is still written with the .xml extension if you leave the extension empty and still select the BeerJSON output format from the dropdown element.

## Default output type for exported files 

![image](https://github.com/user-attachments/assets/38057d30-b4e6-47c0-9b27-e5d7a0661ebd)

Actual file content : 
![image](https://github.com/user-attachments/assets/d63b399d-50b5-45f8-a880-b42aa57f3681)

If I manually force the *.json extension by explicitely writting test.json, then it gets properly serialized as a .json file :
![image](https://github.com/user-attachments/assets/22c2418e-727d-4a4a-bc83-789dd692853a)

## Charset encoding issue
However, notice the charset issues in the .json version.
I couldn't find equivalent encoding issues in the xml version by the way.
I tried to reopen the file with UTF-8 (default), Western ISO-8859-1, to no avail.
Seems like Qt latin string wrong encoding to me.

**Comment by matty0ung** [comment]
Good point about the export.  At the moment, once the user gave a file name, we use the filename extension to decide the format.  But, as you say, ideally we should properly handle the case of no filename extension (or unrecognised).  I don't know if we can get the "Save" dialog to report back to us what the selected file format was.  If so, we can use that in exactly the way you suggest.

For the JSON, I'll have a look.  You're right that JSON should normally be coded in UTF-8.  (It's a different story for BeerXML.)

**Comment by bebenlebricolo** [comment]
Thanks Matt.
As for Qt Dialog (and the choices), I'm quite confident we can extract that info either as a SIGNAL or directy querying the dropdown box when the user actively clicks on "save".

Usually we can also detect (by text changed SIGNAL) what the extension being typed in is and update the drowdown dialog when we're certain that's either xml/json.

An improved UX would also be to automatically rename the file's extension depending on what the user is selecting from the dropdown dialog as well. 

My 2 cents :smile:

**Comment by matty0ung** [comment]
It turns out the fixes for both issues are straightforward.  A small lambda function for the file extension changing when you change the filter.  And a "D'oh" fix for the corrupted characters where I'd used a string_view instead of a string on an underlying temporary.

**Comment by bebenlebricolo** [comment]
Nice, thanks for the swift fixes !

**Comment by matty0ung** [comment]
Fix included in [4.0.5 release](https://github.com/Brewtarget/brewtarget/releases/tag/v4.0.5).
