### ISSUE TITLE
Cmake Qt5 version issue on Mac Sonoma 14.6.1 building 4.0.6

### ISSUE THREAD

**Issue by TMasz** [Brewtarget/brewtarget#852]
I have the latest Qt5 installed via homebrew but I get this from cmake:

```
/opt/local/bin/cmake ../brewtarget-4.0.6
-- Building brewtarget version 4.0.6
-- PROJECT_SOURCE_DIR is /Users/tommasz/Developer/brewtarget-4.0.6
-- Doing Debug build (DO_RELEASE_BUILD = OFF)
Warning: Formula qt5 was renamed to qt@5.
Warning: Formula qt5 was renamed to qt@5.
-- CMAKE_PREFIX_PATH = /usr/local/opt/qt@5

CMake Error at CMakeLists.txt:480 (find_package):
  Could not find a configuration file for package "Qt5" that is compatible
  with requested version "5.15.13".

  The following configuration files were considered but not accepted:

    /opt/local/lib/cmake/Qt5/Qt5Config.cmake, version: 5.14.2



-- Configuring incomplete, errors occurred!
See also "/Users/tommasz/Developer/build/CMakeFiles/CMakeOutput.log".
See also "/Users/tommasz/Developer/build/CMakeFiles/CMakeError.log".
```
Is this a configuration issue on my end?

**Comment by matty0ung** [comment]
Hello,

Hmm, that's interesting, as, normally, homebrew would give you Qt 5.15.13 if you asked it for Qt5, but CMake is finding only version 5.14.2 of Qt.

If you try running the bt script in the top directory of Brewtarget -- specifically `./bt -v setup all` -- it tries to install all the dependencies to allow you to build.  (This is the script that we use to set up the build environment in the nightly builds.)  Let me know if this does the trick.

Alternatively, if you wait a couple of days, we should be on to Qt 6.

**Comment by TMasz** [comment]
I had to run that script a couple of times since it was generating errors on homebrew installs of packages I already had installed but it got to a step that tries to do a MacPorts (which I don't have) install and stops:

`1500 directories, 10769 files
DEBUG:  Installing xalanc via MacPorts  [buildTool.py:1004]
Password:
Error: Current platform "darwin 23" does not match expected platform "darwin 18"
Error: If you upgraded your OS, please follow the migration instructions: https://trac.macports.org/wiki/Migration
OS platform mismatch
    while executing
"mportinit ui_options global_options global_variations"
Error: /opt/local/bin/port: Failed to initialize MacPorts, OS platform mismatch
CRITICAL:  Error running sudo (sudo port install xalanc)  [btUtils.py:80]`

**Comment by matty0ung** [comment]
Thanks for the info.  I don't own a Mac, so, although I can usually, by trial and error, solve build/install problems in the GitHub Mac build environment, there are other things that I rely on Mac owners to tell me about!

That's interesting you were getting errors from things already being installed.  The script does attempt to check whether things are already installed (via `brew list`), but there must be some flaw in the logic there. 

For MacPorts, the error message suggests you need a newer version of MacPorts itself.  If you didn't already, you should ignore the commented-out commands in the build scripts, and follow the instructions at https://guide.macports.org/#installing to install the version of MacPorts that matches your version of MacOS.

**Comment by TMasz** [comment]
More errors. I'll stick with 2.3.0 for now. Thanks for your help.

**Comment by matty0ung** [comment]
Fair enough.  If you change your mind and want help debugging the errors, feel free to reopen this ticket and, as ever, we'll do our best to help.  In the meantime, happy brewing!
