### ISSUE TITLE
Missing libb2-1.dll

### ISSUE THREAD

**Issue by Brew1984** [Brewtarget/brewtarget#863]
Installation 4.07 failed because code could not be executed: libb2-1.dll not found

**Comment by matty0ung** [comment]
Ah, another dependency introduced by moving to Qt6.  Should be a one-line fix.  I'll include it in the next PR.

**Comment by matty0ung** [comment]
Fixed in [4.0.8](https://github.com/Brewtarget/brewtarget/releases/tag/v4.0.8).
