### ISSUE TITLE
Changing Yeast or Attenuation doesn't change ABV

### ISSUE THREAD

**Issue by jeroen79** [Brewtarget/brewtarget#872]
In the latest versions changing yeast or yeast Annetuation  doens't seem to affect ABV which doesn't seem logical?

I even tried making a yeast with only 50% but the result doesn't change

**Comment by matty0ung** [comment]
That seems like a very good question!  I'll have a look at how the ABV calculations work...

**Comment by matty0ung** [comment]
From a quick look at the code, it seems we do not currently involve yeast at all in the ABV calculation(!).  We look only at OG and FG.  I would be very happy to improve this.  I imagine it's a bit of a complex topic, but if we can find a good formula (or formulae) then it should be doable to implement in the code.  I will try to have a look when I next have some time, but meanwhile all suggestions would be welcome!

**Comment by jeroen79** [comment]
I am quite sure brewtarget did do this correctly in the past, maby it was accidentally removed in die 4.x versions?

**Comment by matty0ung** [comment]
Sorry, you're right that there's another bit of the calculation.  I was looking in the wrong place.  It looks like there is a bit of tweaking to do.  I'll dig into it.  

With the changes introduced in 4.0, you can now specify an attenuation range, ie min and max, for a yeast, and then specify the actual attenuation you want to use in a particular recipe, so the way we read attenuation did change a bit.  Also, I can see there's a bug where modifications to attenuation in the master yeast record aren't getting stored in the database.

**Comment by matty0ung** [comment]
OK, I have a fix for this working locally.  There's a separate problem with editing percentages on the yeast editor, but that will likely be a small tweak.  Once I've sorted that, I'll push it all up to the current PR and then do a merge.  Should be within a few days if all goes well.

**Comment by matty0ung** [comment]
Fixed in [4.0.10 release](https://github.com/Brewtarget/brewtarget/releases/tag/v4.0.10).
