### ISSUE TITLE
Drop down menu for Style and Equipment are so narrow, cannot see contents 

### ISSUE THREAD

**Issue by karthil** [Brewtarget/brewtarget#879]
I've pasted a screenshot of the Style dropdown menu.  But the Equipment dropdown menu behaves the same way. 
![image](https://github.com/user-attachments/assets/c592b954-c837-4f73-b2ad-3508cf72a2da)

**Comment by matty0ung** [comment]
Thanks for this.  I think it's because there's now a splitter between the two columns on the "recipe" part of the window.  I probably just need to change the control so it's a regular drop-down rather than button + drop-down.  Will have a look.

**Comment by matty0ung** [comment]
Started having a look at this.  Got it to work OK on Linux, but not yet on Windows.  Will try moving the drop-down under the button instead of to the right of it.

**Comment by matty0ung** [comment]
Fix will be included in 4.0.11 release.

**Comment by matty0ung** [comment]
Fixed in [4.0.11](https://github.com/Brewtarget/brewtarget/releases/tag/v4.0.11).
