### ISSUE TITLE
OG doesn't immediately change when adding malt to a recipe

### ISSUE THREAD

**Issue by karthil** [Brewtarget/brewtarget#880]
OG doesn't change until you add or remove yeast.  I haven't tried adding/removing other components to find out if that also causes an update.

**Comment by matty0ung** [comment]
I suspect this will be the same issue as https://github.com/Brewtarget/brewtarget/issues/881.  The logic is shared across all recipe additions.  Will confirm when I do the PR.

**Comment by matty0ung** [comment]
Fixed in [4.0.11](https://github.com/Brewtarget/brewtarget/releases/tag/v4.0.11).
