### ISSUE TITLE
IBU doesn't update when adding hops

### ISSUE THREAD

**Issue by karthil** [Brewtarget/brewtarget#881]
The only way I've found to get IBU to update is to close and restart the program.

![image](https://github.com/user-attachments/assets/004b404f-0c5e-479f-9aaa-491c606e4edc)

**Comment by Brew1984** [comment]
Until this is fixed just activate another recipe and go back to the one you're editing.  Same for all the ingredients. It works for me.

**Comment by matty0ung** [comment]
This will probably be some signals and slots plumbing.  I'll take a look.

**Comment by matty0ung** [comment]
Took me a little while to work it out, but it's a one-line fix.  PR on the way.

**Comment by matty0ung** [comment]
Fixed in [4.0.11](https://github.com/Brewtarget/brewtarget/releases/tag/v4.0.11).
