### ISSUE TITLE
Segfault on pressing delete key to remove ingredients from recipe

### ISSUE THREAD

**Issue by rocketman768** [Brewtarget/brewtarget#89]
Select an ingredient in the recipe pane. Press delete key. Segfault.

**Comment by rocketman768** [comment]
Program received signal SIGSEGV, Segmentation fault.
    0x00007ffff790ce10 in QAbstractItemView::selectionModel() const () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
    (gdb) bt
    #0  0x00007ffff790ce10 in QAbstractItemView::selectionModel() const () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
    #1  0x00000000005c9e82 in MainWindow::deleteSelected (this=0xe1be70) at /home/philip/myc/brewtarget/brewtarget/src/MainWindow.cpp:481
    #2  0x00000000006a613c in MainWindow::qt_static_metacall (_o=0xe1be70, _c=QMetaObject::InvokeMetaMethod, _id=40, _a=0x7fffffffd6b0)
    at /home/philip/myc/brewtarget/build/src/moc_MainWindow.cpp:382
    #3  0x00007ffff314cfdd in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
    #4  0x00007ffff76be772 in QAction::triggered(bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
    #5  0x00007ffff76c0e98 in QAction::activate(QAction::ActionEvent) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
    #6  0x00007ffff76c14d7 in QAction::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
    #7  0x00007ffff76c612c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
    #8  0x00007ffff76cb600 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
    #9  0x00007ffff311ddcb in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
    #10 0x00007ffff36917bb in QShortcutMap::dispatchEvent(QKeyEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
    #11 0x00007ffff3691919 in QShortcutMap::tryShortcutEvent(QObject*, QKeyEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
    #12 0x00007ffff76cb428 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
    #13 0x00007ffff311ddcb in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
    #14 0x00007ffff3661c51 in QGuiApplicationPrivate::processKeyEvent(QWindowSystemInterfacePrivate::KeyEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
    #15 0x00007ffff3666645 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) ()
       from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
    #16 0x00007ffff364b64f in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
    #17 0x00007fffe8c64450 in ?? () from /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so
    #18 0x00007ffff1b44c5d in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
    #19 0x00007ffff1b44f48 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
    #20 0x00007ffff1b44ffc in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
    #21 0x00007ffff31761b7 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
    #22 0x00007ffff311b512 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
    #23 0x00007ffff312315c in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
    #24 0x00000000004f99fd in Brewtarget::run () at /home/philip/myc/brewtarget/brewtarget/src/brewtarget.cpp:584
    #25 0x00000000004b68d9 in main (argc=1, argv=0x7fffffffe0f8) at /home/philip/myc/brewtarget/brewtarget/src/main.cpp:88
    (gdb) f 1
    #1  0x00000000005c9e82 in MainWindow::deleteSelected (this=0xe1be70) at /home/philip/myc/brewtarget/brewtarget/src/MainWindow.cpp:481
    481        active->deleteSelected(active->selectionModel()->selectedRows());
    (gdb) p active
    $1 = (BtTreeView *) 0x0

**Comment by Mackanzx** [comment]
I'm not able to reproduce this error. It just asks me if i want to delete the latest selected recipe. (windows 10, latest stable/2.2.0)

**Comment by rocketman768** [comment]
Happens only immediately after startup for me. Debian/jessie.
