### ISSUE TITLE
Update Development Prerequisites to qt6

### ISSUE THREAD

**Issue by dfrap** [Brewtarget/brewtarget#892]
It is no longer possible to compile with qt5. The required packages should be updated to qt6. 
On current stable Debian 12, I find these are enough to compile correctly: 
qt6-svg-dev qt6-tools-dev qt6-base-dev qt6-multimedia-dev  

It is not possible to install current releases on Debian, so compiling seems to be the best option.

**Comment by matty0ung** [comment]
I have updated the https://github.com/Brewtarget/brewtarget/wiki/Development:-Getting-Started page.  I haven't tested the `bt` script etc on Debian, but I'd hope it mostly works given how much of Debian is used by Ubuntu.  Give me a shout if you hit particular problems.

**Comment by matty0ung** [comment]
Hopefully this is fixed in [4.0.12](https://github.com/Brewtarget/brewtarget/releases/tag/v4.0.12).  If not, please don't hesitate to reopen this issue!
