### ISSUE TITLE
Icons Misisng

### ISSUE THREAD

**Issue by fbzto** [Brewtarget/brewtarget#895]
Just installed Brewtarget on a fresh linux mint instance. For soem reason Icons within the app aren't showing. Any ideas on how to get these to show?

**Comment by matty0ung** [comment]
A couple of other people have reported similar problems, so I'm guessing they are all linked.  I _think_ it's most probably a missing library or dependency.  I'll have a look and see what I can discover.

**Comment by fbzto** [comment]
Thanks! Didn't realize this was still being updated. Was using the old version for years. Happy to support!

**Comment by matty0ung** [comment]
If you get a moment, try `sudo apt install libqt6svg6`, then launch Brewtarget again.  Current suspicion is that, unlike Qt5, Qt6 does not ship its .svg display library by default.

**Comment by fbzto** [comment]
Problem solved! Thanks!

**Comment by matty0ung** [comment]
Fix included in [4.0.12](https://github.com/Brewtarget/brewtarget/releases/tag/v4.0.12).
