### ISSUE TITLE
Opening user recipe causes crash

### ISSUE THREAD

**Issue by karthil** [Brewtarget/brewtarget#897]
You can create a new recipe.  But once you have done so, closing the program, re-opening and attempting to open that recipe causes a crash.

[brewtarget.log](https://github.com/user-attachments/files/17928980/brewtarget.log)

**Comment by matty0ung** [comment]
I managed to reproduce this locally, so I'll have a look.

**Comment by matty0ung** [comment]
Fix is a one-liner (a place we are looking up the recipe's boil without first checking it exists).  PR incoming (along with fix for copy recipe problems).

**Comment by matty0ung** [comment]
Hopefully this is fixed in [4.0.12](https://github.com/Brewtarget/brewtarget/releases/tag/v4.0.12).  If not, please don't hesitate to reopen this issue!
