### ISSUE TITLE
Copy recipe crash

### ISSUE THREAD

**Issue by Brew1984** [Brewtarget/brewtarget#899]
When copying a recipe 4.0.11 crashes with assert: [16:20:55.782] (5rc) ERROR : ASSERT: "hopAddition.recipeId() == this->key()" in file ../src/model/Recipe.cpp, line 2602  [model/Recipe.cpp:2602]

**Comment by matty0ung** [comment]
Thanks for letting me know about this.  A fix is on the way.  Turns out I accidentally removed a line of code in Recipe.cpp (because I'd originally planned to move it somewhere else).  Reinstating it stops this crash.

**Comment by matty0ung** [comment]
Hopefully this is fixed in [4.0.12](https://github.com/Brewtarget/brewtarget/releases/tag/v4.0.12).  If not, please don't hesitate to reopen this issue!
