### ISSUE TITLE
Scale Recipe tool should remove the current equipment

### ISSUE THREAD

**Issue by rocketman768** [Brewtarget/brewtarget#91]
After the tool is run, it should remove the equipment from the recipe. It does not.

**Comment by theophae** [comment]
I don't understand why it should do that. If I want to scale my recipe to adapt it to a new efficiency value, why the current equipment should be removed ?

**Comment by rocketman768** [comment]
That is a good point.

When you are scaling to a different batch size, the recipe batch size no
longer matches the equipment batch size. This means if you rerun the mash
wizard, the volumes and all the other derived calculations are wrong.

Another more elegant solution is to rework the tool to accept a different
equipment as the input so that you can simultaneously scale both efficiency
and volume while replacing the recipe's equipment with the right one.

For now though, the quick fix is to remove the equipment when scaling
volumes. The warning message even tells you this is going to happen.

**Comment by theophae** [comment]
That is a good idea.
And what about automatically execute the mash wizard after these changes. it just needs to take the same mash thickness as input. A simple advisory message to indicate that the mash has been changed seems enough (but not mandatory). I've never understood what it is so difficult to adapt this point.

**Comment by rocketman768** [comment]
Yeah, executing the mash wizard would be good. I'll make a feature request for this.
