### ISSUE TITLE
Convert units/formulas options to combo boxes

### ISSUE THREAD

**Issue by rocketman768** [Brewtarget/brewtarget#93]
Instead of groups of radio buttons, use a form layout of combo boxes for the sake of standard UI design.

**Comment by theophae** [comment]
I agree with that, it will make any modification easier.

**Comment by Daedalus12** [comment]
Heya; I'm new to this project (and Qt), but think I can tackle this as a first issue. Made a branch at https://github.com/Daedalus12/brewtarget/tree/issue93

**Comment by rocketman768** [comment]
Cool, thanks! Make a pull request (with "closes #93" in the commit headline) against the master branch and we'll review.
