### ISSUE TITLE
Mash designer - lower step temperature causes negative infusion

### ISSUE THREAD

**Issue by rocketman768** [Brewtarget/brewtarget#94]
If the current step temperature is less than the current one, you get negative infusion volumes available to you.

![negative_infusion](https://cloud.githubusercontent.com/assets/752558/10124043/26de2ca6-64ff-11e5-8f84-e97e38bb8405.png)

**Comment by rocketman768** [comment]
This problem is bigger than I anticipated. The mash designer is totally broken when the current target temp is lower than the previous target temp. The problem is that the functions `MashDesigner::maxTemp_c()`, `MashDesigner::minTemp_c()`, `MashDesigner::minAmt_l()`, and `MashDesigner::maxAmt_l()` are all implicitly assuming the temperature is going up.

I am not confident that I can fix this without a significant risk of regression for 2.2.0. Will push this off until next release, as the risk is high, and this is an unlikely use case.

**Comment by f1oki** [comment]
Wouldn't it suffice to use something like

```C++
if (currentTargetTemp > previousTargetTemp) { ... }
else { ... }
```

in `MashDesigner::maxTemp_c()` and  `MashDesigner::minTemp_c()`?

**Comment by rocketman768** [comment]
I tried it. The problem with that is that the sliders need to move in the opposite direction when the temperature goes down. That requires more logic throughout the rest of the file. It's doable, just not a quick fix.

**Comment by f1oki** [comment]
Right on! I hadn't thought about that.
